### ISSUE TITLE
Rename to match PyNN convention

### ISSUE THREAD

**Issue by mossblaser** [SpiNNakerManchester/sPyNNaker#1]
Since PyNN has the strong convention of using `pyNN.simulatorname` for backends, I suggest renaming this repository `pyNN.spinnaker`.

**Comment by alan-stokes** [comment]
so during pynn scripts, you can use pyNN.spinnaker, this was done during Rowley's lovely instlalation stuff. Changing the repository is a differnet issue and is unlikely to happen due to all the interconnections.
