### ISSUE TITLE
binaries failed to compile with dma cache. so tests with them will fail. 

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#1035]
IF_curr_exp_stdp_mad_pair_additive_structural_last_neuron_distance_weight
IF_cond_exp_stdp_mad_pair_additive_structural_last_neuron_distance_weight
IF_cond_exp_stdp_mad_pair_additive_structural_random_distance_weight
IF_curr_exp_stdp_mad_pair_additive_structural_random_distance_weight
IF_cond_exp_stdp_mad_nearest_pair_additive_structural_last_neuron_distance_weight

**Comment by dkfellows** [comment]
I guess we're not planning on doing much about DMA caching now.
