### ISSUE TITLE
/test_iobuf_without_during_run_flag vs bitfields

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#1064]
spynnaker_integration_tests/test_iobuf/test_iobuf_without_during_run_flag
has bitfield cfg flags.
Should it be run against bitfields or are these just for safety?

**Comment by rowleya** [comment]
Guessing it used to make it faster to run; currently I think they are disabled anyway by default.

**Comment by Christian-B** [comment]
tested already deleted so issue no irrelevant
