### ISSUE TITLE
SpYNNakerNeuronGraphNetworkSpecificationReport untested requires graphviz

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#1078]
The report SpYNNakerNeuronGraphNetworkSpecificationReport  which is triggered by the cfg setting
[Reports]   
draw_network_graph=True

requires graphviz

Currently
import graphviz
is a delayed import hidden in a method
Suggesting that at some point someone had trouble with graphviz and a testing platform.
It also requires actual graphviz to be installed to run

So the questions is.
Do we want to to test this method?

If so how do we install graphviz in github action and on Jenkins.

Once Graphviz is installed be can trigger this by changing "draw_network_graph" to "write_network_graph"
or by adding 
draw_network_graph=True to one of the tests.

---
I also see nothing Spynnaker specifc or (needing a board) so would suggest if this is worth testing to
move it to FEC and test it with a unittest

**Comment by dkfellows** [comment]
Installing graphviz is not too difficult in a Github Actions workflow; https://github.com/marketplace/actions/setup-graphviz wraps it up conveniently. On Jenkins, it's probably best to just add it to the image (and no, I don't know how to do that).

**Comment by dkfellows** [comment]
And looking through https://github.com/ts-graphviz/setup-graphviz/blob/master/src/Installer.ts, I see that it's probably just adding this APT package: `graphviz` (and maybe also `libgraphviz-dev`). We've already got a [tested `apt-get-install` action of our own](https://github.com/SpiNNakerManchester/SupportScripts/tree/master/actions/apt-get-install) and don't need to support non-Linux for testing.
