### ISSUE TITLE
C-code multiple module dependancies

### ISSUE THREAD

**Issue by neworderofjamie** [SpiNNakerManchester/sPyNNaker#109]
If you're developing a new neural model/learning rule in a new module (as one should!) and it depends on components from extra models (e.g. ca2-based adaptive behaviour) and sPyNNaker i.e. everything else, I don't believe the current Makefile system supports this. The workaround of copying the required bits of extra models to your own module is slightly sad-making :)

**Comment by rowleya** [comment]
I agree with this.  I tried to make it multiple-module-capable, but have so far failed and run out of time to continue looking at it.  Other changes may have made this easier since I last tried.  Hopefully this bug will enable me to spend more time on this in future...

**Comment by rowleya** [comment]
I believe this is now fixed - you can specify multiple source folders
