### ISSUE TITLE
pip 21.2 resolver taking forever to select dependencies in python actions

### ISSUE THREAD

**Issue by andrewgait** [SpiNNakerManchester/sPyNNaker#1105]
The new release of pip is taking forever to decide on dependencies in our python Github actions; this is a known issue with pip, so setting up this issue to track the progress at https://github.com/pypa/pip/issues/10201.

For now it's probably a good idea to pin pip to an earlier version.

**Comment by dkfellows** [comment]
Is this still an issue?

**Comment by Christian-B** [comment]
Uncapped pip (straight to master as otherwise not testable.

Appears to work.
