### ISSUE TITLE
bugs for pool-dense connector

### ISSUE THREAD

**Issue by chanokin** [SpiNNakerManchester/sPyNNaker#1107]
Hey, I just found a couple of bugs in the code. In line 291 of _pool_dense_connector.py_ a value of `1` should be converted (with `self.__recip(1)`) to the appropriate fixed-point representation used in the C-side.

https://github.com/SpiNNakerManchester/sPyNNaker/blob/f526672edb463aa63c2826a556e694944eadac0e/spynnaker/pyNN/models/neural_projections/connectors/pool_dense_connector.py#L291

In line 183 of _local_only_pool_dense_impl.c_ the variable `index` so far has the row for the weight matrix but the matrix is now stored in row-major format. This is easily fixed with a multiply by the number of post neurons (which still needs to be saved into a local variable from the `config` struct).
https://github.com/SpiNNakerManchester/sPyNNaker/blob/f526672edb463aa63c2826a556e694944eadac0e/neural_modelling/src/neuron/local_only/local_only_pool_dense_impl.c#L183

**Comment by chanokin** [comment]
Also, weights should be divided by the pooling area, I guess somewhere around here: 

https://github.com/SpiNNakerManchester/sPyNNaker/blob/f526672edb463aa63c2826a556e694944eadac0e/spynnaker/pyNN/models/neural_projections/connectors/pool_dense_connector.py#L94-L100

**Comment by rowleya** [comment]
These should all be fixed in the branch now.

Should weights in the convolution connector also be divided by the pooling area if that is used there?

**Comment by chanokin** [comment]
I hadn't really checked the Conv part and it seems to work fine so far 😆 But yes, these should be divided as well.

**Comment by rowleya** [comment]
OK, that is there too now!

**Comment by chanokin** [comment]
Awesome, I've tested with the small CNN MNIST network and it works great!
