### ISSUE TITLE
get_v locks up simulation if there had been no record_v declaration.

### ISSUE THREAD

**Issue by SimonDavidson** [SpiNNakerManchester/sPyNNaker#113]
I added a get_v to a pyNN script, but didn't put in the record_v earlier in the script (user error).

When get_v was executed, it tried to read data from the target cores anyway, but as there was no data present the simulation just hung (hanged?).

In earlier versions of the tools, the pyNN interpreter would check and fail gracefully if you tried to do a get_v when you never asked for the information with record_v first. This is a better way to do things.

**Comment by alan-stokes** [comment]
Hi Simon, 

It was due to a missing a few checks in the population class. Ive added them into a branch called #fix_get_v_issue

Ive made a pull request, and got Jamie to check it for me to keep the flow of checks correct.

its now in master and thus is fixed.

**Comment by SimonDavidson** [comment]
Hi Alan,

Thanks!

BTW: I'm on holiday this week, but available by email  (mostly).

I hope you holiday went well.

Simon

On 27/07/2015 15:08, Alan Stokes wrote:
>
> Hi Simon,
>
> It was due to a missing a few checks in the population class. Ive 
> added them into a branch called #fix_get_v_issue
>
> Ive made a pull request, and got Jamie to check it for me to keep the 
> flow of checks correct.
>
> its now in master and thus is fixed.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SpiNNakerManchester/sPyNNaker/issues/113#issuecomment-125218966>.
>


-- 
Simon Davidson,
Research Fellow,
APT Group, School of Computer Science,
University of Manchester,
Manchester
M13 9PL
simon.davidson@manchester.ac.uk
