### ISSUE TITLE
Setting duration parameter of poisson spike source to None makes it stop after 4s

### ISSUE THREAD

**Issue by neworderofjamie** [SpiNNakerManchester/sPyNNaker#115]
I fixed this in https://github.com/SpiNNakerManchester/sPyNNaker/commit/d5728965d4868e5de8a0d3ed0f389dcae61800be, so feel free to cherry pick into master.

**Comment by alan-stokes** [comment]
So fixed in master now. I wasnt able to reproduce the error you expressed, but I can see how the line looks dubious in the possion. My persoanl feel is to make duration = runtime at that point, but after discussions with jamie, i'm ...... ok in leaving it as FFFFFFFF
