### ISSUE TITLE
Missing exp function in distance dependent probability connector

### ISSUE THREAD

**Issue by chanokin** [SpiNNakerManchester/sPyNNaker#119]
Hi,
I was trying to use the DistanceDependentProbabilityConnector class and it threw an error about a missing exp function when the distance expression is parsed. 

To fix it I just added:
from numpy import exp
to 
sPyNNaker/spynnaker/pyNN/models/neural_projections/conectors/distance_dependent_probability_connector.py

It feels like there should be a more general solution, but I'm not sure what the best thing to do is.

**Comment by AlexRast** [comment]
I agree that this is a problem after running into a similar situation. The 
essential issue is that PyNN allows an arbitrary expression for the distance 
dependence - which could itself come from any external python module. The Python 
import model doesn't make imports in an enclosing scope automatically available 
to enclosed functions or classes, so we can't do this simply by importing the 
appropriate functionality in the top-level PyNN script.

The connector could possibly parse the expression looking for any dotted 
subreferences and then import any modules required, i.e. if you had something like:

d_expression = "math.exp(d)" the connector could extract the math prefix using a 
regexp and then run

import math

before evaluating the expression, but this seems tedious and error prone to me.

We can probably make the intelligent guess that math and numpy are likely to be 
useful and always import them into DistanceDependentProbabilityConnector (I can 
make the change and issue a pull request tonight if desired) but that's not a 
fully general solution, it only fixes a number of "typical" cases.

Any other thoughts on how this might be achieved more practicably?

**Comment by apdavison** [comment]
It's not so bad. This is not documented, but the distance expression can only contain certain functions and constants from NumPy (plus builtin Python functions like `abs()`, of course).

The following import statement should cover it:
```
from numpy import arccos, arcsin, arctan, arctan2, ceil, cos, cosh, exp, fabs, \
    floor, fmod, hypot, ldexp, log, log10, modf, power, sin, sinh, sqrt, tan, tanh, \
    maximum, minimum, e, pi
```

**Comment by alan-stokes** [comment]
Having read this. Im happy to follow andrew davision here and use the above improt def. This ahs been done and psuhed into the Pynn changes branch which is still collecting changes before being pulled and reviewed.

**Comment by AlexRast** [comment]
As long as AD says that's how the functionality is supposed to be supported 
anyway, I think there's no reason not to do it. In any case this should end 
issues - but we should therefore document what functions are supported. (We can 
do this by reference to the Numpy documentation)

**Comment by alan-stokes** [comment]
merged into master. will be in the arbitiriary release. issues being closed accordingly.

**Comment by neworderofjamie** [comment]
I hope that's not how you're going to spell arbitrary :)

**Comment by alan-stokes** [comment]
*Arbitrary (I have to go to culture ships wiki page to find the corect spelling. lol).
