### ISSUE TITLE
Population method tset() results in "NotImplemented" Exception

### ISSUE THREAD

**Issue by astoeckel** [SpiNNakerManchester/sPyNNaker#121]
The following two PyNN scripts should be equivalent and perfectly valid:

Variant 1:

    inputPopulation = sim.Population(data.nIn, sim.SpikeSourceArray,
        cellparams = {'spike_times': np.array(data.inputNeuronSpikeTimes)}, label='input')

Variant 2:

    inputPopulation = sim.Population(data.nIn, sim.SpikeSourceArray,
        cellparams = {'spike_times':[]}, label='input')
    inputPopulation.tset('spike_times', np.array(data.inputNeuronSpikeTimes))

(I need the a little bit strange Variant 2 due to a problem with the ESS).

However, with sPyNNaker Variant 2 crashes with the following backtrace:

    File "/localhome/nmpidemo/RemoteSpiNNaker/temp/job8746647657467586056.tmp/lib/simulation_pyNN_v7.py", line 23, in execute
        inputPopulation.tset('spike_times', np.array(data.inputNeuronSpikeTimes))
    File "/localhome/nmpidemo/sPyNNaker/sPyNNaker/spynnaker/pyNN/models/pynn_population.py", line 645, in tset
        raise NotImplementedError
    NotImplementedError

I see no reason why setting the parameters inline in the Population constructor should work without "tset" being implemented, so I guess this is a bug.

**Comment by alan-stokes** [comment]
fixed in branch pynn_changes. Is awaiting extra funcs from other issues before being pulled and reviewed

**Comment by alan-stokes** [comment]
merged into master. will be in the arbitiriary release. issues being closed accordingly.
