### ISSUE TITLE
SplitterAbstractPopulationVertexNeuronsSynapses used in examples and intro lab but not in actual code

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#1213]
The SplitterAbstractPopulationVertexNeuronsSynapses appears to be hard coded into a number of examples and introlab but does not appear to be used in actual code.

1. Is this correct
2. If yes would it not be better to change the examples to use the splitter used eslewhere

**Comment by rowleya** [comment]
1. The splitter is used in the microcircuit example, as well as a few others as a demonstration and to ensure it gets used.
2. Every example that uses the splitter also has a version that doesn't, except the microcircuit (where it is essential to make it work in real-time).

Note that once the next branch goes in from reduce_overhead (once working), this will make the use of the splitter more automatic in some examples e.g. where certain combinations of things make a single binary no longer work anyway.  An eventual long term plan would be to try to find ways to automatically select the splitter for other cases too e.g. it might be selected automatically for 0.1ms in real time, or else some calculations could be done to work out when it might be needed and how many synapse cores might be needed (up to a maximum given the number of cores on a chip).

**Comment by Christian-B** [comment]
ok clearly worth keeping. Thanks.
