### ISSUE TITLE
"spiNNaker" module missing getters

### ISSUE THREAD

**Issue by astoeckel** [SpiNNakerManchester/sPyNNaker#123]
The "pyNN.spinnaker" module does not expose some of the API functions listed for the "simulation" module in the PyNN documentation, such as:

* `get_time_step()`
* `get_min_delay()`
* `get_max_delay()`

As far as I understood it, there should be a getter for all common `setup` properties.

**Comment by alan-stokes** [comment]
fixed in branch #pynn_changes which will be merged into master once other issues been covered.
