### ISSUE TITLE
router_report_from_paths does not work with virtual vertex

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#1235]
To replicate.
Set cfg
[Reports]
write_router_reports= True

run Spinnaker unittest

Virtual Vertex are not in Placements

**Comment by Christian-B** [comment]
Code that goes wrong is https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/blob/d3e083cac13a6599ab57c96ba6a7d392af38853e/spinn_front_end_common/utilities/report_functions/reports.py#L199

Which calls  FecDataView.get_placement_of_vertex(m_vertex)

@rowleya says "There are helpers that let you find the "placement" to start from"

**Comment by rowleya** [comment]
See here: https://github.com/SpiNNakerManchester/PACMAN/blob/master/pacman/utilities/algorithm_utilities/routing_algorithm_utilities.py#L543

and here: https://github.com/SpiNNakerManchester/PACMAN/blob/master/pacman/utilities/algorithm_utilities/routing_algorithm_utilities.py#L558

**Comment by Christian-B** [comment]
fixed
