### ISSUE TITLE
Recorded gsyn for IF_cond_exp has unexpected format

### ISSUE THREAD

**Issue by astoeckel** [SpiNNakerManchester/sPyNNaker#124]
For PyNN 0.7.5 I expect the result for "record_gsyn" to be of the form

    neuronId, time, gE, gI

where gE is the synaptic conductance for the excitatory channel and gI is the synaptic conductance for the inhibitory channel.

However, sPyNNaker only returns a 3-column array.

     neuronId, time, ?

However, the result of record_gsyn does not seem to be correctly defined in the PyNN documentation, so this might not be a bug.

Furthermore, this problem is obsolete with PyNN 0.8 as the record api received a major overhaul, separating recording of gE and gI.

**Comment by rowleya** [comment]
I believe that for conductance-based neurons, we return:
neuronId, time, gE - gI

i.e. the overall conductance from the synapses.  I don't think that this is wrong for PyNN 0.7:
http://neuralensemble.org/trac/PyNN/wiki/API-0.7#get_gsynselfgatherTruecompatible_outputTrue

I am not sure what this is meant to do for current-based neurons, but we currently return:
neuronId, time, cE - cI

where cE is the total excitatory input current and cI is the total inhibitory input current.  I assume that it is not possible to compute the synaptic conductance for a current-based neuron, but if it is, I am happy to update this code.

**Comment by apdavison** [comment]
This is a documentation error in PyNN. My apologies. I've updated the docstrings and the API documentation - see https://github.com/NeuralEnsemble/PyNN/commit/a7e9f0099d9b6c8308d88aaad73a3bdf214ca36e

(The reason for the mistake is probably that when Vm and gsyn data are written to file, the times are not included).

**Comment by neworderofjamie** [comment]
Out of interest, what should the behaviour of get_gsyn be when called on a
neuron with current-based synapses?

**Comment by apdavison** [comment]
BTW, in PyNN 0.7, recording synaptic currents is not supported. For current-based neurons, calling `population.record_gsyn()` should raise a `pyNN.errors.RecordingError` exception. Calling `population.get_gsyn()` should raise `pyNN.errors.NothingToWriteError` (although I've just noticed that the NEST backend raises `KeyError`).

This limitation is removed in PyNN 0.8

**Comment by rowleya** [comment]
Interesting - I think we might be currently writing the times to a file as well.  This should be changed if so.

**Comment by alan-stokes** [comment]
So part 1 of changes related to this issue: we've now added a warning for when recording g_syn on none conductance models. 

part 2 of seperating inhib and excit will be done soon.

**Comment by alan-stokes** [comment]
merged into master. will be in the arbitiriary release. issues being closed accordingly.
