### ISSUE TITLE
Latest Ubuntu doesn't support Python 3.6

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/sPyNNaker#1255]
Ubuntu 22.04 doesn't support Python 3.6.

This is an issue because our CI builds use `ubuntu-latest` and Python `3.6`. We should choose which we want.
* If we want to support building against 3.6, we must lock the Ubuntu version to `ubuntu-20.04`.
* If we want to support building on Ubuntu "latest", we must update the minimum Python version. (Careful, it's used in a number of places.)

**See also:** actions/setup-python#544

**NB:** This change must be applied to all our Python projects.

**Comment by dkfellows** [comment]
The oldest supported Python version on Ubuntu 22.04 appears to be 3.7.13, according to the metadata at https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

**Comment by andrewgait** [comment]
Given 3.6 reached end of life at the end of last year it's probably best if we drop it.
