### ISSUE TITLE
Unable to connect to board without BMP connection

### ISSUE THREAD

**Issue by chanokin** [SpiNNakerManchester/sPyNNaker#126]
Trying to run a simple network on a spinn-5 boad without BMP network connection. I get the following error:

spinnman.exceptions.SpinnmanException: BMP connection to 192.168.240.0 is not responding, please check that it is connected

**Comment by alan-stokes** [comment]
have generated a fix under branch #bmp_off_auto_detect which resides over spinnman, front end common and spynnaker. It is awaiting in a pull request, awaiting review by the software team.

**Comment by alan-stokes** [comment]
merged info master now. please redownload master branches and try again. please note of the new config param which you will need to set to false to allow this fix to engage.
