### ISSUE TITLE
Fundamentally broken test

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/sPyNNaker#1290]
In `test_csa_connector.py`, the test `test_csa_block_connector` is fundamentally broken; it depends on passing 9 arguments to the `create_synaptic_block()` method despite that only taking 5. The breakage is currently being hidden by the workaround for INCF/csa#17.

It isn't at all clear to me how to fix things.

**Comment by andrewgait** [comment]
This was fixed by https://github.com/SpiNNakerManchester/sPyNNaker/pull/1291.
