### ISSUE TITLE
getWeights() Function

### ISSUE THREAD

**Issue by WemboLi** [SpiNNakerManchester/sPyNNaker#131]
Hi guys,
I am trying to implement STDP learning rule on spinnaker and get a trivial matter about the training of weight. I initialize the weights and two population with following part:

ON_pop = sim.Population(prepop_size, sim.SpikeSourceArray, spikeArrayOn, label='inputSpikes_On')
post_pop= sim.Population(postpop_size,sim.IF_curr_exp, cell_params_lif, label='post_1')
weight_ini = np.random.normal(0.108, 0.003,prepop_size*postpop_size).tolist()
connectionsOn = sim.Projection(ON_pop, post_pop, sim.AllToAllConnector(weights = weight_ini,delays=2), synapse_dynamics=sim.SynapseDynamics(slow=stdp_model))

After training, I get the trained weight with function getWeights():
weights_trained = connectionsOn.getWeights(format='list')

And save it with scipy.io.savemat('trained weight.mat',{'weight':weights_trained). But when I load the weights again with scipy.io.loadmat() and apply the trained weights to connections between ON_pop and post_pop again in another simulation:
connectionsOn = sim.Projection(ON_pop, post_pop, sim.AllToAllConnector(weights = weights_trained,delays=2))

 the neuron network behaves differently from the stable trained phase in the first simulation. Is it because that getWeights() store weights in a different format?

**Comment by neworderofjamie** [comment]
Hi Wembo,

You need to convert the downloaded weights to the correct format like this:

```
def convert_weights_to_list(matrix, delay):
    def build_list(indices):
        # Extract weights from matrix using indices
        weights = matrix[indices]

        # Build numpy array of delays
        delays = numpy.repeat(delay, len(weights))

        # Zip x-y coordinates of non-zero weights with weights and delays
        return zip(indices[0], indices[1], weights, delays)

    # Get indices of non-nan i.e. connected weights
    connected_indices = numpy.where(~numpy.isnan(matrix))

    # Return connection lists
    return build_list(connected_indices)

sim.FromListConnector(convert_weights_to_list(downloaded_weights, delay))
```
