### ISSUE TITLE
Ring buffer sigma and spikes-per-second on a per synapse-type and per-population basis

### ISSUE THREAD

**Issue by neworderofjamie** [SpiNNakerManchester/sPyNNaker#132]
Different populations have incoming spike trains with different statistics therefore it makes little sense to specify this globally (also the global parameters are copied into each vertex anyway!). Also, different synapse types have different statistics and separate ring-buffer shifts to scale them with, so ideally, you should also be able to specify ring buffer sigma and spikes-per-second separately for different synapse types.

**Comment by alan-stokes** [comment]
changes have ben done to spinnaker to allow changes of the spikes per second and ring buffer sigma from a top elvel pynn script.

**Comment by AlexRast** [comment]
Does this do it on a per-population basis? If so then I think there's a strong 
case to be made as mentioned earlier regarding external I/O functionality to 
migrate these 2 parameters into the subclass of vertices that actually use it 
rather than making them global to all models.

**Comment by rowleya** [comment]
Unfortunately, this has been added to take account of how PyNN 0.7 works (you pass the class and the initialization parameters, rather than an instantiated class).  As I understand it, PyNN 0.8 passes an instantiated class, so at this point, we will have to change to a different interface for these parameters.

**Comment by AlexRast** [comment]
Isn't that the same thing (i.e. the initialisation parameters that are valid for 
a population type are themselves dependent on the type of population being 
instantiated)? So these can easily be asssociated with particular population 
classes, which will be instantiated as the appropriate vertex subclass, while 
other population classes neither take nor use these parameters.

**Comment by alan-stokes** [comment]
Different populations have incoming spike trains with different statistics therefore it makes little sense to specify this globally (also the global parameters are copied into each vertex anyway!). 

This has been merged into master. the changing it for different synapse types, has not yet been completed.

**Comment by alan-stokes** [comment]
splitting the extra part into a new ticket. so we can record that 1/2 is done by oen release date and the other by dec.

**Comment by alan-stokes** [comment]
linked to #136
