### ISSUE TITLE
When you call get_v and get_gsyn, caching the recorded value is a bad idea

### ISSUE THREAD

**Issue by neworderofjamie** [SpiNNakerManchester/sPyNNaker#141]
These can easily be huge and, especially on 32-bit machines fill all available memory. If the user wants to cache these values, they can, but surely it's not PyNN's responsibility!

**Comment by rowleya** [comment]
I think I had put this in there to match the spikes - I noticed a number of people using getSpikes and printSpikes in the same script for the same populations.  However, if this causes memory problems, I could just leave it for spike recording (I haven't seen anyone use get_v and print_v for the same population for example).  I guess that both using and storing the spikes is a more general use case.

**Comment by neworderofjamie** [comment]
Isn't that basically user error though meaning that displaying a warning be
a better idea?

**Comment by apdavison** [comment]
It's not a user error to call getX() and printX() in the same script.

**Comment by neworderofjamie** [comment]
Maybe error's the wrong word, isn't it user mis-understanding (in this case
of the fact that those operations involve downloading large amounts of data
off SpiNNaker)?

**Comment by AlexRast** [comment]
Can this not be a spynnaker.cfg option? Presumably those who are going to use 
recorded spikes or any other value twice for different purposes in the same 
script know why they're doing it. They can opt to cache the values for speed if 
they want, or maybe indeed some of them don't want to, because their host 
resourcss are insufficient. I suspect 2 different uses of the same spike data 
will be relatively rare, so my sense is that caching ought to be off by default. 
In any case I see no reason why we should make a fixed decision on behalf of the 
user.

**Comment by rowleya** [comment]
I suspect that this may be the only option, as we can’t guess what the users might do – including calling getSpikes more than once! We could also do more caching to disk here as the disk read is likely to be faster than reading the machine.

I will look into some changes...

**Comment by neworderofjamie** [comment]
I don't see why the solution needs to be so complicated! Attempting to
second-guess ever single thing a user MIGHT do seems a somewhat foolish
quest...If the users are doing something small/don't care about performance
they can call both methods, it should display a warning and it'll cost them
30s of their lives as it downloads twice. If they do, just call getSpikes
and numpy.save the result!

**Comment by rowleya** [comment]
I added a fix to the branch that I just merged - this saves the results in a temporary file rather than in memory.  It seems to work - let me know if it avoids the memory issues for you (as I have a 64-bit system).

**Comment by alan-stokes** [comment]
Rowley has fixed this within the master branch, will be introduced in our bug release of arbitiary this week. 

therefore closing issue
