### ISSUE TITLE
Should n_colour_bits be a ApplicationVertex property

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#1413]
SynapseDynamicsStructuralCommon.__write_prepopulation_info 
https://github.com/SpiNNakerManchester/sPyNNaker/blob/5f8270d52781a0990e15837b38ef3a5a9c108291/spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py#L268

assumes that the "app_vertex" has a n_colour_bits property.
yet only DelayExtensionVertex, PopulationApplicationVertex (and a few of its sublcasses) have it

**Comment by rowleya** [comment]
I think PopulationApplicationVertex has it

**Comment by Christian-B** [comment]
The DelayExtensionVertex has a method with the same name but it is used in a seperate context.

So for SynapseDynamicsStructuralCommon we can just assert we have a PopulationApplicationVertex
