### ISSUE TITLE
mean_spike_count() and meanSpikeCount()

### ISSUE THREAD

**Issue by apdavison** [SpiNNakerManchester/sPyNNaker#142]
A tiny issue, but one that is likely to break a lot of scripts:

In PyNN 0.7, `Population.meanSpikeCount` exists, but `Population.mean_spike_count` does not. However, sPyNNaker uses the latter name.

In PyNN 0.8, the first name still exists but is deprecated, the preferred form is the second.

Can I suggest adding "meanSpikeCount" as an alias for "mean_spike_count"?

**Comment by alan-stokes** [comment]
Rowley has fixed this within the master branch, will be introduced in our bug release of arbitiary this week. 

therefore closing issue
