### ISSUE TITLE
Projection does not support passing an rng

### ISSUE THREAD

**Issue by Scaatis** [SpiNNakerManchester/sPyNNaker#151]
pyNN allows passing an optional parameter rng to a Projection that will be used by the Connector. sPyNNaker allows passing this parameter, but it is not used in any way. This can make porting pyNN scripts more difficult.

**Comment by alan-stokes** [comment]
this is currently only true with fixed_number_post_connector. the rest now use the rng.

**Comment by alan-stokes** [comment]
this has been solved (likely during the pynn 0.8 integration) as it now uses self._rng.

therefore closing issue
