### ISSUE TITLE
getSpikes from a spikeSourceArray returns time values not adjusted for timestep

### ISSUE THREAD

**Issue by SimonDavidson** [SpiNNakerManchester/sPyNNaker#153]
So this issue is specifically related to the spike source array, and concerns the output of the getSpikes() function.

The 'time' values being returned are the internal counts of numbers of time steps, so they need to be multiplied by the size of each timestep to return a value in milliseconds.

This does not occur for getSpikes called on standard neuron populations - I get the correct timestamp-adjusted values for these.

**Comment by alan-stokes** [comment]
Hi Simon, 

Given the verbal discussion with the spike test I ran. It seems that the issue has been resolved with the latest refactor. You're branches are likely out of date. 

Note: we have discussed and will be updating his branches accordingly today.
