### ISSUE TITLE
Spikes lost when reading back with get_spikes on spikeSourceArray

### ISSUE THREAD

**Issue by SimonDavidson** [SpiNNakerManchester/sPyNNaker#154]
I created an array of 100 sources and set input spikes on only a few of them. I'm fairly sure they were correctly applied to the network but when I read them back with getSpikes(), most of them were not returned.

I had to manually add a spike at 1.0 ms to each input neuron to have them return anything at all. My real spikes were all lost.

PyNN script (libSingleNeuronStdp) available upon request.

**Comment by alan-stokes** [comment]
Send me the script. Ill see if this has also been solved with the master.

**Comment by alan-stokes** [comment]
closing in the assumption that this issue has been fixed by the multiude of fixes for simons system. If this is invalid, pelase reopen.
