### ISSUE TITLE
Exception when calling "tset" for "spike_times" for non-uniform spike train lengths

### ISSUE THREAD

**Issue by astoeckel** [SpiNNakerManchester/sPyNNaker#158]
Consider the following example:

```python
import pyNN.spiNNaker as sim

sim.setup()
p = sim.Population(3, sim.SpikeSourceArray, {"spike_times": []})
p.tset("spike_times", [[10.0, 20.0], [10.0], [30.0, 40.0, 50.0]])

sim.run(1000.0)
```
This code crashes at "p.test" with the following exception:
```
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    p.tset("spike_times", [[10.0, 20.0], [10.0], [30.0, 40.0, 50.0]])
  File "/localhome/nmpidemo/sPyNNaker/sPyNNaker/spynnaker/pyNN/models/pynn_population.py", line 746, in tset
    self.set(parametername, value_array)
  File "/localhome/nmpidemo/sPyNNaker/sPyNNaker/spynnaker/pyNN/models/pynn_population.py", line 671, in set
    self._parameters[parameter] = value
  File "/localhome/nmpidemo/sPyNNaker/sPyNNaker/spynnaker/pyNN/utilities/parameters_surrogate.py", line 41, in __setitem__
    self.vertex.n_atoms)
  File "/localhome/nmpidemo/sPyNNaker/sPyNNaker/spynnaker/pyNN/utilities/utility_calls.py", line 49, in convert_param_to_numpy
    return numpy.array(param, dtype=float)
ValueError: setting an array element with a sequence.
```

However, if I change the line to (now the individual SpikeSources emit the same number of spikes):
```python
p.tset("spike_times", [[10.0, 20.0], [10.0, 20.0], [30.0, 40.0]])
```
it does not crash (at least not at p.tset, but that's another story).

**Comment by astoeckel** [comment]
Note that a similar bug existed in the Spikey PyNN backend, but it was easy to fix: https://github.com/electronicvisions/PyNN/pull/3

**Comment by alan-stokes** [comment]
The new version of the software stack (as of master currently) seems to not have this issue. There has been a signifcant refactor of the way the neural models are represented in python (to more tie in with how the c code is now operating) and a quick test with your params seems to show the spike times being set correctly. Therefore I would state that this issue is closed given the next release will have it fixed. 

You are welcome to download the master branches of everything and try it out by the way.

**Comment by astoeckel** [comment]
> You are welcome to download the master branches of everything and try it out by the way.

I can't. I'm one of those unfortunate souls who don't have a SpiNNaker board on their desk and have to rely on a working version on the Neuromorphic Compute Platform.

**Comment by alan-stokes** [comment]
Then I fear you will need to wait till December for the portal to be updated with the offical release of AnotherFineProductFromTheNonsenseFactory is pushed onto the portal. I dont know if Rowley is willing to update the portal to a arbitary version of the tool chain. It may be that we can make a pre-release of AnotherFineProductFromTheNonsenseFactory. But that requires us to decide on where to make that cutoff, and if this is the case, id rather wait till the outstanding pull requests have been completed.
