### ISSUE TITLE
PopulationView is not implemented

### ISSUE THREAD

**Issue by astoeckel** [SpiNNakerManchester/sPyNNaker#160]
According to the PyNN 0.7 API documentation, the "PopulationView" class seems to be the preferred way to access individual neurons in a neuron population. However, as of now this feature is not implemented.

See also:
https://github.com/hbp-sanncs/pynnless/commit/000090a2bef6850b61c4b45b2aa3090836d31b9b#diff-4793782cbb43b2133b14850a65492144R619

**Comment by AlexRast** [comment]
From what I can make out of the documentation the PopulationView is merely one 
interface that you *could* use to access individual neurons. You can also access 
neurons by simple indexing in the population itself (note the __getitem__ method 
for a Population). As I understood it PopulationViews are more about getting 
more-or-less arbitrary subsets of entire Populations that you may want to treat 
in some systematic way distinct from the population as a whole (e.g. setting a 
group of parameters for a set of neurons within the same Population to different 
values).

PopulationViews will eventually be supported but I will leave it to Andrew 
Rowley to indicate if there is any particular planned date for such support.

**Comment by alan-stokes** [comment]
The plan of action is to support this by April next year [end of sga0]. This is more of a place holder though, given there is a multitude of other tasks that need to be done before reaching this one.

**Comment by astoeckel** [comment]
> You can also access neurons by simple indexing in the population itself (note the __getitem__ method for a Population).

As I hadn't considered using this interface I euphorically got into hacking this interface for accessing individual neuron parameters into PyNNLess, but it doesn't seem like this interface works correctly with any backend.

See: #163 , https://github.com/NeuralEnsemble/PyNN/issues/380, https://github.com/NeuralEnsemble/PyNN/issues/381

As I see it, the specification explicitly permits to return a PopulationView from `__getitem__` so #163  is actually blocked by this issue.

**Comment by neworderofjamie** [comment]
Before you waste too much time on this, I'm pretty sure you can't access
neurons by their indices on SpiNNaker either!

Cheers

Jamie

**Comment by Christian-B** [comment]
No more development is being done in PyNN 0.7.

So work along these lines has been done in PyNN 0.8

if you need more than that please contact the mailing list.
