### ISSUE TITLE
Population constructor modifies given parameters

### ISSUE THREAD

**Issue by astoeckel** [SpiNNakerManchester/sPyNNaker#161]
In the following code
```
params = {}
res = sim.Population(count, sim.SpikeSourceArray, params)
```
the variable `params` is suddenly filled with new entries after sim.Population returns. An API which silently has such side effects is generally a bad thing, as the client code suddenly explodes at a totally unrelated location.

I propose to a) always perform a deep copy of mutable arguments b) to specify this in the PyNN specification.

See also:
https://github.com/hbp-sanncs/pynnless/commit/000090a2bef6850b61c4b45b2aa3090836d31b9b#diff-4793782cbb43b2133b14850a65492144R609

An alternative and much preferred solution would be to use a proper programming language with static typing and clear compile-time move, copy and reference semantics (such as C++11) ;-)

**Comment by alan-stokes** [comment]
having just pushed a quick fix into master for this. we now do a deep copy. My only fear about this is the speed requried to do this deep copy. But I think this is more a issue on the connectors/projections, not the population's so far, and therefore isnt too big a issue. 

Anyhow. it will be in the next release.
