### ISSUE TITLE
Delay extension may try to use key of None

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#164]
It is possible for a delay extension to end up with a key of None if all the outgoing edges are pruned.

**Comment by alan-stokes** [comment]
not possible with current version of the tools as the type of edge outgoing from a delay vertex is none filterable, and therefore there will alwyas be a edge and thus a key.

**Comment by rowleya** [comment]
This seems to be present again (delay edges can be filtered).  Note also related is that if the edge is filtered, there will be no DelayBlock for some subvertices.

**Comment by alan-stokes** [comment]
fixed again.
