### ISSUE TITLE
getSpikes from a external device, or delay_extension or other none neuron model

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#165]
the current implementation of getSpikes will crash with a atrribute error, not a confuigation error. As there is no attribute is_recording_spikes() on these types of vertices. There needs to be a check above for isinstance type

**Comment by Scaatis** [comment]
Possibly related, when I try to get spikes form a SpikeSourceArray when there are no spikes to get, I get
```
Traceback (most recent call last):
  File "dummy_net_multi_run.py", line 119, in <module>
    print "Total spikes from fast injector: %d" % len(fast_injector.getSpikes())
  File "/home/felix/Documents/SpiNNaker/sPyNNaker/spynnaker/pyNN/models/pynn_population.py", line 214, in getSpikes
    self._spinnaker.placements, self._spinnaker.graph_mapper)
  File "/home/felix/Documents/SpiNNaker/sPyNNaker/spynnaker/pyNN/models/spike_source/spike_source_array.py", line 204, in get_spikes
    n_machine_time_steps, placements, graph_mapper, self, return_data)
  File "/home/felix/Documents/SpiNNaker/sPyNNaker/spynnaker/pyNN/models/common/eieio_spike_recorder.py", line 92, in get_spikes
    result = numpy.vstack(results)
  File "/usr/lib/python2.7/dist-packages/numpy/core/shape_base.py", line 228, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate
```

**Comment by sergiodavies** [comment]
I experienced this when there is a spike_source_array population producing
no spikes during the simulation.
This should be corrected in the output buffering branch.

Regards

--

Dr Sergio Davies

Research associate - APT Group   Room IT 302 - IT Building
School of Computer Science       Oxford Road, Manchester
The University of Manchester     M13 9PL, U.K.

mailto: sergio.davies@manchester.ac.uk
mailto: sergio.davies@gmail.com
http://apt.cs.man.ac.uk/people/daviess/

2015-11-18 12:57 GMT+00:00 Felix Schneider <notifications@github.com>:

**Comment by alan-stokes** [comment]
This seems to be a repeat of a issue that (i think) Alan Diamond pointed out to us months ago, it was pushed in then, but must have reverted during merges. If Sergio has fixed it within the buffered out Branch, then it should fall into the master version sometime between now and the next release date. 

Alan

**Comment by alan-stokes** [comment]
having tested a SSA which didnt spike, it no longer crashes in master. Therefore when Another Fine Product From The Nonesense Factory is released at the end of the month, this issue will be done. 

therefore Im closing it now.
