### ISSUE TITLE
getWeights() appears to be broken in arbitrary

### ISSUE THREAD

**Issue by svadams** [SpiNNakerManchester/sPyNNaker#170]
When I do a run with STDP enabled and retrieve the weights after the run with getWeights() no weight changes are registered even though learning is happening (it is evident from other behaviour of the network). This was definitely working OK in little-rascal.

Note that Alex Rast at Manchester has replicated this error with the same network as me and so can provide the network if you need to inspect it.

This is fairly urgent as we are trying to do learning experiments for a paper and cannot do all the things we'd like if we can't get weights back or save weights out for testing.

Regards
Sam

**Comment by alan-stokes** [comment]
This has been deduced to be a error in how the script is setting the synaptic_dynamics of the projections. It seems Python supports allowing end users to add properties to instantiated classes and this is why the unsupported form of the setter did not fire off an exception. 

To clarify the synaptic_dynamics can only be set during projection instantiation so far, and thus using projection.synaptic_dynamics = blah will not work. 

Resulted in the closure of this issue.
