### ISSUE TITLE
SpikeSourceArray issue when spike output on every timestep

### ISSUE THREAD

**Issue by SimonDavidson** [SpiNNakerManchester/sPyNNaker#171]
I have 10 source neurons which spike every timestep, each source neuron going to its own single identical target neuron. I expect the target neurons to spike regularly and synchronously, but neurons 0, 1 and 2 do not. It appears to screw up when the sources spike on every time step, but works fine when it's every other time step.

Script attached. It's a python file but I had to change the extension to .txt to get this GitHub issue tracker to read it in.

[regular_stimuli.txt](https://github.com/SpiNNakerManchester/sPyNNaker/files/42625/regular_stimuli.txt)

**Comment by rowleya** [comment]
I have been investigating this - this seems to be down to an inability of python to be able to consistently divide one number by itself.  Interestingly, if you use a timestep smaller than your inter-spike interval, this doesn't happen.  I am assuming that the rounding errors are less obvious in this case.

I have managed to add in a calculation that seems to avoid these issues, and this seems to work well.  I have done this in the branch that I am merging just now, so it should be merged shortly.

I will close this ticket for now, but open it if you find this doesn't work once I do the merge.
