### ISSUE TITLE
setup.py fails when not using master branch

### ISSUE THREAD

**Issue by Scaatis** [SpiNNakerManchester/sPyNNaker#173]
The setup.py does seem to have been updated with the various branches.

I am on `work_flow_multi_run` and I get:
```
error: package directory 'spynnaker/pyNN/models/abstract_models/abstract_model_components' does not exist
```
After creating the folder, it runs successfully.

**Comment by alan-stokes** [comment]
will fix before this branch is in a release version

**Comment by rowleya** [comment]
This was a transient issue with setup.py that has been resolved.
