### ISSUE TITLE
Does SpiNNaker support infinite v_thresh?

### ISSUE THREAD

**Issue by Scaatis** [SpiNNakerManchester/sPyNNaker#174]
One implmementation detail for the HBP neurorobotics platform is that a neuron with infinite spiking threshold is created. Since I have no good test case right now, does SpiNNaker support this?
Basically, if I called:
```Python
 cellparams = {'v_thresh': float('inf'),
               'cm': 1.0,
               'tau_m': 20.0,
               'tau_syn_E': 10.0,
               'v_rest': 0.0}
self._cell = sim.Population(1, sim.IF_curr_exp, cellparams)
```
would it behave as expected?

**Comment by rowleya** [comment]
I doubt we would support it just now.  We use fixed point numbers on SpiNNaker, so it would be hard to represent an infinite threshold without some other support.  This could be realized simply by having an additional Boolean per neuron that specified infinite threshold or not, and then not spiking if threshold is infinite.  The other issue is with wrap arounds – eventually, you would reach the maximum value of the fixed-point representation (at just under 65536 I think), and then the voltage would become negative unless checked.

Given that the communication between platforms (and indeed neurons) will be spikes, and that this neuron can never spike, can you tell me how useful this really is?  Is there some behavior that occurs depending on the membrane voltage for example?

**Comment by Scaatis** [comment]
I'm not sure what unit that value is in, but I think a membrane voltage of 65535 ist unlikely to be reached, so I guess it is close enough to infinite. I'm closing this ticket.
