### ISSUE TITLE
outputTimesForSections configuration

### ISSUE THREAD

**Issue by Scaatis** [SpiNNakerManchester/sPyNNaker#175]
With the changes to the mapping work flow, the configuration option `outputTimesForSections` no longer has any effect.

**Comment by alan-stokes** [comment]
I alas have to disagree with you here. The outputTimesForSections parameter is used to instantiate the pacman algorithm executor on lines 300 to 302 on spinnaker.py.

This is used within the pacman algorithm selector throughout to determine if it should record the time it takes to run each algorithm. If this is set to false, id hope that this data is not recorded, but admittedly I always have it set to true, so I didn’t test the off mode.

There is a question over if we should not expose this dial, and just keep it true always.

**Comment by Scaatis** [comment]
Strange. I always have it set to true, but I thought it would print the time needed for e.g. getting membrane voltages to the console. Have I misinterpreted what this configuration option does?

**Comment by rowleya** [comment]
It used to do this, but I believe the current system outputs the times to an xml file at the end of simulation.

**Comment by alan-stokes** [comment]
Rowley: you would be correct in believing this. The data is more provenance data, and therefore it made sense to allow people who wish to benchmark the tools to use a xml file instead of having to search though textual output. 

Given this, i'm going to close the issue.
