### ISSUE TITLE
Change rate of PoissonSpikeSource

### ISSUE THREAD

**Issue by Scaatis** [SpiNNakerManchester/sPyNNaker#180]
I'm splitting this into a seperate issue as the whole thing seems to have become two different questions.

I want to be able to change the rate of a PoissonSpikeSource between runs. There exists [a commit](https://github.com/SpiNNakerManchester/sPyNNaker/commit/c55d38e5d1a67a929364f56aeca2265847028fe0) that does most of what one would need, but that was pre-multi-run. The changes to the C part were easy enough to merge, but I'm stumped at the python part. A number of significant changes took place between when this commit was written and now, and I have no idea how to get a changed rate to SpiNNaker. Some pointers would be appreciated.

**Comment by alan-stokes** [comment]
fixed via pynn behaviour
