### ISSUE TITLE
Configuration options are not parsed

### ISSUE THREAD

**Issue by Scaatis** [SpiNNakerManchester/sPyNNaker#185]
In the spynnaker.cfg files, all configuration options are read in as strings, even numbers and binary values. That means that the code line
```Python
if config.get("Reports", "writeProvanceData"):
```
does not have the intended effect. If you put False in the configuration file, it's just read as the string `"False"`. If you want it to actually evaluate to False, you have to set the configuration option to the empty string.

This combined with the fact that it should read "Provenance" makes this option very counterintuitive to use.

On a related note: What does that actually do? We noticed it significantly slows down multi-run on our new 48-node board, so we were wondering what this is for and if it is safe to turn off.

**Comment by rowleya** [comment]
There are other ways to get config values e.g. config.get_boolean, which will work.  If this is not actually being done somewhere where it should, that is a different issue, and needs to be fixed (I have seen cases in the past, so I will not be too surprised by this).  The spelling should also be fixed!

This will read some data from the machine if produced by the binary, so it would probably slow down the closed loop simulation to have it on.

**Comment by Scaatis** [comment]
Well it looks like get_boolean is not being used here, even though it should, as the value is used for an if statement. The line I posted is from spinnaker.py, line 540, though there are other, similar lines in that file.

**Comment by alan-stokes** [comment]
Ive corrected the issue of get_boolean in my auto_pause_and_resume brnach. once its all tied in, then itll slide into master. there's only 3 locations where the issue resides.

**Comment by alan-stokes** [comment]
this branch has been merged into master, and therefore this issue will be solved come the Another Fine Product From The Nonesance Factory release. Therefore closing this issue.

**Comment by neworderofjamie** [comment]
Nonce sense?
http://3.bp.blogspot.com/_Q8DzHn3JFIc/TE62334_cwI/AAAAAAAAACQ/9ymfSGkeRzo/s1600/collins_nonce1.jpg
