### ISSUE TITLE
pylab installation needed 

### ISSUE THREAD

**Issue by mahmoodalmansooei** [SpiNNakerManchester/sPyNNaker#189]
The installation guide does not content pylab package. please update accordingly

**Comment by rowleya** [comment]
pylab is installed by matplotlib as I understand it, which is detailed in the installation guide for the overall PyNN on SpiNNaker system here:
http://spinnakermanchester.github.io/2015.005.Arbitrary/PyNNOnSpinnakerInstall.html

This isn't required by any modules that I know of, but is commonly used by example scripts, so is recommended.
