### ISSUE TITLE
spin1 api can overrun on pause

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#202]
It is possible for the spin1_api to continue sending timer ticks even when paused, if the timer overruns its scheduled time.  The pause flag should be checked before sending any timer ticks

**Comment by andrewgait** [comment]
I'm a bit confused by this issue, to be honest - how does spin1_api manage to reach a paused state on a core without the time value in the neuron code reaching the set number of simulation ticks (whether it overruns or not...)?

**Comment by rowleya** [comment]
This is fixed now I think (someone can open it again if they think it isn't).  This was caused because we needed to make sure the recording data was finished before pausing the simulation, but because this writes to SDRAM, it could cause another timer tick to go off, meaning that the provenance says it has overrun even though it hasn't!  The resolution was to add an intermediate state, so the simulation could be paused, then recording data written, then update to a final state to say this has all been done.
