### ISSUE TITLE
Different post-synaptic neuron have same weights with lateral inhibitory

### ISSUE THREAD

**Issue by hh2712** [SpiNNakerManchester/sPyNNaker#207]
Hi,
I have constructed a two layer neural network with STDP mechanism and leaky integrate and fire model. For each neuron in the second layer, it imposes inhibitory connection to all other neuron on second layer.

I have then used getWeights() function to retrieve the weights. The post-synaptic neuron do behave as I expected, but there are neurons having exactly the same weights, even I have implemented the lateral inhibitory.

Could anyone kindly give me some suggestions on this? I have attached the relevant code below.

#-------------------------------------------------------------------------------------------------------------#
connectionsOn = sim.Projection(ON_pop, post_pop, sim.AllToAllConnector(
    weights = weight_ini,delays=1),
                               synapse_dynamics=sim.SynapseDynamics(
                                   slow=stdp_model))
#inhibitory between the neurons
connection_I  = sim.Projection(post_pop, post_pop,
                               sim.AllToAllConnector(weights = 5,delays=1,allow_self_connections=False),
                               target='inhibitory')

sim.run(simtime)
weights_trained = connectionsOn.getWeights(format='array')
sim.end()
#-------------------------------------------------------------------------------------------------------------#

Many thanks,
Hanyi

**Comment by AlexRast** [comment]
We need more information please to help you on this.

 From the code snippet and what you are describing it's difficult to tell what, 
if anything, is going wrong.

Can you describe what you would expect to see and why? Describe your network and 
how you're setting it up so we have the context. Can you also please give us a 
high-level description of what the network is supposed to do?

Also please send the full PyNN script and then it should be easier to identify 
what's happening.

Thanks.

**Comment by alan-stokes** [comment]
Can I ask that you move this discussion into the google group (https://groups.google.com/forum/#!forum/spinnakerusers). This is because I'd prefer the entire community (rather than just the software members [who follow spynnaker]) to help diagnose if this is either a misunderstanding on PyNN / how models work vs an actual software bug.

Therefore I'm closing the issue with the caveat that  if it indeed shows some flaw in the software, it can be reopened.

**Comment by hh2712** [comment]
No problem.

Thanks,
Hanyi

**Comment by hh2712** [comment]
Hi,
I have re-posted my question on google group again, with a clarified
background information and attached code underneath.

Would it be possible for you to help me look into this issue again?

Thanks and regards,
Hanyi
