### ISSUE TITLE
pynn script shouldnt need a population. 

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#213]
I know it seems a silly requirement, but i had to add a pop for icub reflector scipt to work correctly. I know andrew davidsion built test scripts that ran pynn without pops or projections, so we should try to detect this somehow and handle it. 

I know it goes against our logic, as thats really a wastage from the tools point of view (maybe we can put into FEC that when no vertices exist to just ignore this and put a warning).

regards
Alan

**Comment by alan-stokes** [comment]
fixed via:
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/173
https://github.com/SpiNNakerManchester/sPyNNaker8/pull/42
https://github.com/SpiNNakerManchester/sPyNNaker/pull/364

**Comment by Christian-B** [comment]
fixed
