### ISSUE TITLE
Passing a weights array failed

### ISSUE THREAD

**Issue by chanokin** [SpiNNakerManchester/sPyNNaker#216]
I tried using a weights array and threw this error:

`ValueError: could not broadcast input array from shape (20) into shape (100)`

I believe the bug is in:

https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/neural_projections/connectors/all_to_all_connector.py#L52

where 
`(pre_vertex_slice.hi_atom + 1 * n_post_neurons)`

should be
`(pre_vertex_slice.hi_atom + 1) * n_post_neurons`

**Comment by rowleya** [comment]
Oops - yes I can see this issue.  I did have problems with the "list of weights" format for a number of connectors; note that PyNN 0.8 will not support this format, but will instead support a matrix of weights.

The workaround for this is to use a FromListConnector.

**Comment by andrewgait** [comment]
Edit made in https://github.com/SpiNNakerManchester/sPyNNaker/pull/368

**Comment by alan-stokes** [comment]
closed!
