### ISSUE TITLE
I can´t run some examples

### ISSUE THREAD

**Issue by Brayan200291** [SpiNNakerManchester/sPyNNaker#221]
Hello, i´m new using SpiNNaker , and i have a problem, I checked some examples work, but some don´t.  I see the examples don´t work 
An example of error that I can see  it´s something like 
"ImportError: No module named neuron.neuron_models.neuron_model_leaky_integrate_and_fire"
Also, when i try to use the Izhikevich model, the interface shows me error.
I expect that someone can help me please. Thank you.

**Comment by rowleya** [comment]
Hi,

Can you send me the full output of the error?  Can you also tell me if you are using a local machine or the HBP collaboratory?
If you are using a local machine, can you send me a the link from which you got the installation instructions?  If you are using the collaboratory, do you have a job number?

Thanks,

Andrew :)

**Comment by Brayan200291** [comment]
I actually use a local machine, I´m studing a master, my project is using SpiNNaker but I really new with SpiNNaker, I´m  using Windows, the link of installation that i used is: 
http://spinnakermanchester.github.io/2015.005.Arbitrary/PyNNOnSpinnakerInstall.html#MacOSX
I attach you a image of the error that  I had

Date: Wed, 15 Jun 2016 08:56:42 -0700

**Comment by Brayan200291** [comment]
I actually use a local machine, I´m studing a master, my project is using SpiNNaker but I really new with SpiNNaker, I´m  using Windows, the link of installation that i used is: 

http://spinnakermanchester.github.io/2015.005.Arbitrary/PyNNOnSpinnakerInstall.html#MacOSX

I attach you all error that  I had:

1.2016-06-15 10:52:10 INFO: Read config files: C:\Users\bryan/.spynnaker.cfg, C:\Users\bryan\AppData\Roaming\Python\Python27\site-packages\spynnaker\spynnaker.cfg

Traceback (most recent call last):
  File "C:\Users\bryan\Desktop\gib_manchester_spinnaker\sPyNNaker-master\spynnaker\pyNN\models\neuron\builds\if_cond_exp.py", line 1, in <module>
    from spynnaker.pyNN.models.neuron.neuron_models\
ImportError: No module named neuron.neuron_models.neuron_model_leaky_integrate_and_fire


 Another error that i had using a Izhikevich model
2016-06-15 11:08:51 INFO: Read config files: C:\Users\bryan/.spynnaker.cfg, C:\Users\bryan\AppData\Roaming\Python\Python27\site-packages\spynnaker\spynnaker.cfg

Traceback (most recent call last):
  File "C:\Users\bryan\Desktop\izikevich_prueba_1.py", line 2, in <module>
    from spynnaker.pyNN.models.neuron.builds.izk_curr_exp import IzkCurrExp
ImportError: No module named neuron.builds.izk_curr_exp

Thanks,

Brayan

**Comment by rowleya** [comment]
Hi,

The latest version of the software installation instructions is here:
https://spinnakermanchester.github.io/2016.001.AnotherFineProductFromTheNonsenseFactory//spynnaker/PyNNOnSpinnakerInstall.html<https://spinnakermanchester.github.io/2016.001.AnotherFineProductFromTheNonsenseFactory/spynnaker/PyNNOnSpinnakerInstall.html>
Additionally, as you are using Windows, there are some different requirements from the Mac OS X instructions.

From the messages below, it also looks like you are using git checkouts of the software.  Whilst you are welcome to do this, it isn’t recommended unless you are actually modifying the software; in particular, the git master is not guaranteed to be fully tested (though it is usually reasonably tested).  This also means that you will have entries in your python site-packages folder that might conflict with the installation versions.  I believe that “pip uninstall” should be able to remove these, but just in case you might also need to edit the easy_install.pth file in your python site-packages folder and remove any of the SpiNNakerManchester entries (these include SpiNNMachine, SpiNNMan, SpiNNaker_DataSpecfication, SpiNNaker_PACMAN, SpiNNStorageHandlers, SpiNNFrontEndCommon, sPyNNaker, sPyNNakerExternalDevicesPlugin and sPyNNakerExtraModelsPlugin).  Once you have done this, you should be able to follow the instructions above to get the latest version.

Let us know if you have any issues with this.

Andrew :)

**Comment by alan-stokes** [comment]
due to length of time without a response, assuming this issue was completed.
