### ISSUE TITLE
getting synaptic matrix off the machine. redundant and broken code

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#229]
Howdi.

So trying to debug the fix_interface branch with comparisons with master. This is becoming a bit of a pain, but this issue is to flag up a block of code that is:
1. so broken im amazed it would ever work.
2. must be some left over from a old refactor.

projection_partitionable_edge has a 
get_synaptic_list_from_machine(self, graph_mapper, partitioned_graph,
                                       placements, transceiver, routing_infos):

This blows up really well, given its trying to get access to self.-synapse_list which doesn't exist. After a bit of looking, this isnt the logical way to get at the synaptic matrix, and this code block isnt being used anywhere. I propose to get rid of it completely, so that people dont try using it.

agree or not?

oh and a side note, im getting the reports folder of spynnaker back into action, given it seems to have disappeared and has a handy "generate_synaptic_matrix_reports()" function that should be kept for these kind of debug sessions (needless to say, this is currently broken as well, and is why i landed on this code block).

regards
Alan

**Comment by rowleya** [comment]
Yes, this is almost certainly left over and can be deleted.

**Comment by alan-stokes** [comment]
looks like we killed this during the most recent refactor (though i dont renember doing so). so we can kill this issue. YEY!
