### ISSUE TITLE
Move Data Generation to Machine vertices

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#237]
Data generation is really the job of the Machine Vertex.  Application vertices are better thought of as of use for partitioning, after which most of the functions can be done by the machine vertex.

**Comment by andrewgait** [comment]
This is a good idea but should be left for a future release.

**Comment by alan-stokes** [comment]
concur. a lot of work on the FEC models do exactly this. but the APV is annoyingly nasty in doing this unless we find a way to hand chunks of synaptic manager around.

**Comment by dkfellows** [comment]
Somewhere along the way we seem to have done this, at least sufficiently to close this.
