### ISSUE TITLE
setup.py doesn't get executed on recent pip versions

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#242]
It seems that setup.py doesn't actually get executed on some recent pip versions, meaning that pyNN-spiNNaker doesn't get installed correctly.  This should be replaced with a script that can be executed after sPyNNaker has been installed.

**Comment by rowleya** [comment]
This has been fixed in #245 - this now requires a script to be run instead of a pip install.

**Comment by Christian-B** [comment]
Fixed as best as possible considering the are currently two versions of PyNN supported. 

This make the use of pynn.spiNNaker dangerous as it is unclear what version is being obtained.
