### ISSUE TITLE
Memory allocation is not working correctly

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#244]
Sometimes a script with enough neurons and enough run time will over-allocate memory.  This means that everything seems fine until the Executing Data Specifications and Loading phase at which point the core reports that it can't allocate memory.

**Comment by alan-stokes** [comment]
i think you mean under allocate memory. a over allocation would be fine and we most likely always do that. It would be interesting to get a small example that does this. because its highly likely that the synaptic matrix estimates must be failing at this point.

**Comment by rowleya** [comment]
It over allocates the SDRAM as in it allocates too much.  It doesn't under-allocate though it might under-estimate.  Note that there is no check on this; DSG in FEC could do a check though and fail if too much SDRAM is allocated.

**Comment by alan-stokes** [comment]
would be much better to fail in dsg. dse is a nightmare to debug. it underallocs sdram region in dsg?/ sdram estimate for partitioning?, and writes too much to it during dsg.

**Comment by rowleya** [comment]
If it writes too much to a region, DSG might or might not fail.  This is because you don't actually know if it has written too much, as pointers can move and you can add for loops etc.  There could probably be a basic check for write and write_array which is aware of set_write_pointer - it can then keep track of the furthest known write pointer and if this is outside of the region, it can raise an error (see SpiNNakerManchester/DataSpecification#8).

An additional check can be done in FEC where after the DSG is called, the size of each region is added to the total size for the chip on which the data is to be loaded.  This can then raise an exception if that overflows (see SpiNNakerManchester/SpiNNFrontEndCommon#72).

This issue is still needed to fix the actual overflow though.

**Comment by alan-stokes** [comment]
think this is solved from the pull request about dsg memory errors. If this is the case, its likely this guy can be closed.

**Comment by alan-stokes** [comment]
closing assuming fixed. reopen if proved otherwise
