### ISSUE TITLE
izhikevich neuron raises error when Probabilty of connection set to zero

### ISSUE THREAD

**Issue by iambasab** [SpiNNakerManchester/sPyNNaker#249]
When i connect two neuronal populations using FixedProbabiltyConnector in PyNN, if I put the probabilty variable to 0, the simulation crashes.

**Comment by rowleya** [comment]
I believe that this is the issue that no key is being assigned to the pre-population, and then the check for this is failing (probably something I have done ;).

**Comment by andrewgait** [comment]
I believe this has been fixed, or at least I can't replicate it.  There is now a warning issued if the probability in the connector is set to zero from _generate_weights() in spynnaker/pyNN/models/connectors/abstract_connector.py.  Please let us know if you can still replicate this crash.

**Comment by alan-stokes** [comment]
closed unless basab relocates issue
