### ISSUE TITLE
Rename `MultapseConnector` to `FixedTotalNumberConnector`?

### ISSUE THREAD

**Issue by apdavison** [SpiNNakerManchester/sPyNNaker#250]
I see from the documentation that sPyNNaker has a `MultapseConnector`. It looks from the description that this does the same thing as the `FixedTotalNumberConnector` which is new in PyNN 0.8.1.

For the sake of future compatibility, what do you think about renaming `MultapseConnector` if it does indeed do the same thing?

**Comment by rowleya** [comment]
Sounds like a good plan - this came from the Microcircuit implementation where we needed this but didn't have it.  I would be surprised if too many people are using it, but it could easily be aliased anyway for backwards compatibility.

**Comment by alan-stokes** [comment]
Hi Andrew, 

If theMultapseConnector is indeed is doing what a FixedTotalNumberConnector is expected to do, I dont see the harm in changing it, as long as we keep the spynnaker.__init__.py to alias it back to a multapse copnnector in PyNN0.75. changing the class without this would be bad form, as we've had this exposed at the top level for some time now (which is interesting in on itself, given we try to not expose none pynn stuff via spynnaker)  and some people (as rowley has just pointed out) use it and so we'd be breaking backwards compatibility doing so. 

Its worth noting that the PyNN 0.8 functionality will result in a separate block of code and a common code module, so this could then slide there and be aliased independently as needed.

**Comment by alan-stokes** [comment]
https://github.com/SpiNNakerManchester/sPyNNaker8/pull/43
