### ISSUE TITLE
convert reports into machine readable format for provenance gathering

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#252]
The reports generated by the tools are currently designed to be human readable, but contain data that would be important for provenance, such how the cores were allocated, partitioning format, routing keys etc. As this allows a exact reproducible version.

We'd basically need to tie these report generation into the provenance framework and then forward the entire folder back up to the portal storage location.

**Comment by andrewgait** [comment]
I may be misunderstanding this request, but aren't all the relevant reports returned to the (HBP) user upon conclusion of a successful job?  (Perhaps this functionality was only added after this issue was opened...)

**Comment by rowleya** [comment]
This may already be implemented as you suspect.  We already provide provenance for the HBP portal for sure, and this is parsed out of the data I believe.  The whole report folder is also available.

**Comment by alan-stokes** [comment]
given how old this issue is. and the impression that said data is handed back now. closing
