### ISSUE TITLE
Plasticity doesn't work after resume simulation

### ISSUE THREAD

**Issue by fbarchi** [SpiNNakerManchester/sPyNNaker#258]
Hi,
I have a problem with plasticity behavior after resume a simulation.
Taking for example the stdp_curve.py script in project pynn_example, if I run it for 60s the values range  is [-0.6, 0.6], if I run for 30s I obtain [-0.3, 0.3] but resume simulation for others 30s the range remain [-0.3, 0.3] and the synaptic weights don't change.

I yet apply a patch for "sim_time resume bug" in the 
spinn_frontend_common/c_common/models/reverse_iptag_multicast_source/reverse_iptag_multicast_source.c on line 1023. (see Rowleya's commit 26e94e790...).

I use spynnaker 3.0.0

**Comment by alan-stokes** [comment]
likely a caching issue. having spoken to the dude. this is the logic which reproduces error.
plastic network
p.run(x)
y = pop.get_weights()
p.run(z)
a = pop.get_weight()

a == y 

but 1 run of p.run(x+z) is different than a

my bet is that we cache the weights at first get weights, not detect run happens so second time get weights goes we just hand over first set of weights

**Comment by alan-stokes** [comment]
https://github.com/SpiNNakerManchester/sPyNNaker7/pull/11
https://github.com/SpiNNakerManchester/sPyNNaker/pull/327

these pull requests will fix the caching issue. has a little test that eye balled work.
