### ISSUE TITLE
Division by wrong value in fixed-to-float conversions

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#260]
Some of the code for converting values from fixed-point S1615 to floating-point uses an incorrect value of 32767.0 instead of 32768.0 (namely gsyn and v).

**Comment by Christian-B** [comment]
Duplicate of https://github.com/SpiNNakerManchester/DataSpecification/issues/10

**Comment by rowleya** [comment]
This is a bit different - it should be checked though I think this is fixed

**Comment by alan-stokes** [comment]
fixed in master
