### ISSUE TITLE
Direct matrix optimisation is attempted even when the resultant matrix won't fit in DTCM

### ISSUE THREAD

**Issue by neworderofjamie** [SpiNNakerManchester/sPyNNaker#262]
I can't see any way of manually turning this optimisation off so the user has to just keep reducing the number of atoms per core until it stops RTEing

**Comment by alan-stokes** [comment]
Hi Jamie,
I'm going to assume direct matrix optimisation means the extra master pop
table for one to one connectors.

I don't think you can turn it off with the current master pop binary
search. What you could do, if you don't want it, is to look in the github
history on that file (id hazard to guess that the last changes were putting
in the direct dtcm table) and bring that out as a separate master pop impl.
you could then change the config param for master_pop_table_generator to
point at your old/new one and then the rest should jsut work.

on a side note, the dtcm calc needs to be updated to better take into
account these things, as then it would automatically work itself out. This
causing issues in your compartmentalisation models?

regards
Alan

**Comment by neworderofjamie** [comment]
Nope I was just helping Rob with the model he is building for the ERC
project. Am hesitant to start monkey-patching wildly so, until this is
fixed, reducing the atoms per core seems a reasonable workaround.

**Comment by alan-stokes** [comment]
if hes got so many one to one connectors, that they're filling in DTCM, it might be worth looking at the script and seeing if they can be amalgamated into less edges with denser connectivity. I remember at one point, they were using something like 32k ssa's each with 1 atom (to represent their retina), which caused them other issues, in i think, partitioning. So if its something like that, a high level rethink might sort out most of the issues.

the requirements for falling into the direct dtcm synaptic matrix is that there's 1 entry, and its a one to one connector. so if you can change the graph to not have that, it'll go away, as itll fall inot the sdram synaptic matrix.

**Comment by rowleya** [comment]
I did a fix for this at some point for Simon as well - I added an option to specify a maximum limit on the amount of DTCM used by this structure (so you could also specify 0 to turn it off entirely).  I will have to have a look around to see if I can find and extract this fix.

**Comment by neworderofjamie** [comment]
Thanks @rowleya

**Comment by tophensen** [comment]
I think I am encountering the same bug right now. @rowleya : Can you please elaborate on the workaround you mentioned?

**Comment by rowleya** [comment]
I have created a new branch for this called "one_to_one_matrix_limit".  This allows you to add the following to your .spynnaker.cfg:
```
[Simulation]
one_to_one_connection_dtcm_max_bytes = <max_bytes>
```

Where ```<max_bytes>``` is the maximum number of bytes to allow in the one-to-one matrix.  This has a default value of 8192.  You can turn off the one-to-one matrix by specifying a value of 0 here.

**Comment by alan-stokes** [comment]
fixed in master. closing
