### ISSUE TITLE
multi script runs on the same machine

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#265]
If you run a script multiple times, at the same time, on a local spinnaker machine, this causes a multitude of little issues.

1. If reset_on_start_up is set to true, it can result in one script hanging in loading phase as the machine is rebooted from the second script.
2. If restart is not on, the same cores can be allocated and therefore rewritten over during loading phase.
3. If second script has ran after loading of the first has occurred,  both scripts will use different parts of the machine, but due to sharing of the same app id, the first one to finish will kill the other script.

needless to say, this probably need to be fixed at some point, but as its a edge use case and the main usage is to use the spalloc system for multi script runs, where these issues do not occur, i wouldn't expect it to happen in the near future.

**Comment by andrewgait** [comment]
The question here is whether it's even really an edge use case.  I'm not convinced it's likely that anyone is seriously going to want to run separate scripts simultaneously on a single board; if they do want to run scripts simultaneously, then they should be directed to use the spalloc system.

**Comment by alan-stokes** [comment]
I THINK (given the age of this issue) that it was related to when we would go with 1 48 chip board to demo things like suduko and 10% column without spalloc resources..... I agree that nowadays i think its a pointless case, that if so, should be responded with "use spalloc"
