### ISSUE TITLE
No checking of pre and post-synaptic ids in connectors -- Intentional?

### ISSUE THREAD

**Issue by pabogdan** [SpiNNakerManchester/sPyNNaker#268]
The following is from https://github.com/pabogdan/neurogenesis/blob/master/notebooks/bug%20reporting/No%20Connector%20checks%20for%20ids.ipynb

Trying to connect up **p1** and **p2**, first of size 1, second of size 2 using a OneToOneConnector (size mismatch?), and then a FromListConnector (from neuron id 2 to neuron id 3-- makes no sense, neither population is that big). 

Is this an intentional optimization (don't waste time checking) or a bug?

```python
import spynnaker.pyNN as p
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
```

```python
p.setup(timestep=1.0)
```

```python
# Parameters
cell_params_lif = {'cm': 0.25,
                   'i_offset': 0.0,
                   'tau_m': 20.0,
                   'tau_refrac': 5.0,
                   'tau_syn_E': 5.0,
                   'tau_syn_I': 5.0,
                   'v_reset': -70.0,
                   'v_rest': -65.0,
                   'v_thresh': -50.0
                   }

weight_to_spike = 2.
delay = 1
```

```python
p1 = p.Population(1, p.IF_curr_exp, cell_params_lif)
p2 = p.Population(2, p.IF_curr_exp, cell_params_lif)
```

```python
p.Projection(p1, p2, p.OneToOneConnector(weight_to_spike, delay))
p.Projection(p2, p1, p.FromListConnector([(2,3, weight_to_spike, delay)]))
```

```python
spikeArray = {'spike_times': [0, 10]}

# Input populations
input_p1 = p.Population(1, p.SpikeSourceArray, spikeArray,label='inputSpikes_p1')
p.Projection(input_p1, p1, p.OneToOneConnector(weight_to_spike, delay),  label='input_p1->1')
```

```python
p1.record_v()
p1.record_gsyn()
p1.record()
```

```python
p.run(50)
```

```python
v_p1 = p1.get_v(compatible_output=True)
gsyn_p1 = p1.get_gsyn(compatible_output=True)
spikes_p1 = p1.getSpikes(compatible_output=True)
```

    Getting membrane voltage for Population 0
    |0                           50%                         100%|
     ============================================================
    Getting conductance for Population 0
    |0                           50%                         100%|
     ============================================================
    Getting spikes for Population 0
    |0                           50%                         100%|
     ============================================================

```python
p.end()
```

    Getting provenance data from machine graph
    |0                           50%                         100%|
     ============================================================
    Getting provenance data
    |0                           50%                         100%|
     ============================================================
    Getting Router Provenance
    |0                           50%                         100%|
     ============================================================
    Extracting IOBUF
    |0                           50%                         100%|
     ============================================================

```python
plt.plot(v_p1[:, 2])
for input_t in spikeArray['spike_times']:
    plt.axvline(input_t, ls=':', c='g', lw=2, alpha=.5)
for t in spikes_p1[:,1]:
    plt.axvline(t, ls='-', c='r', lw=2, alpha=.5)
plt.title("")
plt.ylabel("Potential (mV)")
plt.xlabel("Time (ms)")
```

![output_10_1](https://cloud.githubusercontent.com/assets/1470639/22208231/1338afc0-e17a-11e6-83a5-b45a1ba01ba9.png)

**Comment by rowleya** [comment]
No such check is required by the interface, and indeed the "official" implementations do not offer such a check.  The data generated is valid and will just miss out the invalid connections.

We could offer a warning in this case, or else a Provenance data item that reports the number of "dropped" connections (or both), which would then at least let you know what you had done.
