### ISSUE TITLE
using app dirs for locations of cfg files

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#269]
during the review / rebuild / integration of jamie pynn 0.8 it came to light that hes using appdirs to support his configuration files in a more platform independent way to how we currently do so. 

This should likely get merged into our spynnaker tools via some sort of central location, aka a configuration module (favoured by donal) which could be used by all 3 front ends to date. 

place holder for when this functionality is done

**Comment by Christian-B** [comment]
Done
