### ISSUE TITLE
Spikes seem to get lost in small network

### ISSUE THREAD

**Issue by SimonDavidson** [SpiNNakerManchester/sPyNNaker#27]
Attached PyNN script contains a variable number of Poisson spike sources which project to two populations via probabilistic projections of constant weight and constant delay.

The number of poisson sourcse is passed in as an argument, along with the number of target neurons in each pop and the weight to use. (I used 14500, 1000 and 0.01 as parameters to demonstrate the problem).

The target neurons have their thresholds set really really high (+0.5V!) so they never spike. I want to observe the fluctuating potential due to the poisson source stimulation.

I noticed that when I change th number of Poisson sources per core from 50 in steps of 50 up to 250, the mean potential of the target neurons changes, which they shouldn't do as the network is the same, it's just the way it was partitioned.

I conclude that spikes are being lost dependent on the partitioning.

**Comment by alan-stokes** [comment]
So the test script this is being assocated with is located [inspynnaker.intergration_tests/simon_noise_possion/noise_test_case](https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/integration_tests/simon_Noise_possion/noise_test_case.py)

it seems that runs on the machine onto 21 chips, where a 4 by 4 grid (280 cores) is used to inject packets into 3 chips that resided on the left side of the 4 by 4 grid in a straight line. as shown below. 

![layout from placement](https://cloud.githubusercontent.com/assets/7520968/6002306/1c65b6d8-aaea-11e4-9aaa-28e19e802bfe.jpg)

This results in large mc drops in chips 3:2, 3:1, and 4:2 (as shown by the proavance data generated during the run shown below)

<router_at_chip_3_1>
        <Loc__MC>5139</Loc__MC>
        <Ext__MC>39930</Ext__MC>
        <Dump_MC>13073</Dump_MC>
        <Loc__PP>3159</Loc__PP>
        <Ext__PP>5932983</Ext__PP>
        <Dump_PP>0</Dump_PP>
        <Loc__NN>999454</Loc__NN>
        <Ext__NN>876551</Ext__NN>
        <Dump_NN>0</Dump_NN>
        <Loc__FR>0</Loc__FR>
        <Ext__FR>0</Ext__FR>
        <Dump_FR>0</Dump_FR>
      </router_at_chip_3_1>

<router_at_chip_3_2>
        <Loc__MC>4458</Loc__MC>
        <Ext__MC>35140</Ext__MC>
        <Dump_MC>20732</Dump_MC>
        <Loc__PP>3264</Loc__PP>
        <Ext__PP>98658</Ext__PP>
        <Dump_PP>0</Dump_PP>
        <Loc__NN>999429</Loc__NN>
        <Ext__NN>840034</Ext__NN>
        <Dump_NN>0</Dump_NN>
        <Loc__FR>0</Loc__FR>
        <Ext__FR>0</Ext__FR>
        <Dump_FR>0</Dump_FR>
      </router_at_chip_3_2>

<router_at_chip_4_2>
        <Loc__MC>0</Loc__MC>
        <Ext__MC>84275</Ext__MC>
        <Dump_MC>1291</Dump_MC>
        <Loc__PP>694139</Loc__PP>
        <Ext__PP>4853929</Ext__PP>
        <Dump_PP>0</Dump_PP>
        <Loc__NN>999438</Loc__NN>
        <Ext__NN>824576</Ext__NN>
        <Dump_NN>0</Dump_NN>
        <Loc__FR>0</Loc__FR>
        <Ext__FR>0</Ext__FR>
        <Dump_FR>0</Dump_FR>

The current solution would be to posititon manually using placement constriants the l2E and l1I populations to chips in the middle of the 4 by 4 grid. This is only a stop gap though.

The best solution is to impliment the connective based placement which would mitigate this issue by hopfully making less router dead locks, or optimise the router to take account of these dead locks. 

This is likely to only be impliemtnable after september though.

**Comment by alan-stokes** [comment]
update on this. the spikes were being lost in the fabric due to congestionc ausing deadlock in the routers. 

Current fix (residing in the re-injection brnach) adds a new model onto each chip which reinjects dropped packets. But the model is injected right down at spinnman level, and makes 2 cores montiro cores. Which we think is a rather nasty bodge. To top it off, this bodge cant be turned off yet. 

So new plans on how this is to be done are in progress.

**Comment by alan-stokes** [comment]
so update to this, the re-injector module has now been pushed into master, and therefore this issue is now closed.
