### ISSUE TITLE
Low rate Poisson source causes an error

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#271]
Referring to the code here:
https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/spike_source/spike_source_poisson.py#L317

When the rate is very low, the expected spikes per timestep is very low.  This can cause one of two problems:
1) When spikes_per_timestep is 0, a division by 0 is performed.
2) When spikes_per_timestep is close to 0, time_between_spikes is very large and doesn't fit in a UINT32.

Since this code is only there to stop multiple spikes being sent all at once, the simple solution is to make time_between_spikes = 0 when spikes_per_timestep is <= 1, only performing the division when spikes_per_timestep > 1.

**Comment by andrewgait** [comment]
Added suggested code in https://github.com/SpiNNakerManchester/sPyNNaker/pull/367

Is there an actual low Poisson rate example out there somewhere that this can be tested against further?

**Comment by alan-stokes** [comment]
closed
