### ISSUE TITLE
pyNN.spiNNaker not installing

### ISSUE THREAD

**Issue by p-klein** [SpiNNakerManchester/sPyNNaker#274]
Hi,
I am having troubles installing the software for the SpiNNaker boards. I followed the instructions in the PyNN on SpiNNaker Installation Guide and the dependencies.
`pip install "sPyNNaker == 3.0.0"` and so on.

When I want to configure the board python complains about not finding the module spiNNaker.
`python -c "import pyNN.spiNNaker"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named spiNNaker
`
Any ideas why this is happening? 

Edit: I am using Ubuntu 16.04 

Best,
Philipp

**Comment by rowleya** [comment]
Hi,

This is a known issue and is fixed in a branch, but requires a change to the instructions.  You can try this out by downloading the following file:
https://raw.githubusercontent.com/SpiNNakerManchester/sPyNNaker/fix_pyNN_spiNNaker_install/spynnaker/setup_pyNN.py

If you execute this, it should create the appropriate links.  Note that you might have to call sudo e.g.:
    sudo python setup_pyNN.py

or else be in an administrative console on Windows.

Let me know if you still have issues.

Andrew :)

**Comment by Christian-B** [comment]
As for the considerable future there will be two supported versions of PyNN with SpiNNaker the command import pyNN.spiNNaker could lead to confusion as to which version os imported so probably will not be supported for a while.

Once PyNN7 on SpiNNaker has been officially deprecated the import pyNN.spiNNaker could be reinstated.

**Comment by alan-stokes** [comment]
just to add. 
pynn 0.75
import spynnaker7.pynn as sim

pynn 0.8
import spynnaker8 as sim

these are the currently supported commands.

**Comment by rowleya** [comment]
OK, so technically pyNN always supports pyNN.<simulator>, so we probably need to support this.  There are now setup scripts in master which set up the links correctly:
pynn 0.7:
python -m spynnaker7.pyNN.setup-pynn

pynn 0.8:
python -m spynnaker8.setup-pynn

Each of the scripts checks for the appropriate pyNN version.  Issues arise if people try to have both PyNN 0.7 and 0.8 in a single environment, which is basically impossible; you need a virtualenv or something else that separates out the namespace, as pyNN itself can only be installed once.  If people want to switch between the versions, that is quite easy:

pip install pyNN==0.7.6
python -m spynnaker7.pyNN.setup-pynn

pip install pyNN==0.8.3
python -m spynnaker8.setup-pynn
