### ISSUE TITLE
Use version number epochs

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#277]
As the versioning scheme has changed, version epochs should be used:
https://www.python.org/dev/peps/pep-0440/#version-epochs

**Comment by Christian-B** [comment]
All versions are now epochs.    All repositories also changed so the version is harded coded in the same place the ..../_version.py file.

As chaning version numbers is a nurmal pre release set closing this issues as the specific epochs work done.
