### ISSUE TITLE
Custom config file fails to retrieve iobuf

### ISSUE THREAD

**Issue by pabogdan** [SpiNNakerManchester/sPyNNaker#284]
The following:
```
[Reports]
extract_iobuf = True
extract_iobuf_during_run = False
clear_iobuf_during_run = False
```
fails to retrieve iobuf completely

**Comment by Christian-B** [comment]
Same as: https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/162

if not please reopen with more details and an example script.

**Comment by alan-stokes** [comment]
iobuf is not the same as live buffers. 
this is that instead of extracting it per auto pause adn resume step, it would pull it at end of sim. rather risky to set it up that way, but allwoed via the config params. not pulling at all in this case is thus a bug not covered

**Comment by alan-stokes** [comment]
is re-producable in master. am looking into it now.

**Comment by alan-stokes** [comment]
fixed via
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/172
https://github.com/SpiNNakerManchester/sPyNNaker8/pull/41

**Comment by Christian-B** [comment]
fixed
