### ISSUE TITLE
comprehensive string representation

### ISSUE THREAD

**Issue by chanokin** [SpiNNakerManchester/sPyNNaker#290]
It would be really useful to have good string representations of the different classes (via __str__ or __unicode__). Right now most objects print back type/addresses, i.e. the default behaviour.

**Comment by andrewgait** [comment]
I'm not completely sure what this issue is getting at, to be honest.  Most if not all of the objects that are directly accessible from a user script have sensible string representations already.  Are we saying that this needs to be the case for every class in every package we have?

**Comment by chanokin** [comment]
I don't remember exactly what this was about. I think I meant that, if we wanted to print an object, we ended up with <Population object at address xyz> instead of say "Population [label] [neuron type] [other useful info]". I think at the moment I was working with Projections and in a large project it was really hard to figure out which of them had failed.

**Comment by andrewgait** [comment]
As far as I can see this has been implemented correctly for Populations, and it was sorted out for Projections in https://github.com/SpiNNakerManchester/sPyNNaker8/pull/231.  I also think that anything else easily accessible from a user script has a sensible string representation.  I’m going to close this issue as it stands but would be happy to look at individual objects as necessary in the future.
