### ISSUE TITLE
set_neurons_per_core is static across p.setup calls

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#307]
This is a little non-intuitive.  It would be better to allow:
1. Only allow p.set_neurons_per_core after p.setup and make it context based
2. Allow a per-population setting of neurons per core; if this has not been done, the context-based setting is used.

**Comment by alan-stokes** [comment]
1. will be done via the fakeStates object. so yey. 
2. could change pynn_pop_common set_model_based_max_atoms_per_core to put a partitioner_max_size_constraint instead of changing the vertex internal value.

**Comment by Christian-B** [comment]
fixed. It now longer is static
