### ISSUE TITLE
Could we add a placement constraint that works for an area rather than a single chip?

### ISSUE THREAD

**Issue by SimonDavidson** [SpiNNakerManchester/sPyNNaker#31]
It would be useful for stuff that is too big to be placed on a single chip to be able to give a rough guide for placement rather than a hard constraint that throws an exeption if it can't be met exactly..

e.g. "place this population somewhere around chip (6,5)."

So even if it spills over, the whole population ends up in the vicinity of chip (6.5) and the tools don't just get anal and throw an error becuase it can't put everything in chip (6,5).

**Comment by alan-stokes** [comment]
Done, its currently in the master brnach, but there hasnt been a offical release with this functionality so far.
