### ISSUE TITLE
Routing Table lost after reset

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#347]
Using a synfire chain including run(500) reset run(500)  the second run does not generate any spikes

For example:
https://github.com/SpiNNakerManchester/sPyNNaker7/blob/master/p7_integration_tests/test_multi_call_examples/test_synfire_1_run_reset_1_run__smaller_runtime_no_extraction_if_curr_exp.py

same in pynn8:
https://github.com/SpiNNakerManchester/sPyNNaker8/blob/more_integration_tests/p8_integration_tests/test_multi_call_examples/test_synfire_1_run_reset_1_run__smaller_runtime_no_extraction_if_curr_exp.py

**Comment by Christian-B** [comment]
On farther investigation V is recording but flat.

So it appears the p.SpikeSourceArray is not firing on the second run

**Comment by Christian-B** [comment]
With Alan's (and others) help we track this down to reset deleting the routing tables and not reloading them.

Alan's chip power monitor branch fixes this so we hope to speed up fixing that branch.

**Comment by alan-stokes** [comment]
note that when this is fixed. remove skiped intergration tests that referr to this issue. 
search for this to find it
https://github.com/SpiNNakerManchester/sPyNNaker/

**Comment by alan-stokes** [comment]
fix in hand, with chip_power-monitor to cover all errors
https://github.com/SpiNNakerManchester/sPyNNaker8/pull/35
https://github.com/SpiNNakerManchester/sPyNNaker/pull/357

**Comment by alan-stokes** [comment]
fixed in master now
