### ISSUE TITLE
Too long random back-off in SpikeSourcePoisson

### ISSUE THREAD

**Issue by chanokin** [SpiNNakerManchester/sPyNNaker#361]
In SpikeSourcePoisson the back off could end up beeing too long if the population is big:

https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/spike_source/spike_source_poisson.py#L401

could be fixed with:

`
spec.write_value(random.randint(0, min(SpikeSourcePoisson._n_poisson_vertices,  MICROSECONDS_PER_SECOND//machine_time_step)))
`

**Comment by andrewgait** [comment]
Fixed in https://github.com/SpiNNakerManchester/sPyNNaker/pull/367

**Comment by alan-stokes** [comment]
closed!
