### ISSUE TITLE
"Exception: Only rows of up to 255 entries are allowed" - What does it mean to a general PyNN user?

### ISSUE THREAD

**Issue by mmikaitis** [SpiNNakerManchester/sPyNNaker#370]
Exception occurs in the following small test cases:

* Population 1 with 1 neuron; Population 2 with 127 neurons; All-to-All connection; STDP.
* Population 1 with 100 neurons; Population 2 with 127 neurons; All-to-All connection; STDP.
* Population 1 with 1 neuron; Population 2 with 256 neurons; All-to-All connection; **No STDP**.

Exception **does not** occur in the following test cases:

* Population 1 with 1 neuron; Population 2 with 126 neurons; All-to-All connection; STDP.
* Population 1 with 300 neurons; Population 2 with 126 neurons; All-to-All connection; STDP.
* Population 1 with 1 neuron; Population 2 with 255 neurons; All-to-All connection; **No STDP**.
* Population 1 with 127 neurons; Population 2 with 127 neurons; One-To-One connection; STDP.
* Population 1 with 127 neurons; Population 2 with 400 neurons; One-To-One connection; STDP.

So it looks like this error means that Population 2 cannot be larger than 126 neurons if there is at least one neuron in Population 1 that will connect to all of the neurons in Population 2 through plastic synapses? I.e. **No neuron can connect to more than 126 neurons when STDP is enabled**?

How does 126 or 127 relate to 255? 126x2=252 and 127x2=254. What is meant by "entries" and "rows" in terms of PyNN vocabulary. How does STDP affect these numbers.

Error needs clarification on what needs to be fixed in user's PyNN script.

Thanks, - Mantas :)

**Comment by mmikaitis** [comment]
It would be worth also considering 3 population test cases. I.e. Population 1 with 1 neuron, Population 2 with 126 neurons, Population 3 with 126 neurons. Two All-To-All projections 1 -> 2 and 1 -> 3. Will this cause the exception?

**Comment by rowleya** [comment]
I believe that this is fixed by #374.  

I didn't get a match for the numbers you give in terms of limits, but for STDP it will depend on the rules as to the maximum number of synapses per row.  When not using STDP, I couldn't replicate this.  If you have a script that does so, please attach it!

**Comment by mmikaitis** [comment]
Ahh I see, I saw these errors with neuromodulation rule which probably requires more memory per row. So the only time this exception appears using simple STDP rule, pair based, is when post-synaptic population is larger than 255 neurons (Simple test attached).

Without STDP, there is indeed no error, my mistake.

I can see that #374 would make this error more clear.

```
import spynnaker7.pyNN as sim

cell_params = {'cm': 0.25,
               'i_offset': 0.2,
               'tau_m': 20.0,
               'tau_refrac': 2.0,
               'tau_syn_E': 5.0,
               'tau_syn_I': 5.0,
               'v_reset': -70.0,
               'v_rest': -65.0,
               'v_thresh': -50.0
              }

sim.setup(timestep=1.0)

pop1 = sim.Population(1, sim.SpikeSourcePoisson,
       {'rate':1}, label="pre")
pop2 = sim.Population(256, sim.IF_curr_exp, cell_params, label='post')

synapse_dynamics = sim.SynapseDynamics(slow=sim.STDPMechanism(
    timing_dependence=sim.SpikePairRule(
        tau_plus=2, tau_minus=1),
    weight_dependence=sim.AdditiveWeightDependence(A_plus=0.0, A_minus=0.0,)))

sim.Projection(pop1, pop2,
        sim.AllToAllConnector(weights=0.1),
        synapse_dynamics=synapse_dynamics,
        target='excitatory', label='projection')

sim.run(1)
sim.end()

**Comment by rowleya** [comment]
Fixed in merge
