### ISSUE TITLE
print_X should write results to disk during execution

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#376]
The print_X functions (e.g. printSpikes, print_v etc.) currently force the data to pass through the PC RAM, so for large networks, the user can run out of RAM even though they don't want to process the data.  The data should instead be written straight to disk.

**Comment by chanokin** [comment]
If the object used to store the data is a Numpy array, we could use a [memmap](https://docs.scipy.org/doc/numpy/reference/generated/numpy.memmap.html) which should somewhat keep the change hidden to the user.

**Comment by rowleya** [comment]
Unfortunately, this goes down to the buffer manager which doesn't use numpy.  Fortunately, this does store the data as a file.  The trick will probably be to ensure that the file doesn't have to be read in whole before the data is stored...  I will have a look.

As a side note, we did once have numpy memmaps in the background, but the issue is that they actually make use of the spare memory address space.  This is fine on 64-bit systems but was a problem when we encountered 32-bit systems (you would think we wouldn't but we do).

**Comment by rowleya** [comment]
A partial solution to this has been done in SpiNNakerManchester/SpiNNFrontEndCommon#195.  This change allows the storing of the data in files during the execution.  The data is still loaded in to RAM post-execution, but at least this should just be the data per Population, rather than all of the recorded data.

**Comment by alan-stokes** [comment]
also note that in pynn 0.8, when you get the data, theres a clear param which will wipe it from RAM as well. I think. seriously forgotten what all the semantics of PyNN 0.8 are now. lol

**Comment by rowleya** [comment]
This is now updated.  Anything more would require much more work.  Memory savings can instead be made elsewhere so closing this now.
