### ISSUE TITLE
Crash on app_stop with pynnBrunnelBrianNestSpinnaker.py

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#38]
app_stop is disabled just now, because it causes an issue with pynnBrunnelBrianNestSpinnaker.py when it is turned on.

**Comment by alan-stokes** [comment]
running the pynnBrunnelBrianNestSpinnaker.py doesnt seem to cause any issues that I can determine (even numerious runs of it seem to work fine). And pynn.end() is called. Thus deducing that the issue has been rectified and that this issue is now completed.

**Comment by neworderofjamie** [comment]
Wasn't this because we weren't allocating SDRAM via the monitor processor
so we were potentially corrupting it's heap and causing app stop to crash?

**Comment by rowleya** [comment]
In fact this only happened when we called app_stop, which had been 
temporarily disabled, hence qhy it wasn't showing up.  Please try this 
again with app_stop enabled; you might also have to run it a couple of 
times (can't remember).

Thanks for the possible diagnosis though Jamie, this could indeed be the 
issue.

Andrew :)
