### ISSUE TITLE
Importing data from SpiNNaker board to hard drive

### ISSUE THREAD

**Issue by iambasab** [SpiNNakerManchester/sPyNNaker#381]
Would it be possible to import data (voltages) from the SpiNNaker machine directly on to the HDD? This will alleviate dependency on available RAM space on host computers.

**Comment by Christian-B** [comment]
Have you considered outputting the data to file.

PyNN 0.75
p1.print_v(file=file_path, compatible_output=True)
p1.print_gsyn(file=file_path, compatible_output=True)
p1.printSpikes(file=file_path, compatible_output=True)

PyNN 0.8
p1.write_data(io=file_path, variables='v', clear=False, annotations=None)
p1.write_data(io=file_path, variables=['v', 'gsyn_exc', 'spikes', 'gsyn_inh'])
p1.write_data(io=file_path, variables='all')

**Comment by Christian-B** [comment]
For PyNN 0.8 the write formats are: .h5, .pkl, .mat
All which are neo data

If there is a need we can add a csv or similar format that can be processed line by line

**Comment by apdavison** [comment]
If it helps, you can always define a new Neo IO class (e.g. `SpiNNakerIO`) to let people read in a custom, SpiNNaker-optimized format.

**Comment by rowleya** [comment]
I think the issue here is that the data is held in memory before writing to disk.  This is covered in #376.  There is a partial fix, which avoids the majority of the memory usage I believe.

**Comment by rowleya** [comment]
This is helping with the memory usage.  Anything more would require much more work.  Other memory savings can be made elsewhere, so closing this issue now.
