### ISSUE TITLE
Add virtual chip allocation

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#39]
Virtual chips are currently allocated by the user.  With the key allocator, it should be possible to allocate a virtual chip without needing to do this.

**Comment by alan-stokes** [comment]
done, awaiting merging via pull request. has had effects on the interface for external devices. no longer needs virutal chip xnad virutal chip y. but for some models, there are now a virutal key requirement. pull requests 13, 14, 23, 128 (who makes up these numbers?!)

**Comment by alan-stokes** [comment]
merged
