### ISSUE TITLE
Duplication of STDP builds

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#395]
There appear to be stdp and stdp_mad versions of a lot of builds.  It doesn't seem possible to use the non-mad stdp versions, so these should be removed.

**Comment by andrewgait** [comment]
I'm a bit confused what you mean here; it doesn't seem as though

https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_impl.c

and

https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_impl.c

do exactly the same thing at the moment.  If they are doing different things, then are we not building something different when MAD is specified?  

I'll have a look at this in more detail in the near future...

**Comment by andrewgait** [comment]
OK, so in the Python code, get_vertex_executable_suffix() in

https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py

returns a binary name with "_stdp_mad" in it, along with the timing/weight rules; there are no examples in the (Python) toolchain of a binary name being returned with just "_stdp" in it, so I agree - any C builds of non-mad STDP code are unnecessary at the moment as they cannot currently be used from a PyNN script, and they should probably be removed from the toolchain.

**Comment by alan-stokes** [comment]
merged
