### ISSUE TITLE
Database isn't created when using only a SpikeInjector

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#401]
For some reason using a SpikeInjector isn't enough to force the creation of the database.  This can be fixed currently by setting up the spynnaker.cfg file appropriately.

**Comment by alan-stokes** [comment]
so the reason for this is out auto_detect_database function call. 

that only looks through the machine graph vertices and sees if they are of instance AbstractSupportsDatabaseInjection and only if it is and its property "is_in_injection_mode" is set to true is it ever to return true. 

the cfg file works, as that's a override on this function. 

this is basically why i think the database isnt built by external devices such as retina. 

on why this spike injector itself is not enough for the database to be set. the Spikeinjector is a reverse iptag multicast source machine vertex which does inherit from AbstractSupportsDatabaseInjection. But its logic for is_in_injection_mode is that it returns True only if the receive port is not set to None. This is deduced right at __init__ time. not during the call. 

maybe moving the logic to the call time and injecting reverseiptags at that point to sort out the port num would recitfy this issue?

**Comment by alan-stokes** [comment]
we could also expend the logic to search for LPGs and if they exist make database.

**Comment by rowleya** [comment]
The ReverseIPTagMulticastSource is an instance of AbstractSupportsDatabaseInjection.  The issue is then that it returns false to the method, because the port is set to None.  Of course the port is auto-assigned, so it should be set to None!  This needs a more careful examination, to decide how it is done - we only want the database when it is used as a SpikeInjector...

On a side note, it does work with LPGs as these always return True from that method.

**Comment by rowleya** [comment]
Fixed by SpiNNakerManchester/SpiNNFrontEndCommon#207

**Comment by rowleya** [comment]
Turned out to be quite easy ;)
