### ISSUE TITLE
number of neurons in a population as float causes errors

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#405]
If someone pass in n_neurons to population as a float even when the value is a whole number represented as a float type this can cause problems.

My suggestion is that is n_neurons can be taken as an int it should be converted to an int.
if not a clear error should be throw here.

**Comment by iambasab** [comment]
Thanks Christian, further to your issue log, here is the exact line that was causing the problem:
scale_fact = 10.0
................
self.NumCellsTCR = 8.0 * scale_fact

didn't work

self.NumCellsTCR = int(8.0 * scale_fact)
worked

The exception was being raised on this call:

self.TCR_pop = p.Population(self.NumCellsTCR, p.Izhikevich(**self.TCR_cell_params), label='TCR_pop')

**Comment by rowleya** [comment]
n_neurons is definitely an int - I guess that we could either throw an exception or give a warning if int(n_neurons) != n_neurons, or else just use int(n_neurons)

**Comment by Christian-B** [comment]
my plan is to check type for int.   If that fails do cast to nearest int and then check that is nearly the same as original, otherwise throw an exception

**Comment by alan-stokes** [comment]
other idea, just cast, and then report as provenance error.

**Comment by Christian-B** [comment]
fixed in:
https://github.com/SpiNNakerManchester/sPyNNaker/pull/418
https://github.com/SpiNNakerManchester/sPyNNaker7/pull/38
https://github.com/SpiNNakerManchester/sPyNNaker8/pull/76

**Comment by dkfellows** [comment]
Fixes committed.
