### ISSUE TITLE
Eligibility traces should be decayed always

### ISSUE THREAD

**Issue by chanokin** [SpiNNakerManchester/sPyNNaker#410]
Hey @mmikaitis , I think we need to change the following:

[Line 133](https://github.com/SpiNNakerManchester/sPyNNaker/blob/88cdf61cd215ccb0e8080dcad1ca1b565a94799f/neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_neuromodulated_impl.c#L133) should go outside the __if__ block, because we want both traces to be evaluated at the same point on the next weight update.

As the pre spike can never be dopamine, the __if__ block [line 183](https://github.com/SpiNNakerManchester/sPyNNaker/blob/88cdf61cd215ccb0e8080dcad1ca1b565a94799f/neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_neuromodulated_impl.c#L183) should not be conditioned to dopaminergic type.

Could you review and comment?

**Comment by mmikaitis** [comment]
Hi Gary,

1) Good spot - fixed!

2) That is not true, that check is checking whether last POST spike is dopamine or not to decide if it should apply depression or not to eligibility trace.

**Comment by chanokin** [comment]
@rjames91 spotted the weird behaviour, so cheers to himt too.

2. Wouldn't we need to advance the eligibility trace in the PRE as well? Maybe measuring when the last standard POST happened?

**Comment by mmikaitis** [comment]
I moved out decaying of eligibility trace out of if (!dopamine) block in both POST and PRE update functions now.

**Comment by chanokin** [comment]
ooooh, that should be the appropriate way of doing it 👍 
thanks!

**Comment by mmikaitis** [comment]
Can you or Robert test this? I do not have access to a board right now!

**Comment by chanokin** [comment]
yup, will do!

**Comment by chanokin** [comment]
Seems to work correctly!

**Comment by mmikaitis** [comment]
Looks fixed.
