### ISSUE TITLE
keep eligibility in STDP format

### ISSUE THREAD

**Issue by chanokin** [SpiNNakerManchester/sPyNNaker#412]
We could probably keep eligibility trace in STDP fixed-point format (lines [141](https://github.com/SpiNNakerManchester/sPyNNaker/blob/b09c3bed2dc644f3975384cd260f88bfb1589d91/neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_neuromodulated_impl.c#L141), [194](https://github.com/SpiNNakerManchester/sPyNNaker/blob/b09c3bed2dc644f3975384cd260f88bfb1589d91/neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_neuromodulated_impl.c#L194)) and only convert when we apply the weight line [268](https://github.com/SpiNNakerManchester/sPyNNaker/blob/b09c3bed2dc644f3975384cd260f88bfb1589d91/neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_neuromodulated_impl.c#L268).

**Comment by mmikaitis** [comment]
Hi Gary. Eligibility trace is always in STDP fixed point format as pre and post traces.

**Comment by mmikaitis** [comment]
When you multiply two fixed-point numbers with format, for example, s15.16, you get a result in the format of .32. That's why I shift it back down to the STDP format.

**Comment by mmikaitis** [comment]
I think we can close this?

**Comment by chanokin** [comment]
yup!
