### ISSUE TITLE
changes for signed eligibility trace

### ISSUE THREAD

**Issue by chanokin** [SpiNNakerManchester/sPyNNaker#413]
List of changes for signed eligibility trace:

__In timing_pair_impl.h__

[Line 7](https://github.com/SpiNNakerManchester/sPyNNaker/blob/b09c3bed2dc644f3975384cd260f88bfb1589d91/neural_modelling/src/neuron/plasticity/stdp/timing_dependence/timing_pair_impl.h#L7) I changed to

` typedef uint32_t post_trace_t; `

[Line 102](https://github.com/SpiNNakerManchester/sPyNNaker/blob/b09c3bed2dc644f3975384cd260f88bfb1589d91/neural_modelling/src/neuron/plasticity/stdp/timing_dependence/timing_pair_impl.h#L102) I changed to 

` return (post_trace_t)( (post_trace << 16) | ((uint16_t)(dopamine_trace)) ); `

__In synapse_structure_weight_impl.h__

[Line 8](https://github.com/SpiNNakerManchester/sPyNNaker/blob/b09c3bed2dc644f3975384cd260f88bfb1589d91/neural_modelling/src/neuron/plasticity/stdp/synapse_structure/synapse_structure_weight_impl.h#L8) I changed to 

` typedef uint32_t plastic_synapse_t; `

[Line 30](https://github.com/SpiNNakerManchester/sPyNNaker/blob/b09c3bed2dc644f3975384cd260f88bfb1589d91/neural_modelling/src/neuron/plasticity/stdp/synapse_structure/synapse_structure_weight_impl.h#L30) I changed to
` return (plastic_synapse_t)( (weight << 16) | ((uint16_t)(trace)) ); `

__In synapse_dynamics_stdp_mad_neuromodulated_impl.c__

[Line 170](https://github.com/SpiNNakerManchester/sPyNNaker/blob/b09c3bed2dc644f3975384cd260f88bfb1589d91/neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_neuromodulated_impl.c#L170) I changed to

` int32_t weight_change = __smulbb( `

[Line 118](https://github.com/SpiNNakerManchester/sPyNNaker/blob/b09c3bed2dc644f3975384cd260f88bfb1589d91/neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_neuromodulated_impl.c#L118) I changed to 

` int32_t weight_change = __smulbb( `

**Comment by mmikaitis** [comment]
Hi Gary,

Did you manage to test this? Feel free to push a fix to a branch!

I pretty sure that this should not change the functionality but it definitely makes things easier to read.

- Mantas

**Comment by alan-stokes** [comment]
guys, this looks more like a pull request than a issue, can you move it over to the correct location. thanks
