### ISSUE TITLE
Fix the FixedNumberPreConnector and FixedNumberPostConnector

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#435]
These connectors currently use a fixed set of pre- or post-neurons.  The correct behaviour is, for each pre/post neuron, select a different random fixed number of post/pre neurons.  It should be possible to do the FixedNumberPreConnector quite easily for each core separately, but for the FixedNumberPostConnector, it might be necessary to generate using the same seed for every core, and generating the whole connectivity, ignoring those post-neurons that are not on this core.

**Comment by andrewgait** [comment]
I'm a bit confused, the PyNN API says

> `class FixedNumberPreConnector(n, allow_self_connections=True, with_replacement=False, rng=None, safe=True, callback=None)[source]` 
> Each post-synaptic neuron is connected to exactly n pre-synaptic neurons chosen at random.

which is what we do at the moment?

`    def _get_pre_neurons(self):
        if self._pre_neurons is None:
            self._pre_neurons = numpy.random.choice(
                self._n_pre_neurons, self._n_pre, False)
            self._pre_neurons.sort()
        return self._pre_neurons`

I'm guessing I'm missing something... ?

**Comment by rowleya** [comment]
I'm afraid the description is confusing; it is meant to be a different set of pre-synaptic neurons for each post-synaptic neuron.  In our model you get the same set of n pre-synaptic neurons for every post-synaptic neuron.  What we do fits in with the letter of the law, but not the spirit ;).

**Comment by andrewgait** [comment]
This issue has been dealt with, at least on host.  On-machine fixed pre- and post- will probably make the next release...
