### ISSUE TITLE
Separate conductance from neuron model

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#44]
A minor refactor would allow any model to be conductance based by separating the conductance to current input calculation from the neuron model

**Comment by hopper333** [comment]
Yes!

On Apr 2, 2015, at 4:22 AM, Andrew Rowley wrote:


A minor refactor would allow any model to be conductance based by separating the conductance to current input calculation from the neuron model

**Comment by alan-stokes** [comment]
this has occured. issue closed.
