### ISSUE TITLE
Too many placements. All 64 chips of a spin3 board

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#446]
dec 7th 8pm Master
windows
On a spin3 board 

For example with scritin https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/250

        Placement Information by Core
        =============================

Generated: 12/08/17 18:04:15 for target machine 'spinn-2.cs.man.ac.uk'

**** Chip: (0, 0)
Application cores: 18
  Processor 1: Vertex: 'multicast speed up application vertex for 0, 0', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: DataSpeedUpPacketGatherApplicationVertex

  Processor 2: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

  Processor 3: Vertex: 'stimulus', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: SpikeSourceArray

  Processor 4: Vertex: 'chain', pop size: 8
              Slice on this core: 0:7 (8 atoms)
              Model: IFCurrExpBase

**** Chip: (0, 1)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (0, 2)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (0, 3)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (1, 0)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (1, 1)
Application cores: 17
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (1, 2)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (1, 3)
Application cores: 17
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (2, 0)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (2, 1)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (2, 2)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (2, 3)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (2, 4)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (2, 5)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (3, 0)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (3, 1)
Application cores: 17
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (3, 2)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (3, 3)
Application cores: 17
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (3, 4)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (3, 5)
Application cores: 17
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (3, 6)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (4, 0)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (4, 1)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (4, 2)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (4, 3)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (4, 4)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (4, 5)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (4, 6)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (4, 7)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (5, 1)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (5, 2)
Application cores: 17
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (5, 3)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (5, 4)
Application cores: 17
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (5, 5)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (5, 6)
Application cores: 17
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (5, 7)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (6, 2)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (6, 3)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (6, 4)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (6, 5)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (6, 6)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (6, 7)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (7, 3)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (7, 4)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (7, 5)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (7, 6)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**** Chip: (7, 7)
Application cores: 18
  Processor 1: Vertex: 'ExtraMonitorSupportApplicationVertex', pop size: 1
              Slice on this core: 0:0 (1 atoms)
              Model: ExtraMonitorSupportApplicationVertex

**Comment by rowleya** [comment]
I believe that this is the expected behaviour, but Alan might comment further.  If we don't want this, we would be better doing things like this in SpiNNMan as the cores are then considered monitors.

**Comment by rowleya** [comment]
Technically, we could reduce this to chips with routes going through them...

**Comment by Christian-B** [comment]
I can except placing it on the unused chips.

However in this case it is placing it on 64 chips while a spin3 board only has 4.
This is clearly an error

**Comment by Christian-B** [comment]
correction: not spin 3 board
RATHER spinnaker.cs.man.ac.uk but REMOTELY from London

**Comment by alan-stokes** [comment]
if it had been a 4 chip board, it would def had been a erorr. and amazing one at that, given tis working off the python machine. lol. but glad it was user error in the end
