### ISSUE TITLE
Error with initial_values

### ISSUE THREAD

**Issue by apdavison** [SpiNNakerManchester/sPyNNaker#447]
The `initial_values` argument to the `Population` constructor is expected to be a dictionary, so that this line fails:

https://github.com/SpiNNakerManchester/sPyNNaker/blob/ee083cb093cd0d561903d1b5df6c3c73d4840dd2/spynnaker/pyNN/models/pynn_population_common.py#L30

It should be `for name, value in initial_values.items():`

**Comment by Christian-B** [comment]
Fixed in https://github.com/SpiNNakerManchester/sPyNNaker/pull/448

**Comment by rowleya** [comment]
Merged so closing
