### ISSUE TITLE
On resume. Wrong order for ClearIoBuff, Run and ReadIoOff

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#456]
On the second run the idea order is

Run (first run)
Read Io Buff
Clear IO Buff
Run (second time)
Read IO Buff

--

But the order you get is.
Run (first run)
Read Io Buff
Run (second time)
Clear IO Buff
Read IO Buff

The result is the iobuff stuff from run 2 is LOST.

The UGLY STICKY PLASTER is
Delay adding the clear_iobuf_during_run code in
Abstract_spinnaker_base _do_run
-
this fix depends on PACMAN algorithms being ordered 

But what needs to be done is make sure
Run has a token that postpones it to after clear io buff is executed.

**Comment by rowleya** [comment]
There is now a fix that uses tokens.  Note that clearing occurs before the application run of the second run i.e. you don't clear IOBuf on the first run.

**Comment by Christian-B** [comment]
Closing this as it works.

However it did bring up an interesting clash with my temporary fix of moving ChipIOBufClearer later in abstractSpinakerbase.

This cause and order of
ChipRuntimeUpdater
DatabaseInterface
NotificationProtocol
GraphProvenanceGatherer
ChipIOBufClearer
ApplicationRunner

The log messages done during ChipRuntimeUpdater phase where LOST!

**Comment by rowleya** [comment]
Fixed more in SpiNNakerManchester/SpiNNFrontEndCommon#269

**Comment by Christian-B** [comment]
Assumed fixed with last pr
