### ISSUE TITLE
reverse iptag multicast source has a bug with is vs ==

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#46]
line 261 shows:

 if self._prefix_type is EIEIOPrefix.LOWER_HALF_WORD:
                spec.write_value(data=self._prefix)
            else:
                spec.write_value(data=self._prefix << 16)

its very likely that this will not work, as is (we think) is the wrong check here, we think it should be ==

The code cannot be tested due to another error.

**Comment by alan-stokes** [comment]
closing due to assumption that its a dead error. please reopen if not.

**Comment by nmscott** [comment]
Hey, 

I've recently tried working as a freelance journalist  and  wrote some interesting articles,  check  it out <http://chevocrowu.imagesinphotography.com/e4wjx>

nathan
