### ISSUE TITLE
Accessing SpiNNaker programatically.

### ISSUE THREAD

**Issue by russelljjarvis** [SpiNNakerManchester/sPyNNaker#469]
I am trying to re program the connectivity of this network:
https://github.com/SpiNNakerManchester/PyNN7Examples/blob/master/examples/va_benchmark.py
Using a python pickle pyNN friendly variation of the this hippocampome network:
http://hippocampome.org/php/connectivity.php
found [here](https://github.com/russelljjarvis/DAnalysisCNeuro/blob/master/connections.p):

I have completed two preliminary tasks (described below). 

I have used PyNN to create a network an active network of Izhikitich cells using the required connectivity in a different ([model](https://github.com/russelljjarvis/DAnalysisCNeuro/blob/master/group_assignment.ipynb). I have also run a SpiNNaker friendly network benchmark by graphically copying and pasting code into the human brain projects collaboratory GUI. 

I am now ready to use the code from va_benchmark.py, but with connectivity defined by aforementioned [pickle file](https://github.com/russelljjarvis/DAnalysisCNeuro/blob/master/connections.p. ), using a pattern given by the code snippet below:

```python
import pickle
with open('unit_test/connections.p','rb') as f:
   [ post_inh,pre_inh,pre_exc,post_exc] = pickle.load(f)
pre_inh = inh_cells[pre_inh]
post_inh = all_cells[post_inh]
pre_exc = exc_cells[pre_exc]
post_exc = all_cells[post_exc]

connections = {}
connections['inh'] = sim.Projection(pre_inh, post_inh, connector, exc_syn, receptor_type='excitatory')
connections['exc'] = sim.Projection(pre_exc, post_exc, connector, inh_syn, receptor_type='inhibitory')
```
However when I try to submit a job with extra filenames as arguments via the python `nmpi` API, I am getting the error `Exception: Error 403: You do not have permission to create a job`.

I am wondering if there is a better way to get files onto the Human Brain Collaboration portals SpiNNaker? I am also wondering if there is a way I can apply to escalate my privilege level?

Thanks.
Russell.

```python
import nmpi
c = nmpi.Client("rjjarvis", token=token)

job_id = c.submit_job(source="neuromorphic.py",

                      platform=nmpi.SPINNAKER,

                      collab_id=141,

                      inputs=["unit_test/connections.p","unit_test/neuromorphic.py"],

                      command="run.py {system}")

You do not have permission to create a job

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-18-7e8e35f122b0> in <module>()
      3                       collab_id=141,
      4                       inputs=["unit_test/connections.p","unit_test/neuromorphic.py"],
----> 5                       command="run.py {system}")

/opt/conda/lib/python3.5/site-packages/nmpi/nmpi_user.py in submit_job(self, source, platform, collab_id, config, inputs, command, tags)
    328             else:
    329                 return "Job not submitted: 'tags' field should be a list."
--> 330         result = self._post(self.job_server + self.resource_map["queue"], job)
    331         print("Job submitted")
    332         return result

/opt/conda/lib/python3.5/site-packages/nmpi/nmpi_user.py in _post(self, resource_uri, data)
    255                             headers={"content-type": "application/json"})
    256         if not req.ok:
--> 257             self._handle_error(req)
    258         if 'Location' in req.headers:
    259             return req.headers['Location']

/opt/conda/lib/python3.5/site-packages/nmpi/nmpi_user.py in _handle_error(self, request)
    223             errmsg = errmsg.decode('utf-8')
    224         logger.error(errmsg)
--> 225         raise Exception("Error %s: %s" % (request.status_code, errmsg))
    226 
    227     def _query(self, resource_uri, verbose=False, ignore404=False):

Exception: Error 403: You do not have permission to create a job
```

**Comment by rowleya** [comment]
This looks more like a problem with the Neuromorphic Collab interface than a problem with SpiNNaker specifically.  I can see that you have been accepted to run jobs on the interface, but I don't see anything related to the collab with id 141 - the only collab with your name against it has id 5458.  Is this a new Collab in which you are trying to run this job?  If so, this will need to be approved separately.

**Comment by russelljjarvis** [comment]
You are right, appropriately updating the collab identity fixes the problem. I can submit jobs, given the correct collab id.
