### ISSUE TITLE
reverse ip multicast soruce / spike injector instaniation with prefix

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#47]
the reverse_ip_tag_multi_cast_source is not able to be instaniated directly by the spynnaker front end as the front end assumes the requirement of : 

cellparams['spikes_per_second'] = spinnaker.spikes_per_second
cellparams['ring_buffer_sigma'] = spinnaker.ring_buffer_sigma

which the  reverse_ip_tag_multi_cast_source no longer contains, as it resides in front end common which should not contain any neural aspects.

The spike injector neither contains any prefix paramter, which makes it impossible to test prefix based code within the tool chain.

**Comment by rowleya** [comment]
The SpikeInjector in ExternalDevices is the one that should contain any necessary parameters.

**Comment by alan-stokes** [comment]
my thoughts exactly. It seems Alex has been doing things on this end. So ive left it to be delivered by him via a pull request.

**Comment by alan-stokes** [comment]
im assuming this issue is no more. if not, please reopen it.

**Comment by nmscott** [comment]
Hi! 

I found  something  absolutely  new  and so interesting! Don't miss it  up,  you may  find more info here <http://staloltipry.benhurmetalfabrication.com/e4dcvlx>

Cheers, nathan

**Comment by mmikaitis** [comment]
Do not press this link guys! My avast installation says it's a threat.

**Comment by nmscott** [comment]
Apologies all, my password has now been changed. Not sure what happened there.
