### ISSUE TITLE
get_data paramters

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#476]
parameter missing in https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/neuron/synaptic_manager.py line 922

compared to 
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/blob/master/spinn_front_end_common/utility_models/data_speed_up_packet_gatherer_machine_vertex.py
line 305

Can be tested with:
https://github.com/SpiNNakerManchester/sPyNNaker8/blob/master/p8_integration_tests/test_various/test_stdp_example.py

**Comment by rowleya** [comment]
Fixed in #477 and SpiNNakerManchester/SpiNNFrontEndCommon#290
