### ISSUE TITLE
[Structural Plasticity] Add ability to record

### ISSUE THREAD

**Issue by pabogdan** [SpiNNakerManchester/sPyNNaker#487]
Currently, the only ways of observing the effect of structural plasticity are either to enable appropriate log_infos in relevant C files, recompiling and text mining through the resulting reports, or to occasionally extract connectivity information during the simulation. This is clearly not ideal.

A solution that would tie in more smoothly to PyNN would be nice. For example, ``structurally_plastic_projection.record("rewiring")`` would probably be more useful than our current approaches, not to mention faster and more accurate.

**Comment by andrewgait** [comment]
I agree this is a good idea, but what kind of variables or information would you suggest to be "recorded" here?  Clearly it's somewhat prohibitive in larger networks to record the connectivity after every timestep, but are you thinking of other variables (successful creations/eliminations, for example, or maybe just a "simple" count of the number of current connections at each timestep) as well?

**Comment by pabogdan** [comment]
> Clearly it's somewhat prohibitive in larger networks to record the connectivity after every timestep
Quite right. Users can already do this if they really want to, but I don't think anyone needs/wants this.
> but are you thinking of other variables (successful creations/eliminations, for example, or maybe just a "simple" count of the number of current connections at each timestep) as well?

In each timestep we could have number of incoming connection per neuron. This would implicitly contain the information about formations and removals. 

This approach would have the benefit of only requiring core-local information which I believe we already compute somewhere. 

The downside would be you need as much information to record this as for something like recording v or gsyn (info per neuron per timestep). 

Thoughts?

**Comment by rowleya** [comment]
If the data is useful, it is still optional so having the ability to do it sounds fine to me.

**Comment by pabogdan** [comment]
+ being able to record fan-ins for a subset of neurons would probably help here.

**Comment by andrewgait** [comment]
> Plus, being able to record fan-ins for a subset of neurons would probably help here.

If we set it up to do e.g. incoming connections per neuron, then the already-existing selective recording mechanisms will probably work here too.

**Comment by alan-stokes** [comment]
sounds good to me. assuming its uint32_ts and not floats. so its the basic stuff.

**Comment by andrewgait** [comment]
We do compute this sort of information locally on cores, but only during spike processing.  So if a neuron processes no spikes in a timestep, then it's not immediately obvious how to obtain the information about its incoming "live" connections... unless I'm missing something when looking at the current code.

**Comment by rowleya** [comment]
Hmm yes true; my advice would be then to record the addition and removal events themselves.  Everything else can be implied from this and the original connectivity.  I guess this would be a bit like spikes in that you don't know how often it will actually happen, so you have to guess the space required a bit.  I think the structural plasticity runs a fixed number of times per timestep, so there is a maximum number of changes.

**Comment by andrewgait** [comment]
Now that the structural plasticity recording code has been merged, closing this issue.
