### ISSUE TITLE
Different ports for different live event connections necessary?

### ISSUE THREAD

**Issue by georghinkel** [SpiNNakerManchester/sPyNNaker#490]
Hi,

just a short question, if you have multiple live event connections such as a SpynnakerPoissonControlConnection and a SpynnakerLiveSpikesConnection, can they share the same port or do they need different ports? I guess they would need different ports, but I just wanted to be sure. I am curious because these classes share the same default values (port 19999). 

Further, I have seen that spike injectors also need a port, but the examples use very different port numbers from the notification ports (19999 and 19996), namely something that seems to be rather random such as 12345 and 12346 in the spike_io example. In case you have multiple spike injector populations, I guess these port numbers must also be different? What are these port numbers used for? Are these ports of the host machine or of the Spinnaker board?

Best,

Georg

**Comment by alan-stokes** [comment]
short answer, yes. long answer, not recommended. 

detailed answer, having multiple connections with the same port risk them receiving data from multiple things, and you may not be able to filter them correctly. They may even overload each other. Therefore separating them is recommended, as then you know the data being received is for a given component. 

ports are part of sockets, which are a general thing, so google will help ya there.

**Comment by georghinkel** [comment]
So is the port number 12345 and 12346 that is given as a parameter to the SpikeInjector in the spike_io example a port number used in a socket at the board that would connect to a socket with the local_port that is specified with the LiveSpikeConnection (e.g., 19999)? 

Perhaps the more specific question is, I have a setup where I cannot really tell how many SpikeInjector populations there may be in a network, so I am concerned about the ports to put at the SpikeInjector populations. From your previous answer, I guess I have to reserve the ports for the connections (one connection for spike recording, one for spike injection, one for Poisson generators and one for leaky integrators), unless I can make sure that the labels used for these connections are distinct (I assume it is the labels that are used to multiplex a message to the connection, is it?).
Do I also have to reserve the ports for all SpikeInjector populations? These populations all have distinct names (unless you explicitly specify a name clash), so would that be OK if these populations share the same port? If so, why do the two populations in the spike_io example use different ports? Where are these ports used? Does every SpikeInjector population imply a socket on the board? On the host?

**Comment by rowleya** [comment]
So each SpikeInjector specifies:
- "port" - The UDP port on which the SpiNNaker machine will listen to for injected spikes, or None for this to be assigned automatically.  This is a port on the SpiNNaker machine.
- "database_notify_port_num" - The UDP port to which messages about the database and the simulation will be sent i.e. when the database is ready to be read, or the simulation is starting / resuming / pausing / stopping.  This is a port on the host machine.

Each of the SpynnakerLiveSpikesConnection or SpynnakerPoissonControlConnection classes takes a "local_port" optionally in the constructor.  This is the port on which that connection will listen for database connections i.e. the one that matches the "database_notify_port_num" above.  If you create more than one connection you need to use different ports for each - this is an operating system level restriction.  Each of these connections will be told when the database is ready to be read, and will read the database to find the appropriate port numbers to send messages to for each specified sender population.  The database is written with the label of each Population against these port numbers, so the reader needs to know the names of all the Populations you want to inject spikes into.

You can have up to around 8 injected and live things in total i.e. SpikeInjector, LiveRatePoissonSource or calls to activate_live_output_for per board; this is limited by the low-level software (SCAMP).  Each SpikeInjector needs a separate port, but note that these will be automatically assigned if not specified, and the SpynnakerLiveSpikesConnection will read the ports from the database for each.

**Comment by georghinkel** [comment]
Thanks!

**Comment by alan-stokes** [comment]
its also worth noting that this 8 is also reduced by other functionality in the tools. Master utilises a speed up process for data out, which utilises a separate port per board. So if that's turned on, your down to 7 things.
