### ISSUE TITLE
ExternalDeviceLifControl population sends membrane potentials as int instead of a S1615

### ISSUE THREAD

**Issue by georghinkel** [SpiNNakerManchester/sPyNNaker#492]
Neurons using the neuron model above are supposed to regularly send their membrane potentials as a multicast command packet with payload where the payload equals to the current membrane potential. They do that, but the membrane potential is sent as an integer instead of an S1615. This loses a lot of precision and sometimes drops the whole point of these devices as these membrane potentials often fall below 1.

**Comment by alan-stokes** [comment]
Hi George. 

to understand why this is the case, you need to revisit what the ExternalDeviceLifController was originally designed to interface with. aka a push bot. The values that the lab manual for its protocol states are in the range of 1 to 100, and so the controller converts to that format. It is not hard to duplicate the code and replace the int with a s1615, or even better, augment the code to switch format types based off init parameters, but currently this is not implemented as noone has asked. 

I recommend you augment the ExternalDeviceLifController c and python to do the switch and produce a pull request for us to review, as us getting to it may take longer than yourself. 

regards
Alan

**Comment by rowleya** [comment]
One thing to note is that the output value is between 1 and 100, but the internal representation is a fixed point value - thus it is just chopped off at the end.  I don't think you can just change this, as existing devices might not be compatible with the fixed point format; instead it might be good to have a format flag which would indicate whether conversion is desired.  Alternatively, fixed-point numbers are treated as integers internally - therefore using larger numbers and then just treating the value as fixed-point would also work (using a power of 2 multiplier for example).

**Comment by andrewgait** [comment]
The fix for this has been merged, so closing this issue.
