### ISSUE TITLE
spynnaker or spynakker?

### ISSUE THREAD

**Issue by chanokin** [SpiNNakerManchester/sPyNNaker#499]
I noticed the ranged dictionaries and lists use spynakker as a prefix instead of spynnaker, is this OK?

https://github.com/SpiNNakerManchester/sPyNNaker/tree/master/spynnaker/pyNN/utilities/ranged

**Comment by alan-stokes** [comment]
(cwl) technically yes, its fine, its just a class name. In reality, that likely needs to change, for consistency sake. 

would be cool to know who cant type spynnaker. im quite happy to find tis me. ive made enough sillies like that over the years.

**Comment by dkfellows** [comment]
I've been correcting this sort of issue as I go along, but some places are more intrusive than others.

**Comment by andrewgait** [comment]
Not sure this really needs to be an issue any more; this specific spelling mistake has been dealt with now.
