### ISSUE TITLE
Why are we copying a value to itself?

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/sPyNNaker#504]
https://github.com/SpiNNakerManchester/sPyNNaker/blob/2bb5e69265e76ee225db43e84e539e12fcc35638/neural_modelling/src/neuron/input_types/input_type_current.h#L25

This is pretty weird…

**Comment by andrewgait** [comment]
Discussed this with @oliverrhodes - there are plans underway to use this loop to apply a different scaling dependent upon the syanpse type of the receptor, hence the loop over the number of receptors.  He's still working on it at the moment, but it would be helpful if this stayed as it is at the moment as it will basically be changed to `value[i] = value[i] * scaling_factor[i]` at some point in the future.

**Comment by andrewgait** [comment]
A comment was added to the code here to make it clear what's going on; closing this issue for now.
