### ISSUE TITLE
fixed-plastic synaptic entry masking 

### ISSUE THREAD

**Issue by chanokin** [SpiNNakerManchester/sPyNNaker#505]
In SynapseDynamicsSTDP, if we are computing neuron id, synapse type bits in [Lines 185-187](https://github.com/SpiNNakerManchester/sPyNNaker/blob/2bb5e69265e76ee225db43e84e539e12fcc35638/spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py#L185-L187) to use as shifts

https://github.com/SpiNNakerManchester/sPyNNaker/blob/2bb5e69265e76ee225db43e84e539e12fcc35638/spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py#L185-L187

Then masks should also be computed for [Lines 195-203](https://github.com/SpiNNakerManchester/sPyNNaker/blob/2bb5e69265e76ee225db43e84e539e12fcc35638/spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py#L195-L203):

https://github.com/SpiNNakerManchester/sPyNNaker/blob/2bb5e69265e76ee225db43e84e539e12fcc35638/spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py#L195-L203

Same thing applies to [Line 288](https://github.com/SpiNNakerManchester/sPyNNaker/blob/2bb5e69265e76ee225db43e84e539e12fcc35638/spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py#L288)

https://github.com/SpiNNakerManchester/sPyNNaker/blob/2bb5e69265e76ee225db43e84e539e12fcc35638/spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py#L288

**Comment by rowleya** [comment]
Oh yes - missed that bit!  I suspect the read-back is the more important bit here (as if we are correct with the number of bits the other bits will be 0 anyway during construction).  Also need to check if the same is true of non-STDP synapses and read-back....

**Comment by chanokin** [comment]
True, it's the reading that breaks.

**Comment by andrewgait** [comment]
It looks like this has now been fixed in master, so closing.
