### ISSUE TITLE
.pacman.cfg and .spynnaker.cfg don't co-exist

### ISSUE THREAD

**Issue by neworderofjamie** [SpiNNakerManchester/sPyNNaker#51]
Even if .spynnaker.cfg exists, sPyNNaker won't run unless there is no .pacman.cfg in your home directory. This makes it impossible for something that uses the SVN tools e.g. Nengo SpiNNaker to coexist happily with the git tools.

**Comment by alan-stokes** [comment]
I guess we can assume now that we've had numerious releases where end users have been told to reinistall the tools and therefore have now moved over to the spynnaker.cfg file formats. Given that assumption, we can remove the check for legacy pacman.cfg's from the config interface, which will remove this issue entirely.

**Comment by alan-stokes** [comment]
fixed in GFE prov after crash brnahc, which is currnetly under review (sorry rowley) and so this will soon go into master (before the code freeze) and therefore will be in the Another Fine Product From The Nonesence Factory release. 

closing the issue accordinly.
