### ISSUE TITLE
Outdated comment or some confusion

### ISSUE THREAD

**Issue by mmikaitis** [SpiNNakerManchester/sPyNNaker#517]
https://github.com/SpiNNakerManchester/sPyNNaker/blob/8d258376692b897cf41f4807763634524a24725d/neural_modelling/src/neuron/synapses.c#L194

I think this comment could be outdated or perhaps I might not be aware of some optimisation here.

It seems from the assembly output that this piece of code is done simply by loading 0xFFFF from memory using LDR{NE}. Perhaps the author was hoping to get something like this instead:

MOV Rx, #0x10000
SUB Rx, Rx, #1 

... in order to avoid loading 0xFFFF from memory and because MOV Rx, #0xFFFF is an illegal instruction in 32-bit ARM. However, I am not sure that that is faster than LDR? :)

**Comment by rowleya** [comment]
I think this is heavily dependent on the compiler used; the decompilation I have is:
```
add	r2, r2, fp, lsr #16
tst	r2, #65536 ; 0x10000
movne	r2, sl
addne	ip, ip, #1
movne	lr, r9
```

The point of this was I believe as you say - to avoid needing to have a double load for the 0xFFFF.

**Comment by mmikaitis** [comment]
Ah I see, you are right that it depends on the compiler. I get a single conditional LDR after the TST:

2039      cbc:   e3120801    tst r2, #65536  ; 0x10000
**2040      cc0:   159f2020    ldrne   r2, [pc, #32]   ; ce8 <synapses_process_synaptic_row+0xd8>**
2041      cc4:   128cc001    addne   ip, ip, #1
2042      cc8:   13a0e001    movne   lr, #1
2043      ccc:   e18720b3    strh    r2, [r7, r3]
2044      cd0:   eaffffee    b   c90 <synapses_process_synaptic_row+0x80>
2045      cd4:   e35e0000    cmp lr, #0
2046      cd8:   1584c028    strne   ip, [r4, #40]   ; 0x28
2047      cdc:   e3a00001    mov r0, #1
2048      ce0:   e8bd87f0    pop {r4, r5, r6, r7, r8, r9, sl, pc}
2049      ce4:   00400034    .word   0x00400034
**2050      ce8:   0000ffff    .word   0x0000ffff**

**Comment by andrewgait** [comment]
This seems to not be an issue, so closing.
