### ISSUE TITLE
“conflicting types for size_t ” problem arise when adding new timing dependence rule

### ISSUE THREAD

**Issue by shaw0908** [SpiNNakerManchester/sPyNNaker#527]
Hi, as indicated I was following the tutorial on adding new rule given in 
http://spinnakermanchester.github.io/spynnaker/4.0.0/NewPlasticityRules-LabManual.pdf

1. I ran it on MacOSX 
2. C compiler has been installed as in :
     http://spinnakermanchester.github.io/common_pages/4.0.0/Compiler.html
3. C environment variables was set as :
   export NEURAL_MODELLING_DIRS=/Users/han/PycharmProjects/NN/sPyNNaker/neural_modelling
export SPINN_DIRS=/Users/han/PycharmProjects/NN/spinnaker_tools/
export PATH="/spinnaker_tools/tools:$PATH"
export PERL5LIB=/spinnaker_tools/tools
4. The required spinnaker package has been installed 
![screenshot01](https://user-images.githubusercontent.com/39651191/41207012-be1be908-6d05-11e8-9c84-1fa5b833bcc8.png)
5. This is how I modified the "Makefile" in  "Neuron" file
![ss02](https://user-images.githubusercontent.com/39651191/41207036-100ab1ae-6d06-11e8-9286-b5855276d551.png)
6. This is how I modified the "Makefile" in IF_curr_exp_stdp_mad_pair_custom_additive
![ss03](https://user-images.githubusercontent.com/39651191/41207045-522c4a70-6d06-11e8-97e6-bdbde6a0f1e5.png)
7. After typing "Make" under neuron file, this is the error
![ss04](https://user-images.githubusercontent.com/39651191/41207050-7efc584c-6d06-11e8-85d6-61642071a430.png)

I've been working on it for a while, still confused about how "conflict" arose and no one seems to have same question as me. Any help would be appreciated.

**Comment by rowleya** [comment]
There seems to be an issue with the latest gcc version for OS X.  I have had reports that it works when using a version downloaded from here:
https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads

Don't pick the latest version, but the one labelled "6-2017-q2-update June 28, 2017"

**Comment by shaw0908** [comment]
@rowleya  Thanks

**Comment by andrewgait** [comment]
This is related to the issues with gcc 7.0 onwards; closing this specific one for now and keeping https://github.com/SpiNNakerManchester/sPyNNaker/issues/551 open.
