### ISSUE TITLE
sPyNNakerExtraModelsPlugin build issues

### ISSUE THREAD

**Issue by neworderofjamie** [SpiNNakerManchester/sPyNNaker#53]
Firstly, none of the existing makefiles in this module work any more.

Secondly, my attempt at following the guide here https://github.com/SpiNNakerManchester/SpiNNakerManchester.github.io/wiki/1.1-PyNN-on-SpiNNaker-Extension-Development-Guide-Pre_release resulted in a makefile something like this which got to sPyNNaker/neural_modelling/src/neuron/builds/Makefile.common:52 before it died trying to follow a relative path.

```Makefile
APP = $(notdir $(CURDIR))
BUILD_DIR = build/
EXTRA_SOURCE_DIR = $(CURDIR)/../../../
SOURCE_DIRS = $(NEURAL_MODELLING_DIRS)/src/neuron
MODEL_OBJS = $(SOURCE_DIRS)/neuron/models/neuron_model_lif_curr_impl.o \
             $(SOURCE_DIRS)/neuron/plasticity/common/post_events.o \
             $(SOURCE_DIRS)/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_impl.o \
             $(SOURCE_DIRS)/neuron/plasticity/common/maths.o \
             $(EXTRA_SOURCE_DIR)/neuron/plasticity/stdp/timing_dependence/vogels_2011.o \
             $(SOURCE_DIRS)/neuron/plasticity/stdp/weight_dependence/weight_additive_one_term_impl.o
NEURON_MODEL_H = $(SOURCE_DIRS)/neuron/models/neuron_model_lif_curr_impl.h
SYNAPSE_TYPE_H = $(SOURCE_DIRS)/neuron/synapse_types/synapse_types_exponential_impl.h
TIMING_DEPENDENCE_H = $(EXTRA_SOURCE_DIR)/neuron/plasticity/stdp/timing_dependence/vogels_2011_impl.h
WEIGHT_DEPENDENCE_H = $(SOURCE_DIRS)/neuron/plasticity/stdp/weight_dependence/weight_additive_one_term_impl.h
PLASTIC_SYNAPSE_STRUCTURE_H = $(SOURCE_DIRS)/neuron/plasticity/stdp/synapse_structure/synapse_structure_weight_impl.h
APPLICATION_MAGIC_NUMBER = 0xAC1

CFLAGS += -I$(NEURAL_MODELLING_DIRS)/src

APP_OUTPUT_DIR = $(CURDIR)/../../../../../spynnaker_extra_pynn_models/model_binaries

include $(SOURCE_DIRS)/builds/Makefile.common
```

I have just pushed this makefile into the vogels2011 branch of sPyNNakerExtraModelsPlugin

**Comment by alan-stokes** [comment]
So i tried to figure this out, but even with a absoluete file path (hardcoded or using a envoiromental variable) ti just burns. so im confussed. Ill leave it for Rowley to deal with. But at least I tried.

**Comment by alan-stokes** [comment]
fixed (i'd missed to merge front end common branch of this module during the merge of front end common) (id also missed it during the branch pruning) so apologies for all of this. 

Ive merged it in and it now works on the capo2015 branch. Can I ask if this now means vogals2011 branch is obsolete?

Alan
