### ISSUE TITLE
u variable initialization for Izhikevich

### ISSUE THREAD

**Issue by chanokin** [SpiNNakerManchester/sPyNNaker#537]
Variable _u_ in the Izhikevich model implementation should be initialized to _v_*_b_ according to the author's codes.

https://github.com/SpiNNakerManchester/sPyNNaker/blob/779483a16e569d9720731dc712ffa8d4f10f5dbd/spynnaker/pyNN/models/neuron/neuron_models/neuron_model_izh.py#L83

TL;DR

`self._data[U_INIT] = v_init * b `

**Comment by alan-stokes** [comment]
if that's the case, why have a u_init incoming param? 

and given the units for v_init and u_init are different. maybe you've found a bug in the authors code?

https://github.com/SpiNNakerManchester/sPyNNaker/blob/779483a16e569d9720731dc712ffa8d4f10f5dbd/spynnaker/pyNN/models/neuron/neuron_models/neuron_model_izh.py#L72-L73

**Comment by apdavison** [comment]
A user may always wish to use a model differently to the original authors' intentions, this is why we have `u_init`. 

Ideally the *default* initialization should be `v_init * b`, however PyNN does not yet support computed default initial values. Perhaps you could create a ticket in the PyNN issue tracker for this: 
https://github.com/NeuralEnsemble/PyNN/issues/new ?

(The units of `b` are `ms^-1`, so the units are consistent)

**Comment by alan-stokes** [comment]
well if that's meant to be the default. then we can fix it in the next release. Maybe @chanokin  can make the pynn issue and we'll fix it in spynnaker linked to this issue

**Comment by andrewgait** [comment]
Was this ever dealt with or added as a PyNN issue?

**Comment by rowleya** [comment]
I don't think so - we support initial u values, but I think the default is still 0.

**Comment by andrewgait** [comment]
The default initial values are currently set to b=0.2, v=-70.0, u=-14.0, so we are using u_init = v_init * b by default as it stands.  I'm therefore going to close this issue for now (and my personal opinion is that it's really a PyNN issue rather than a SpiNNaker issue if it needs to be taken any further...).
