### ISSUE TITLE
One instance of an Structural Plasticity Mechanism object used in multiple projections

### ISSUE THREAD

**Issue by pabogdan** [SpiNNakerManchester/sPyNNaker#541]
One instance of an Structural Plasticity Mechanism object used in multiple projections causes all of them to have the same shared seed. This is wrong as each post-synaptic application vertex is supposed to have a coherent shared seed, but this seed is not supposed to be shared among multiple application vertices.

**Comment by pabogdan** [comment]
I believe I've resolved this issue here: https://github.com/SpiNNakerManchester/sPyNNaker/commit/55414f7591392cfe61fc120f4103377a7ace92e8

Testing required however!

**Comment by alan-stokes** [comment]
Hi peter. You may want to check how andy did the fix for weights and delays being used in the same issue. It was much more complicated than what i can see with yours. so it may be that theres some pwoer lines ya running over. or that ya missed completely.

**Comment by andrewgait** [comment]
The weights and delays branch hasn't been merged yet, it's waiting for review here: https://github.com/SpiNNakerManchester/sPyNNaker/pull/525 at the moment.  There's probably an associated branch on sPyNNaker8 as well.

**Comment by andrewgait** [comment]
Peter's saying this is done, and PR #525 has also been merged, so closing this issue.
