### ISSUE TITLE
CSA Connector Incompatible With Virtualenvs On MacOSX

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/sPyNNaker#544]
The new CSA connector is broke. One of the ways it is broke is that it needs the `csa` package. The `csa` package needs to be able to execute inside `matplotlib` when installing. (WTF dudes!) The `matplotlib` package is incredibly finicky about running inside virtualenvs on OSX, as has been documented elsewhere… so essentially if you don't configure your virtualenv correctly right at the beginning (a very non-obvious time!) then you can't install sPyNNaker on OSX in that virtualenv because of shitty design in a whole bunch of components that we don't control. And you _also_ need to set up semi-obvious configuration files (`~/.matplotlib/matplotlibrc`) to make things work. _ALL BECAUSE SOME PART-TIME PROGRAMMER HAS NO IDEA WHAT IS A GOOD IDEA TO HAVE AS A DEPENDENCY!_

I'm more than a bit aggrieved about this. In particular, I'm upset at how nasty this whole experience is. I also opened INCF/csa#11 about the real problem, but I don't expect anyone professional to ever review that.

**Comment by rowleya** [comment]
Looks like you are getting a response to the csa ticket :)

**Comment by rowleya** [comment]
Additionally, if this doesn't happen, we could make the csa package optional as well

**Comment by andrewgait** [comment]
It’s probably best if we make it optional - there are as Donal says a number of issues with installing matplotlib in OSX that are best avoided unless the user wants the plotting capabilities or csa available.

**Comment by andrewgait** [comment]
@Christian-B was this dealt with fully in https://github.com/SpiNNakerManchester/sPyNNaker/pull/678 ?

**Comment by alan-stokes** [comment]
this still open? or does it need closing?

**Comment by Christian-B** [comment]
https://github.com/SpiNNakerManchester/sPyNNaker/pull/678 does not deal with the problem.

It delays raising the import issue from the moment the connector is imported until the moment it is used. (init)

**Comment by Christian-B** [comment]
I do not consider this a blocker. Sorry Mac users

**Comment by dkfellows** [comment]
As long as things install and allow people to use _other_ connectors, it's not a big problem.

**Comment by Christian-B** [comment]
This will not be fixed as the CSA connector is not a priority.

Please reopen if there is a specific use.
