### ISSUE TITLE
IF_cond_exp_stoc fails to build with arm-gcc 7.3

### ISSUE THREAD

**Issue by andrewgait** [SpiNNakerManchester/sPyNNaker#551]
Error found by @oliverrhodes and Chiara when trying to build the toolchain using most recent ARM gcc.  My suspicion is that it's something to do with mars_kiss64_simp(), as this is the only unique call from the IF_cond_exp_stoc model.

mkdir -p /localhome/mbbssag3/spinnaker/git/sPyNNaker/neural_modelling/builds/IF_cond_exp_stoc/neuron/
arm-none-eabi-gcc -c -mthumb-interwork -march=armv5te -std=gnu99 -ffreestanding -I /localhome/mbbssag3/spinnaker/git/spinnaker_tools/include -DLOG_LEVEL=LOG_INFO -Wall -Wextra -DPRODUCTION_CODE -DPROFILER_DISABLED -Os  -DAPPLICATION_NAME_HASH=0x5e8c95b4  -I     /localhome/mbbssag3/spinnaker/git/sPyNNaker/neural_modelling/modified_src/ -g -include  /localhome/mbbssag3/spinnaker/git/sPyNNaker/neural_modelling/modified_src/neuron/models/neuron_model_lif_impl.h -include  /localhome/mbbssag3/spinnaker/git/sPyNNaker/neural_modelling/modified_src/neuron/synapse_types/synapse_types_exponential_impl.h -include  /localhome/mbbssag3/spinnaker/git/sPyNNaker/neural_modelling/modified_src/neuron/input_types/input_type_conductance.h -include  /localhome/mbbssag3/spinnaker/git/sPyNNaker/neural_modelling/modified_src/neuron/threshold_types/threshold_type_maass_stochastic.h -include /localhome/mbbssag3/spinnaker/git/sPyNNaker/neural_modelling/modified_src/neuron/additional_inputs/additional_input_none_impl.h -include  /localhome/mbbssag3/spinnaker/git/sPyNNaker/neural_modelling/modified_src/neuron/implementations/neuron_impl_standard.h -o /localhome/mbbssag3/spinnaker/git/sPyNNaker/neural_modelling/builds/IF_cond_exp_stoc/neuron/neuron.o /localhome/mbbssag3/spinnaker/git/sPyNNaker/neural_modelling/modified_src/neuron/neuron.c
/localhome/mbbssag3/spinnaker/git/sPyNNaker/neural_modelling/modified_src/neuron/neuron.c: In function 'neuron_do_timestep_update':
/localhome/mbbssag3/spinnaker/git/sPyNNaker/neural_modelling/modified_src/neuron/neuron.c:288:6: internal compiler error: in gimple_build_assign_1, at gimple.c:422
 void neuron_do_timestep_update(timer_t time) {
      ^~~~~~~~~~~~~~~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
../neural_build.mk:274: recipe for target '/localhome/mbbssag3/spinnaker/git/sPyNNaker/neural_modelling/builds/IF_cond_exp_stoc/neuron/neuron.o' failed

**Comment by andrewgait** [comment]
A further note: this error is still present for arm-none-eabi-gcc version 8.2 (released in December 2018).

**Comment by dkfellows** [comment]
The problem is excited by the code on this line:

https://github.com/SpiNNakerManchester/sPyNNaker/blob/76fbc9bb6bd34636f3e5f96afe275664a74b6c8d/neural_modelling/src/neuron/threshold_types/threshold_type_maass_stochastic.h#L41

Specifically, it is caused by the combination of negation on an `accum`, multiplication on two `accum`s, and feeding the result into a function (`expk`). I've not checked if the function is vital there.

**Comment by dkfellows** [comment]
Since we're multiplying by `threshold_type->machine_time_step_ms_div_10` at that point, we can _trivially_ move the negation to host. Which is a good plan anyway as it means that threshold evaluation gets (marginally) cheaper.
