### ISSUE TITLE
spike source poisson time_between_spikes issue

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#553]
So this got me whilst using the possion as a example for our own codebase for converting nengo c code i came accross this:

the below link covers a definition of a globla struct. which you need to register on line 69 has a param called time_between_spikes.
https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/neural_modelling/src/spike_source/poisson/spike_source_poisson.c#L54-L88

now on line 97 the same available is defined, but outside the global, and it never set to anything (likely due to a time before the struct). 

https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/neural_modelling/src/spike_source/poisson/spike_source_poisson.c#L97

now on lines 404,
https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/neural_modelling/src/spike_source/poisson/spike_source_poisson.c#L404

512,
https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/neural_modelling/src/spike_source/poisson/spike_source_poisson.c#L512

are the only places where either time_between_spikes is used, but this is the one outside the global params. which is never set. 

me thinks theres a bug here somewhere. either make it link to global struct, or it needs to be instantiated

**Comment by andrewgait** [comment]
Or it's completely unnecessary and you don't need it at all in this code... ?  (cf: neuron.c and also delay_extension.c, where a similar parameter is defined (outside the global) and then read in from the neuron parameter data region...)

**Comment by rowleya** [comment]
It looks like there is an issue where a variable has been left behind when the struct was converted.  The correct answer is to use global_parameters.time_between_spikes.  I would guess that time_between_spikes is 0 otherwise...

**Comment by alan-stokes** [comment]
well if this nengo has one benifit, it includes a review of SSP. lol

**Comment by alan-stokes** [comment]
merged fix. so closing
