### ISSUE TITLE
Build failure on MacOS with the latest arm-none-eabi-gcc version 7.3 and 7.2.

### ISSUE THREAD

**Issue by mmikaitis** [SpiNNakerManchester/sPyNNaker#554]
I would like to report a potential bug. After reinstalling arm-none-eabi-gcc through macports on MacOS (which gets version 7.3), I got this build error when running make in sPyNNaker/neural_modelling:

In file included from /opt/local/arm-none-eabi/include/string.h:24:0,
                 from /Users/mantasmikaitis/SpiNNaker/sPyNNaker/neural_modelling/modified_src/neuron/implementations/neuron_impl_standard.h:17,
                 from <command-line>:0:
/opt/local/arm-none-eabi/include/strings.h:40:18: error: conflicting types for ‘size_t’
 typedef __size_t size_t;
                  ^~~~~~
In file included from /Users/mantasmikaitis/SpiNNaker/sPyNNaker/neural_modelling/modified_src/common/neuron-typedefs.h:15:0,
                 from /Users/mantasmikaitis/SpiNNaker/sPyNNaker/neural_modelling/modified_src/neuron/models/neuron_model.h:9,
                 from /Users/mantasmikaitis/SpiNNaker/sPyNNaker/neural_modelling/modified_src/neuron/models/neuron_model_lif_impl.h:5,
                 from <command-line>:0:
/Users/mantasmikaitis/SpiNNaker/spinnaker_tools/include/common-typedefs.h:75:18: note: previous declaration of ‘size_t’ was here
 typedef uint32_t size_t;
                  ^~~~~~
make[2]: *** [/Users/mantasmikaitis/SpiNNaker/sPyNNaker/neural_modelling/builds/IF_curr_exp/neuron/neuron.o] Error 1
make[1]: *** [all] Error 2
make: *** [all] Error 2

Going back manually to 7.2 I got the same problem. Going back further to 6.3, fixed the problem, therefore this is the most recent version that works.

Many thanks,
Mantas

**Comment by mmikaitis** [comment]
I run on the current master version.

**Comment by andrewgait** [comment]
Hi Mantas,

This is true more generally for all OSs as far as I know.  If you want to use version 7 then I have found that you can simply avoid this error by commenting out all “#include <string.h>” lines (eg line 17 of neuron/implementations/neuron_impl_standard.h, amongst others).

You’ll then find that IF_cond_exp_stoc fails to build (see https://github.com/SpiNNakerManchester/sPyNNaker/issues/551) - the only way round this so far is to remove that build from the makefile for now.  I’ll be looking at it at some point soon...

**Comment by andrewgait** [comment]
I ought to have said as well that I haven’t tested this when compiling in debug mode, which may throw up more issues as it may be that it is code that is only defined in debug mode that uses string.h - again, I’ll be aiming to look at this again soon.

**Comment by andrewgait** [comment]
This specific issue was dealt with, there are still issues with gcc 7.0 onwards, but these are detailed in https://github.com/SpiNNakerManchester/sPyNNaker/issues/551, so closing this issue.
