### ISSUE TITLE
Floating point enabled sPyNNaker build failure

### ISSUE THREAD

**Issue by mmikaitis** [SpiNNakerManchester/sPyNNaker#559]
There is a problem with shifting the floating point value, when building with floating point enabled.

In file included from <command-line>:0:0:
/Users/mantasmikaitis/SpiNNaker/sPyNNaker/neural_modelling/modified_src/neuron/input_types/input_type_conductance.h: In function 'input_type_get_input_value':
/Users/mantasmikaitis/SpiNNaker/sPyNNaker/neural_modelling/modified_src/neuron/input_types/input_type_conductance.h:32:29: error: invalid operands to binary >> (have 'input_t {aka double}' and 'int')
         value[i] = value[i] >> 10;
                    ~~~~~~~~ ^~
In file included from /Users/mantasmikaitis/SpiNNaker/sPyNNaker/neural_modelling/modified_src/common/neuron-typedefs.h:16:0,
                 from /Users/mantasmikaitis/SpiNNaker/sPyNNaker/neural_modelling/modified_src/neuron/models/neuron_model.h:9,
                 from /Users/mantasmikaitis/SpiNNaker/sPyNNaker/neural_modelling/modified_src/neuron/models/neuron_model_lif_impl.h:5,
                 from <command-line>:0:
At top level:
/Users/mantasmikaitis/SpiNNaker/sPyNNaker/neural_modelling/modified_src/common/maths-util.h:43:52: warning: 'macro_arg_4' defined but not used [-Wunused-variable]
 static REAL macro_arg_1, macro_arg_2, macro_arg_3, macro_arg_4;
                                                    ^~~~~~~~~~~
/Users/mantasmikaitis/SpiNNaker/sPyNNaker/neural_modelling/modified_src/common/maths-util.h:43:39: warning: 'macro_arg_3' defined but not used [-Wunused-variable]
 static REAL macro_arg_1, macro_arg_2, macro_arg_3, macro_arg_4;
                                       ^~~~~~~~~~~
/Users/mantasmikaitis/SpiNNaker/sPyNNaker/neural_modelling/modified_src/common/maths-util.h:43:26: warning: 'macro_arg_2' defined but not used [-Wunused-variable]
 static REAL macro_arg_1, macro_arg_2, macro_arg_3, macro_arg_4;
                          ^~~~~~~~~~~
/Users/mantasmikaitis/SpiNNaker/sPyNNaker/neural_modelling/modified_src/common/maths-util.h:43:13: warning: 'macro_arg_1' defined but not used [-Wunused-variable]
 static REAL macro_arg_1, macro_arg_2, macro_arg_3, macro_arg_4;
             ^~~~~~~~~~~
make[2]: *** [/Users/mantasmikaitis/SpiNNaker/sPyNNaker/neural_modelling/builds/IF_cond_exp/neuron/neuron.o] Error 1
make[1]: *** [all] Error 2
make: *** [all] Error 2

**Comment by rowleya** [comment]
I would be surprised if any of the code worked with floating point enabled.  For one thing, the host side doesn't know that it needs to send floating point values, so your initial values will be messy...

Is there a reason that you want it to work with floating point?

**Comment by mmikaitis** [comment]
Andrew,

I am working with Michael to replicate his Izhikevich paper ODE results, which also included floating point and just trying some improvements in terms of arithmetic. So I understand it is not compatible because Python writes everything into the machine as fixed-point? Do you know how it was run back then for the paper?

Many thanks

**Comment by rowleya** [comment]
I don't think any of the floating point versions were run in our tools.  It would be possible to convert the various parts and have a float flag to indicate which type the variables are, but this needs to be done on each component.  As you have already found, we have quite often assumed fixed point in the code, so there may be a few traps there!  Also, recording of v (if you need that) would also need to be made float-aware.

**Comment by mmikaitis** [comment]
That makes sense. I talked to Michael and he said that he run float simulation in ybug, which makes sense as you do not need any higher level python interfaces that run only in fixed-point. Closing this as this is not a bug. Thanks.
