### ISSUE TITLE
Rounding decimal to accum is inconsistent between python and C

### ISSUE THREAD

**Issue by mmikaitis** [SpiNNakerManchester/sPyNNaker#561]
[This might be more appropriate to file in front-end-common, but I was not sure]

I just spent some time trying to replicate a certain paper's results. I found that the issue was that the paper was done purely in ybug (Using only C models) and I was trying to replicate it in PyNN using SpiNNaker toolchain. Python was rounding decimal values to the nearest accum while C seems to just round them down.

To give an example, when we set a timestep in PyNN like this:

p.setup(timestep=0.1)

Python will actually write an accum 0xCCD (exactly 0.100006103515625 as decimal) and use this inside the neuron model ODE.

On the other hand, if we specify it in C level as:

timestep = REAL_CONST(0.1)

We will get an accum 0xCCC (exactly 0.0999755859375 as decimal), which gives mismatch between the two methods and the error propagates everywhere this value is used without an easy way of detecting it.

Note that in this case, Python's approach is correct because it rounds to the nearest accum whereas C rounds down. I suggest an enhancement which will report the exact values of all parameters from PyNN script to the user so that they are aware how it was rounded.

**Comment by alan-stokes** [comment]
just a thought. the c might be doing a int cast at some point, which would act basically like a math.floor.

**Comment by andrewgait** [comment]
It looks to me like this issue was dealt with in the accompanying PR which has been merged, so closing this as an issue.
