### ISSUE TITLE
no clear mapping between python and c code recording regions

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#562]
It ust to be that a variable had a given recording id and that it was handed down from python to the c code, thus avoiding mismatch between python and c. now the c has a hardcoded set of #defines which flag the index's, but there is no such fixment in the python, it only occurs due to a ordering of a list. this should instead be sent down to the c code, so that future changes do not cause this to crash.

moved from 
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/365#issuecomment-433142275

**Comment by Christian-B** [comment]
If it "ust to be" that was MANY years ago!

**Comment by andrewgait** [comment]
The hard-coded set of defines in C exactly matches the order of the hard-coded list in Python... I’m not sure that adding an extra layer to this on the off-chance that there might be some variable added to the list at some point (what would the new variable be, anyway...?) would be a good idea.  It’s no different really from a neuron model where you have to send the neuron parameters onto the machine in the same order as they have been defined in the C code...

**Comment by alan-stokes** [comment]
think this has been subercedded by neuron recording. as matrix vs bitfield regions are no longer special

**Comment by Christian-B** [comment]
Assigning to @andrewgait who I expect will close based on his comment from 29 Jul 2019
