### ISSUE TITLE
Spike recording fails index of a multiple of 32 neurons

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#570]
With 255 neurons and recording on the even neurons index recording fails.

Wrong size of data coming out.

reported by @rjames91 

Sample to trigger error.

import spynnaker8 as sim

sim.setup(timestep=1.0)
sim.set_number_of_neurons_per_core(sim.IF_curr_exp, 255)

pop_1 = sim.Population(255, sim.IF_curr_exp(), label="pop_1")
input = sim.Population(1, sim.SpikeSourceArray(spike_times=[0]), label="input")
input_proj = sim.Projection(input, pop_1, sim.AllToAllConnector(),
                            synapse_type=sim.StaticSynapse(weight=5, delay=1))
evens =[i for i in range(255) if i%2 == 0 ]
pop_1.record(["spikes", "v"], indexes=evens)
simtime = 10
sim.run(simtime)

neo = pop_1.get_data(variables=["spikes", "v"])
spikes1 = neo.segments[0].spiketrains
v = neo.segments[0].filter(name='v')[0]
sim.end()

**Comment by Christian-B** [comment]
Farther testing shows this is caused by the number of neurons recording being a multiple of 32.
(One a single core)

Error is thrown in any index array of length 32 * n and any pop size big enough to use the whole index

**Comment by rowleya** [comment]
Does this only happen when recording includes "spikes"?

**Comment by Christian-B** [comment]
The bug is specific to the recording of spikes where index recording is used and there is exactly a multiple of 32 but not all neurons recording on one core.

When the number recording is exactly a multiple of 32 an extra word is added to allow all none recording neurons somewhere to write their spikes to (therefor avoiding gating)

For some reason this extra word is not coming out.

**Comment by alan-stokes** [comment]
merged fix. closed unless its determined to not be a full fix
