### ISSUE TITLE
TypeError: _save_callback() got an unexpected keyword argument 'args'

### ISSUE THREAD

**Issue by zhangysjlu** [SpiNNakerManchester/sPyNNaker#579]
Dear Rowleya,

I am trying to deploy the spiking neural network to spinnaker through spynnaker8, but when I run simulation, an Error appered when calling spynnaker.pyNN.overridden_pacman_functions.spynnaker_data_specification_writer.SpynnakerDataSpecificationWriter.__call__ with inputs ['report_default_directory', 'write_text_specs', 'machine', 'app_data_runtime_folder', 'graph_mapper', 'graph', 'hostname', 'placements'] For details, please see the screenshot below. From the error trackback, it seems the error happened in the file of ~/anaconda2/lib/python2.7/site-packages/spynnaker/pyNN/models/neuron/connection_holder.py", line 96, in finish
self._notify(self), I have verified type(self._notify) is functools.partial. But I cannot see functools.partial has __save_calleback__. May you let me know where the error occurs? Thank you very much!
![screenshot from 2018-12-26 16-06-43](https://user-images.githubusercontent.com/13186004/50438327-61765e80-0928-11e9-9824-8fc31306b61d.png)

**Comment by rowleya** [comment]
I believe that this is fixed by SpiNNakerManchester/sPyNNaker8#187.  This is the branch "fix_save" in sPyNNaker8.

**Comment by dkfellows** [comment]
Can anyone confirm if this is fixed now?

**Comment by andrewgait** [comment]
Closing this, can be reopened if this is still an issue.
