### ISSUE TITLE
math domain error, SpikeSourcePoisson with FromListConnector

### ISSUE THREAD

**Issue by andrewgait** [SpiNNakerManchester/sPyNNaker#589]
While trying to sort out a problem for someone, I came across something that might be wrong; the question is whether the user is doing something daft or not.  The following script throws a ValueError because it tries to take the log of zero; it only does this because (a) it uses a FromListConnector with variable delays so that the delay variance is non-zero, and (b) the rate in the SpikeSourcePoisson population has been set to zero by the user.  Should a user be allowed to do this or should we tell them not to set a rate of zero?

(In the code in synaptic_manager.py, it basically makes a choice between using the "rate" value, or using "spikes_per_second" as set in the config file, so we can quite easily make it take the correct choice, or tell the user they're doing something strange...)

```
import spynnaker8 as sim
sim.setup(timestep=1.0)
poisson = sim.Population(2, sim.SpikeSourcePoisson(
    duration=1.0e10, rate=0.0, start=0.0))
receiver = sim.Population(2, sim.IF_curr_exp())

connections = [
(0, 0, 1.0, 7.0),
(1, 0, 2.0, 7.0),
(0, 1, 3.0, 7.0),
(1, 1, 4.0, 8.0)
]

conn = sim.FromListConnector(connections)
syn = sim.StaticSynapse(weight=0.5, delay=1)
sim.Projection(presynaptic_population=poisson,
               postsynaptic_population=receiver,
               connector=conn, synapse_type=syn, receptor_type="excitatory")

receiver.record(["v", "spikes"])
poisson.record("spikes")

sim.run(200.0)
```

**Comment by rowleya** [comment]
The tools should cope with a rate of 0.  In particular, the issue here comes down to the interaction with the FromListConnector which I don't fully understand; if you replace it with an AllToAllConnector it works fine.  I am guessing then that it is the values used that causes the issue?

**Comment by andrewgait** [comment]
The AllToAllConnector has a fixed delay value for every connection between the populations (from the StaticSynapse).  The FromListConnector allows you to set a different delay for each connection between the populations.  If the pre-vertex is a SpikeSourcePoisson then spikes_per_second gets set to the rate value; then if the variance across the delays is non-zero, this spikes_per_second value is used in the "_ring_buffer_expected_upper_bound" calculation, where, if it's zero, it causes the ValueError.  I think the solution to it is basically to use the rate value if it's zero, but to default back to the config value otherwise.

**Comment by andrewgait** [comment]
(If you change the final delay in the above script from 8.0 to 7.0, you'll see that it also works fine, because the delay variance is now zero).

**Comment by rowleya** [comment]
Another option is to revert to doing what is done when the variance is zero if the rate is zero.  I don't mind in the end since no spikes will be received in any case!

**Comment by rowleya** [comment]
Fixed in master
