### ISSUE TITLE
Record Spikes

### ISSUE THREAD

**Issue by qian-liu** [SpiNNakerManchester/sPyNNaker#59]
1. For a population with a size bigger than the restricted neuron number (e.g. 256) per core, only the first 256 neurons can be recorded.

2. The input population with spike_source_array cannot be recorded.

3. I tried to run a script to with an injected spike source array, there is the error:
 ===============Traceback (most recent call last):
  File "read_spike_file2.py", line 57, in <module>
    p.run(10000)
  File "/home/liuq/apt/2ndYear/pynn_workspace/temp/sPyNNaker-augmented_examples/spynnaker/pyNN/__init__.py", line 188, in run
    _spinnaker.run(run_time)
  File "/home/liuq/apt/2ndYear/pynn_workspace/temp/sPyNNaker-augmented_examples/spynnaker/pyNN/spinnaker.py", line 372, in run
    self._send_buffer_manager.load_initial_buffers()
  File "/home/liuq/apt/2ndYear/pynn_workspace/temp/sPyNNaker-augmented_examples/spynnaker/pyNN/buffer_management/buffer_manager.py", line 155, in load_initial_buffers
    self._send_initial_messages(vertex, region)
  File "/home/liuq/apt/2ndYear/pynn_workspace/temp/sPyNNaker-augmented_examples/spynnaker/pyNN/buffer_management/buffer_manager.py", line 277, in _send_initial_messages
    " region {} of vertex {}".format(bytes_to_go, region, vertex))
spynnaker.pyNN.exceptions.BufferableRegionTooSmall: The buffer size 2 is too small for any data to be added for region 2 of vertex inputSpikes_1:256:511

**Comment by alan-stokes** [comment]
this is another artifact from the binary search master pop vs 2d array master pop. (it broken) Thus we should release the tool chain with binaries with 2d array master pop.

**Comment by alan-stokes** [comment]
closing as covered in #68

**Comment by qian-liu** [comment]
For a population with a size bigger than the restricted neuron number (e.g. 256) per core, only the first 256 neurons can be recorded.

Same problem occurs with PoissonSourceArray.
And can we support poisson rate = 0?

**Comment by alan-stokes** [comment]
Hi Anna, So the current master branch (at least for the possion) no longer has this issue of only recording the first 256 spikes. Albiet this does not have a unlimited max_atoms_per_core, it has 256. To counter this, the only devices with infinite max_atoms_per_core are the spike_injector, and external devices, to which neither of these are recordable for their own reasons (spike injector is unable to predict the amount of memory it'll reuqire for recording, as its stream based, the external devices have no sdram, so doing record [which is sdram based] is pointless. This being said, its possible we could add a proxiy reocrdable pop on the chip where the input is being pumped in, and record that instead. This has now been defined as issue #138).

Im going to look at rate 0 this afternoon.

**Comment by alan-stokes** [comment]
fixed spike poisson so that you can have a rate of 0. its currently resides in the #fixed_possion_rate_0 branch and is currently awaiting merge into master, so should get into the arbitirary release.

**Comment by alan-stokes** [comment]
merged in a while ago. thus closing issue.
