### ISSUE TITLE
issue when running synfire chain

### ISSUE THREAD

**Issue by zhuahua1** [SpiNNakerManchester/sPyNNaker#591]
TypeError: Cannot cast array data from dtype('uint32') to dtype('int32') according to the rule 'safe'

comes from here:
  File "C:\Users\user\Documents\spinnaker\sPyNNaker\spynnaker\pyNN\models\neuron\synaptic_manager.py", line 889, in _get_ring_buffer_shifts
    weight_scale)
  File "C:\Users\user\Documents\spinnaker\sPyNNaker\spynnaker\pyNN\models\neuron\synaptic_manager.py", line 443, in _get_ring_buffer_to_input_left_shifts
    connector.get_n_connections_to_post_vertex_maximum()
  File "C:\Users\user\Documents\spinnaker\sPyNNaker\spynnaker\pyNN\models\neural_projections\connectors\from_list_connector.py", line 105, in get_n_connections_to_post_vertex_maximum
    return numpy.max(numpy.bincount(self._conn_list["target"]))

please advise.

**Comment by alan-stokes** [comment]
strangely. doing this works

return numpy.max(numpy.bincount(self._conn_list["target"].view('int32')))

so that might be the fix?????

**Comment by rowleya** [comment]
I believe so.  I know we have seen this before, just not sure if there is a fix and if so where!

**Comment by alan-stokes** [comment]
sPyNNaker\spynnaker\pyNN\models\neural_projections\connectors\from_list_connector.py", line 105,

replace 
return numpy.max(numpy.bincount(self._conn_list["target"]))
with 
return numpy.max(numpy.bincount(self._conn_list["target"].view('int32')))

ill make a pr for it tomorrow (still stuck waiting on my 5k sim to finish zzzzzzz)

**Comment by andrewgait** [comment]
Is this still an issue?  The change doesn't seem to have made it into master or any PR, but the FromListConnector has moved on a bit since this conversation.

**Comment by andrewgait** [comment]
Looking at the FromListConnector a bit more closely, I think this issue has been dealt with, but please reopen this if not.
