### ISSUE TITLE
FromListConnector error when providing only weights

### ISSUE THREAD

**Issue by filippoferrari** [SpiNNakerManchester/sPyNNaker#597]
When providing only the weights to a FromListConnector the program terminates with a ValueError.

Here is an example adapted from #589 

```python
import spynnaker8 as sim
sim.setup(timestep=1.0)
poisson = sim.Population(2, sim.SpikeSourcePoisson(
    duration=1.0e10, rate=0.0, start=0.0))
receiver = sim.Population(2, sim.IF_curr_exp())

connections = [
(0, 0, 1.0),
(1, 0, 2.0),
(0, 1, 3.0),
(1, 1, 4.0)
]

conn = sim.FromListConnector(connections, column_names=['weight'])
syn = sim.StaticSynapse(weight=0.5, delay=1)
sim.Projection(presynaptic_population=poisson,
               postsynaptic_population=receiver,
               connector=conn, synapse_type=syn, receptor_type="excitatory")

receiver.record(["v", "spikes"])
poisson.record("spikes")

sim.run(200.0)
```

The program terminates at [this line](https://github.com/SpiNNakerManchester/sPyNNaker/blob/63f73083d81febad18bdc08a8db09fab5144e3ef/spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py#L74).

**Comment by andrewgait** [comment]
This is a known issue: it has been fixed in the branch https://github.com/SpiNNakerManchester/sPyNNaker/pull/525 (currently waiting to be merged into master).  (You'll need the sPyNNaker8 equivalent branch at https://github.com/SpiNNakerManchester/sPyNNaker8/pull/150 as well).

Will keep this issue open until the branch gets merged.

**Comment by filippoferrari** [comment]
Thank you for your reply. 
I currently have sPyNNaker installed through pip. Do I have to reinstall everything following [this guide](http://spinnakermanchester.github.io/development/devenv.html) in order to use this feature?

**Comment by andrewgait** [comment]
Yes - you would have to do that to use that feature.  

More straightforwardly, you could just add the delays as another column in your connection list for now, and then it should work with the pip-installed version.

**Comment by filippoferrari** [comment]
That's great, thank you!

**Comment by andrewgait** [comment]
Branch #525 has been merged, so closing this issue.
