### ISSUE TITLE
Structural plasticity vs Reset

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#602]
Need to test what happens with Structural plasticity on a reset.

If you follow the strict rules all weights should rest.

Thanks @pabogdan for pointing this out.

**Comment by Christian-B** [comment]
Related to https://github.com/SpiNNakerManchester/sPyNNaker/issues/599

**Comment by rowleya** [comment]
It is worth testing this.  I think if we use the last full data generation after any reset, that should be fine, so long as changes to neuron parameters and initial state variables made after this are then also loaded on top of the generated data. 

Note that the last full data generation referred to above might be the first ever data generation, but if the user then changes the network in a way that requires remapping (which is only allowed after a reset anyway), it would have to do a full data generation again.

**Comment by Christian-B** [comment]
I tested this with intro_labs stdp adding:
sim.reset()
sim.run(1)
print(stdp_projection.getWeights())

and yes the weights all come out as zero.
