### ISSUE TITLE
sim.set only keeping state variables for one core.

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#603]
import spynnaker8 as sim

sim.setup(1.0)
sim.set_number_of_neurons_per_core(sim.IF_curr_exp, 2)
pop = sim.Population(6, sim.IF_curr_exp(i_offset=1, tau_syn_E=1), {}, label="pop")
pop.record("v")
sim.run(3)
pop.set(tau_syn_E=1)
sim.run(2)
neo = pop.get_data("v")
v = neo.segments[0].filter(name="v")
print(v)

**Comment by Christian-B** [comment]
related to https://github.com/SpiNNakerManchester/sPyNNaker/issues/599

**Comment by Christian-B** [comment]
If you do:
import spynnaker8 as sim

sim.setup(1.0)
sim.set_number_of_neurons_per_core(sim.IF_curr_exp, 2)
pop = sim.Population(6, sim.IF_curr_exp(i_offset=1, tau_syn_E=1), {}, label="pop")
pop.record("v")
pop.initialize(v=-60)
sim.run(3)
pop.set(tau_syn_E=1)
sim.run(2)
neo = pop.get_data("v")
v = neo.segments[0].filter(name="v")
print(v)


the second plus core changes v to 60 on the set call

**Comment by andrewgait** [comment]
I thought this might be fixed by https://github.com/SpiNNakerManchester/sPyNNaker/pull/669 but it would appear not.  There must be some mismatch between ApplicationVertex and MachineVertex somewhere which means that the correct thing happens on the first MachineVertex for each ApplicationVertex but none of the subsequent ones.  Can investigate further unless @rowleya has an immediate idea as to how to fix this.

**Comment by rowleya** [comment]
I have an idea... we used to have this problem and it is down to the resetting of a variable too early... I will take a look and see if I can work out how to fix it

**Comment by rowleya** [comment]
OK, I have done a change to sPyNNaker.  See if that helps...

**Comment by rowleya** [comment]
Nope, doesn't help... going to look again...

**Comment by rowleya** [comment]
OK, another fix in #669 now that should actually fix the issue.

**Comment by andrewgait** [comment]
Yes, that's done it - thanks.

**Comment by andrewgait** [comment]
This was fixed by https://github.com/SpiNNakerManchester/sPyNNaker/pull/669, so closing.
