### ISSUE TITLE
FromListConnector with wieghts and more than 255 cause exception

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#612]
If you use a fromList or fromFile connector with more than 255(I think) and weights and delays it throws

pynnaker.pyNN.exceptions.SynapseRowTooBigException: The connection between pop1 with 200 atoms and pop2 with 300 atoms has more synapses (300) than can currently be supported on this implementation of PyNN (255 for this connection type). Please reduce the size of the target population, or reduce the number of neurons per core.

Without weights and delays it works

Script:
import spynnaker8 as sim

sources = 200
destinations = 300
aslist = []
for s in range(sources):
    for d in range(destinations):
        aslist.append((s, d, 5, 2))

sim.setup(1.0)
sim.set_number_of_neurons_per_core(sim.IF_curr_exp, 100)
pop1 = sim.Population(sources, sim.IF_curr_exp(), label="pop1")
pop2 = sim.Population(destinations, sim.IF_curr_exp(), label="pop2")
synapse_type = sim.StaticSynapse(weight=5, delay=2)
projection = sim.Projection(
    pop1, pop2, sim.FromListConnector(aslist),
    synapse_type=synapse_type)
sim.run(0)
from_pro = projection.get(["weight", "delay"], "list")
print(len(from_pro))
sim.end()

**Comment by Christian-B** [comment]
I think the error is a Safety check that is no longer valid.

i tried 3000 destinations and that worked.

Ok it lost packets as I had 3000 source neurons all firing at the same time.

But the connector worked even 300 destinations. 
(Did like a one to one)

**Comment by Christian-B** [comment]
import spynnaker8 as sim

sources = 3000
destinations = 3000
aslist = []
for s in range(sources):
        aslist.append((s, s, 5, 2))

sim.setup(1.0)
sim.set_number_of_neurons_per_core(sim.IF_curr_exp, 10)
pop1 = sim.Population(sources, sim.SpikeSourceArray(spike_times=[0]), label="input")
pop2 = sim.Population(destinations, sim.IF_curr_exp(), label="pop2")
synapse_type = sim.StaticSynapse(weight=5, delay=2)
projection = sim.Projection(
    pop1, pop2, sim.FromListConnector(aslist),
    synapse_type=synapse_type)
pop2.record("spikes")
sim.run(20)
from_pro = projection.get(["weight", "delay"], "list")
print(len(from_pro))
spikes = pop2.spinnaker_get_data("spikes")
print(len(spikes))
sim.end()

**Comment by Christian-B** [comment]
Correction RAMPING it up does cause errors.
2019-03-08 09:02:18 ERROR: 0, 0, 11: There should be no plastic synapses! (synapse_dynamics_static_impl.c: 39)
2019-03-08 09:02:18 ERROR: 0, 0, 11: Error processing spike 0x1 for address 0x60c32ed8(local=0x40a2d4) (spike_processing.c: 217)
2019-03-08 09:02:18 ERROR: 0, 0, 11: 0: 0xa0400 (spike_processing.c: 222)

Script:
import spynnaker8 as sim

sources = 100
destinations = 3000
aslist = []
spiketimes = []
for s in range(sources):
    for d in range(destinations):
        aslist.append((s, s, 5, 2))
    spiketimes.append([s*20])
print(spiketimes)

sim.setup(1.0)
pop1 = sim.Population(
    sources, sim.SpikeSourceArray(spike_times=spiketimes), label="input")
pop2 = sim.Population(destinations, sim.IF_curr_exp(), label="pop2")
synapse_type = sim.StaticSynapse(weight=5, delay=2)
projection = sim.Projection(
    pop1, pop2, sim.FromListConnector(aslist),
    synapse_type=synapse_type)
pop2.record("spikes")
from_pro = projection.get(["weight", "delay"], "list")
sim.run(sources*20)
print(len(from_pro))
spikes = pop2.spinnaker_get_data("spikes")
print(len(spikes))
sim.end()

**Comment by Christian-B** [comment]
To overflow with the above script I commented out the safety check ing
https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/neuron/master_pop_table_generators/master_pop_table_as_binary_search.py
get_allowed_row_length  Line:153

**Comment by Christian-B** [comment]
Changing the append to:
        aslist.append((s, d, 5+random.random(), random.randint(1, 5)))

And the script above still works fine returning all 9000000 spikes sent over the list of 9000000 connections

**Comment by andrewgait** [comment]
The issue here is something that's going wrong in the FromListConnector, as it worked previously (at least at version 4.0) with the connections effectively set up like an AllToAllConnector as we have here.  (If you change it to sources = 1, destinations = 256 then it will fail with the safety check left in...)

**Comment by Christian-B** [comment]
Sometimes not is actually correct!
