### ISSUE TITLE
OneToOne off chip is n_source = n_destination but on chip if not

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#615]
Is it known that the OneToOne connector does not work with virtual machine (so on chip I assume) if 
the number of sources != the number of destinations?

if yes. Ok to close this with little or no explanation:

Script:
        import spynnaker8 as sim
        sim.setup(1.0)
        pop1 = sim.Population(3, sim.IF_curr_exp(), label="pop1")
        pop2 = sim.Population(3, sim.IF_curr_exp(), label="pop2")
        synapse_type = sim.StaticSynapse(weight=5, delay=1)
        projection = sim.Projection(
            pop1, pop2, sim.OneToOneConnector(),
            synapse_type=synapse_type)
        sim.run(0)
        weights = projection.get(["weight"], "list")
        print(len(weights))
        sim.end()

Change one of the 3s and on a virtual machine it fails.

**Comment by Christian-B** [comment]
This almost means that if with uneven sizes moving the weights = projection.get(["weight"], "list") before the run fails while for even sizes it works.

See: https://github.com/SpiNNakerManchester/sPyNNaker/issues/613

**Comment by andrewgait** [comment]
Yes.  The OneToOneConnector is on-chip if n_sources != n_destinations, but off-chip (it uses a "direct matrix" as there is only one connection per row) for n_sources = n_destinations.  See https://github.com/SpiNNakerManchester/sPyNNaker/blob/08fcb4fd39559bd92fc9cb5b76cd2314a0f70ec5/spynnaker/pyNN/models/neuron/synaptic_manager.py#L611 and https://github.com/SpiNNakerManchester/sPyNNaker/blob/08fcb4fd39559bd92fc9cb5b76cd2314a0f70ec5/spynnaker/pyNN/models/neuron/synaptic_manager.py#L837.

**Comment by Christian-B** [comment]
clear!
