### ISSUE TITLE
FromListConnector does not work with lists of weights

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#617]
Script:
import spynnaker8 as sim

sim.setup(timestep=1.0)
input_pop2 = sim.Population(2, sim.SpikeSourceArray([0]),  label="input")
pop = sim.Population(2, sim.IF_curr_exp(), label="pop")
as_list3 = [(0, 0), (1, 1)]
c3 = sim.Projection(input_pop2, pop, sim.FromListConnector(as_list3),
                    sim.StaticSynapse(weight=[0.7, 0.3], delay=[3, 33]))

sim.run(1)
print (c3.get(['weight', 'delay'], 'list'))
sim.end()

AbstractConnector._generate_values throws a TypeError: 'NoneType' object is not iterable

Notes:
lists of weights work with AllToAllConnector() and OneToOneConnector()

FromListConnector works with lists of just x and y and single wights and delay values.

FromListConnector works with lists  x, y wights, delays list and list in StaticSynapse as it ignores these values in StaticSynapse

**Comment by andrewgait** [comment]
PR merged so closing.
