### ISSUE TITLE
RadialPlacementFromChipConstraint appears not to work

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#628]
Script:
import spynnaker8 as sim
from pacman.model.constraints.placer_constraints import (
    RadialPlacementFromChipConstraint)
constraint = RadialPlacementFromChipConstraint(1, 1)
sim.setup(timestep=1.0)
sim.set_number_of_neurons_per_core(sim.IF_curr_exp, 100)
pop_1 = sim.Population(200, sim.IF_curr_exp(), label="pop_1")
pop_1.set_constraint(constraint)
input = sim.Population(1, sim.SpikeSourceArray(spike_times=[0]),  label="input")
sim.Projection(input, pop_1, sim.AllToAllConnector(),
     synapse_type=sim.StaticSynapse(weight=5, delay=1))
sim.run(10)
sim.end()

Placement report shows the vertex is not on chip 1,1

**Comment by andrewgait** [comment]
Before I embark on attempting to fix this, can I ask @rowleya whether the RadialPlacer should be working, or whether it's been superseded by the OneToOnePlacer?  I started looking at this but there are various places where the RadialPlacer appears to be out of date or just not working correctly and I wanted to check that it was worth fixing it before carrying on.

**Comment by rowleya** [comment]
I think RadialPlacer should be working - technically the OneToOnePlacer is based on it anyway...

**Comment by Christian-B** [comment]
https://github.com/SpiNNakerManchester/PACMAN/pull/204 only applies if the placer is changed in the config file.

The OneToOne placer should at least go pop.

**Comment by Christian-B** [comment]
https://github.com/SpiNNakerManchester/PACMAN/pull/204 now goes pop with OneToOnePlacer!  Thanks
