### ISSUE TITLE
Ordering of slices in report files now random

### ISSUE THREAD

**Issue by SimonDavidson** [SpiNNakerManchester/sPyNNaker#63]
The pacement_by_vertex report used to list the slices in index order, so atoms 0:99 then 100:199, etc.

But at some point that changed and now they are listed in random order, making it difficut to find a particular entry. It also feels a bit sloppy.

Could we change it back to the ordered behaviour?

This issue may also be relevant to other reports - I've not checked - but the same recommendation applies,

**Comment by alan-stokes** [comment]
done and merged into capo branch.
