### ISSUE TITLE
Update configuration to be smarter

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#64]
It is easy to have a configuration file that is out of date after an upgrade.  We should have a way of:
1) Keeping track of the version that a configuration file is for
2) When a configuration file is for an older version, upgrade it automagically for the user

This should be possible to do, so long as we have a way of keeping track of the supported options.  The old file should be backed up of course.

**Comment by alan-stokes** [comment]
after discussion, this has been decided to be not worth developing.
