### ISSUE TITLE
Merging of STDP edges doesn't work

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#67]
Merging of edges (i.e. two edges between the same pair of populations) doesn't work with STDP

**Comment by andrewgait** [comment]
Is this still an issue that needs dealing with?

**Comment by rowleya** [comment]
Good question!  As I can't remember what the issue was, I suspect it isn't important.  A future issue could be to allow different parameters on different edges with the same rules.  This seems to work in Structural plasticity so far...
