### ISSUE TITLE
Add STDP Izhikevich binaries by default

### ISSUE THREAD

**Issue by andrewgait** [SpiNNakerManchester/sPyNNaker#679]
A few people are now using Izhikevich with STDP (thinking of @iambasab in particular).  We should probably add these by default to the build process (and by extension add the aplx files to the release).

**Comment by rowleya** [comment]
Happy for this to happen; note that in later code I am hoping the combinations will be made easier by the splitting of the neuron and synapse models on to different cores, but for now adding extra models is fine.
