### ISSUE TITLE
Crashes if call getSpikes() on recorded population that contained no spikes after run

### ISSUE THREAD

**Issue by alandiamond** [SpiNNakerManchester/sPyNNaker#70]
See abstract_recordable_vertex.py
Line 164
result = result[numpy.lexsort((spike_times, spike_ids))]
If spike_ids is zero length then lexsort crashes

Need to add check for zero length list .
if len(spike_ids) > 1:
	        result = result[numpy.lexsort((spike_times, spike_ids))]

**Comment by alan-stokes** [comment]
cannot reproduce in current master branch, will assume this issue is closed. Please feel free to reopen it if this issue resurfaces after the arbitiary release.
