### ISSUE TITLE
Wrong variable in live poisson control code

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/sPyNNaker#732]
https://github.com/SpiNNakerManchester/sPyNNaker/blob/6d4b17dea981455fc49b19312c549bd87608e69e/spynnaker/pyNN/connections/spynnaker_poisson_control_connection.py#L113

Should that be `control_label` instead of `label`, which is calculated from `label` a few lines above?

**Comment by Christian-B** [comment]
Quick fix with https://github.com/SpiNNakerManchester/sPyNNaker/pull/733

**Comment by Christian-B** [comment]
I think however the correct fix is either of.
1. Check label first time it is used and go pop if wrong.
2. Check and fix the label every time it is used.
Similar to configparser use of the optionxform format.
