### ISSUE TITLE
Maximum delay is not checked for random distribution

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#747]
The maximum delay value doesn't seem to be checked when using a RandomDistribution for delays.  The following fails by crashing the delay extension, but it should fail earlier as the high value provided is already out-of-range.

```
import spynnaker8 as sim
sim.setup(0.1)
pop_a = sim.Population(100, sim.IF_curr_exp(i_offset=5.0))
pop_b = sim.Population(100, sim.IF_curr_exp())
exc_delays = sim.RandomDistribution("normal_clipped", mu=1.5*15, sigma=0.75*15, low=0.1*15, high=14.4*15)
proj = sim.Projection(pop_a, pop_b, sim.AllToAllConnector(), sim.StaticSynapse(delay=exc_delays))
sim.run(1000)
sim.end()
```

**Comment by andrewgait** [comment]
Fixed in https://github.com/SpiNNakerManchester/sPyNNaker/pull/748.  Problem is the timestep value, not the RandomDistribution, at least as far as I can see.
