### ISSUE TITLE
requirement matplotlib missing in setup.py

### ISSUE THREAD

**Issue by bjuergens** [SpiNNakerManchester/sPyNNaker#753]
Matplotlib seems to be missing in `install_requires` in `setup.py`. Matplotlib is needed for the pip-installation of sPyNNaker8. 

When installing manually, this is not a big problem, but when installing it via requirements.txt on a build-server, it's a bigger issue. Just adding matplotlib to requirements.txt doesn't work, because package are installed simultaneous. 

reproduction of the issue with docker: 
```bash
docker run -it ubuntu:18.04 bash
apt update && apt install -y python-pip python-tk
pip install sPyNNaker8 # ImportError: No module named numpy
pip install sPyNNaker8 numpy # ImportError: No module named numpy
pip install numpy
pip install sPyNNaker8 # ImportError: No module named matplotlib
pip install sPyNNaker8 matplotlib # ImportError: No module named matplotlib
pip install matplotlib
pip install sPyNNaker8 # success
```

Expected behavior: One doesn't need to install matplotlib manually before installing sPynnaker8 with pip

What confuses me here, is that numpy seems to missing as well, but as far as I can tell, it is already part of install_requires. In our case that doesn't matter though since in our build-process numpy is already installed at this point

**Comment by dkfellows** [comment]
We don't include `matplotlib` in there because it causes problems on our testing infrastructure, as it is _very_ finicky to install right in virtualized containers such as are used by Travis and Readthedocs.

Numpy probably ought to work out of the box these days. While it used to be a complete pain, recent versions (past few years!) are fine.

**Comment by Christian-B** [comment]
Please also not that due to an unexpected change between PyNN 0.9.3 and PyNN 0.9.4 our latest release does not work with PyNN 0.9.4

So either please install PyNN 0.9.3 first or change the Spynnaker8 requirements from
pynn >= 0.9.1, < 0.10
to
pynn = 0.9.3

The master branch does work with PyNN 0.9.4

**Comment by dkfellows** [comment]
Hmm, can't figure out why numpy isn't being searched for, as it is definitely in the transitive closure of the requirements, and by several routes.

**Comment by dkfellows** [comment]
See also our installation instructions:
http://spinnakermanchester.github.io/spynnaker/5.0.0/PyNNOnSpinnakerInstall.html

**Comment by bjuergens** [comment]
Thanks. 

It looks like the issue comes from farther upstream. CSA doesn't seem to list its requirements correctly: https://github.com/INCF/csa/blob/92b77b67d2f04363d703a320e381766a6f8f7628/setup.py#L41

**Comment by bjuergens** [comment]
the error was, that csa was importing itself during it's own setup.py. By doing that all dependencies of it were also imported and setup.py crashed if the dependencies weren't met beforehand.

the upstream error is now fixed. You can now install spynnaker via pip without any preparations.  There is no need for you to change anything in the spynnaker package. I recommend removing the now obsolete steps from the documentation http://spinnakermanchester.github.io/spynnaker/5.0.0/PyNNOnSpinnakerInstall.html

here is a minimal viable example to show the fix is working 

```bash
docker run -it ubuntu:18.04 bash
apt-get update && apt-get install -y python-pip
pip install sPyNNaker8 # success
```

Also I noticed, that csa gets a special treatment in [spynnaker's setup.py](https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/setup.py#L38). I suspect, that this can now also be simplified. I'm not sure about this though.

**Comment by bjuergens** [comment]
> We don't include matplotlib in there because it causes problems on our testing infrastructure, as it is very finicky to install right in virtualized containers such as are used by Travis and Readthedocs.

I have noticed, that you can solve most of these problems with `export MPLBACKEND=agg`
