### ISSUE TITLE
Output when an error is encountered is too big

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#77]
Currently when an error is encountered, a check is done to see which cores are OK and which are not.  The display then shows the state of all cores, not just those with an error.  This makes it hard to debug what has gone wrong.

**Comment by alan-stokes** [comment]
so the turn_break_downs_into_strings took the sucessful cores as well the unsuccessful ones in its params. so by removing this, itll now only preoduce output for the failed cores. 

located under brnach #reduced_core_output brnach in SpiNNFrontEndCommon
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/tree/reduced_core_output
awaiting pull request #4

**Comment by rowleya** [comment]
Fixed in master
