### ISSUE TITLE
PyNN compliance for neuron model constructor signature 

### ISSUE THREAD

**Issue by pabogdan** [SpiNNakerManchester/sPyNNaker#772]
I've just noticed that our neuron models accept additional parameters not defined in PyNN .e.g `v=-65.0, exc_response=0.0, exc_exp_response=0.0,
inh_response=0.0, inh_exp_response=0.0` in
https://github.com/SpiNNakerManchester/sPyNNaker/blob/1589f7616f3b608744d486a2fb00172109ace165/spynnaker/pyNN/models/neuron/builds/if_curr_alpha.py#L34-L37

Is this the ideal way of doing things?

**Comment by rowleya** [comment]
Note that these are "initial_values".  You can't set them through creating a Population I don't think; you have to call initialise on the Population.

It does look like we have different parameters however from PyNN - it looks like PyNN only has tau_syn_E and tau_syn_I for that model.  Do we know how to derive the other values from this?

**Comment by apdavison** [comment]
You should be able to do something like:
```p = Population(size, celltype, initial_values={'v': -73.4. 'isyn_exc': 0.0})```

This is equivalent to:
```p = Population(size, celltype)
p.initialize(v=-73.4, isyn_exc=0.0)```

**Comment by rowleya** [comment]
Ah yes, I had forgotten about initial_values; i'm pretty sure we do support this, and things marked as "default_initial_values" I think are *only* supported via these mechanisms.

**Comment by pabogdan** [comment]
Right, very well then. Thanks guys!
