### ISSUE TITLE
Speed up reading and writing of SpiNNMan

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#79]
SpiNNMan is currently quite slow in terms of reading and writing large amounts of data.

**Comment by rowleya** [comment]
There is now a version in the speed_up_data_transfer_2 branch that can do up to 33Mbits/s reads.  I now need to fix the remaining functionality to use this.

**Comment by rowleya** [comment]
Note that there are some features in the branch that are not currently in use; for example, it is possible to detect the number of packets automatically to some extent, but this only really works when reading from chip 0, 0.  With other chips, this leads to timeouts.

**Comment by rowleya** [comment]
Finished but in testing and awaiting merge

**Comment by alan-stokes** [comment]
merged!!!!!! closed!!!!!!! WWOOOOP!
