### ISSUE TITLE
Multiple KernelConnector projections between the same two populations give SynapticConfigurationException

### ISSUE THREAD

**Issue by ej159** [SpiNNakerManchester/sPyNNaker#798]
I'm trying to do convolution with the KernelConnector between two populations. The convolution has a number of channels of depth (typically >10). When running with FromList connectors this does not typically happen. I've tried this with master and pop_based_master_pop_table branches and encounter the same thing.

``` python 
import numpy as np
import spynnaker8 as p

x_res = 100.
y_res = 100.

shape_pre = np.asarray([x_res, y_res])
shape_kernel = np.asarray([5, 5])
pre_sample_steps = (1,1)
start_location = np.asarray((shape_kernel/2).astype(int))
shape_post = np.asarray([int((x_res - shape_kernel[0]) / pre_sample_steps[0]) + 1, int((y_res - shape_kernel[1]) / pre_sample_steps[1]) + 1])


kernels = [np.clip(np.random.rand(*shape_kernel), a_min=0, a_max=None) for i in range(32)]


print("shape_pre", shape_pre)
print("shape_post", shape_post)
print("shape_kernel", shape_kernel)
print("pre_sample_steps", pre_sample_steps)
print("start_location", start_location)

p.setup(timestep=1)
p.set_number_of_neurons_per_core(p.IF_curr_exp, 16)
p.set_number_of_neurons_per_core(p.SpikeSourceArray, 16)


spike_times = [[i] for i in range(int(x_res*y_res))]

pre_pop = p.Population(x_res*y_res, p.SpikeSourceArray(spike_times=spike_times))

post_pop = p.Population(shape_post[0]*shape_post[1], p.IF_curr_exp())

def make_projection(kernel):
    return p.Projection(pre_pop, post_pop, p.KernelConnector(shape_pre=shape_pre,
                                                           shape_post=shape_post,
                                                           shape_kernel=shape_kernel,
                                                           weight_kernel=kernel,
                                                           post_sample_steps_in_pre=pre_sample_steps,
                                                           post_start_coords_in_pre=start_location),
                                                           receptor_type='excitatory')


projections = [make_projection(kernel) for kernel in kernels]

runtime = x_res*y_res
p.run(runtime)

```

**Comment by rowleya** [comment]
What is the error that you encounter?

**Comment by ej159** [comment]
```spynnaker.pyNN.exceptions.SynapticConfigurationException: Address 0x89c9710 is out of range for this population table!```

**Comment by andrewgait** [comment]
The problem, I think, is that currently the value returned by get_n_connections_from_pre_vertex_maximum(...) in the KernelConnector is likely an overestimate.  We'd have to do some maths to work out a better value here...

**Comment by andrewgait** [comment]
https://github.com/SpiNNakerManchester/sPyNNaker/pull/799 fixes this issue, but I tried running the script further and got RTE API errors and the message:

`2020-03-05 18:21:43 ERROR: 1, 26, 3: Could not allocate master population address list (population_table_binary_search_impl.c: 128)`

I noticed that @ej159 was running something similar at the same time so I don't know whether he saw something similar or not... I guess we leave this open for now, and maybe open a different issue if necessary?

**Comment by andrewgait** [comment]
Hi @ej159 (and maybe @such-a-git has something to add here too) - I was wondering whether you could send through your equivalent FromListConnector example (compared to the KernelConnector example).  We are wondering whether there's some difference in the resulting connection matrices which could explain why one works and the other doesn't... (it could also still be that there's some underlying estimation that's not quite right in the KernelConnector, but we've done some back-of-the-envelope calculations that suggest that the numbers you're using being to approach SDRAM limits).
