### ISSUE TITLE
get_global_parameters is it dead?

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#802]
Defined in NeuronRecorder and MyNeuronModelInclInputAndThreshold

Only use found was in a test.

Nuke?

**Comment by rowleya** [comment]
This looks like MyNeuronModelInclInputAndThreshold is not up-to-date.  There is now a get_global_values that works on global parameters, so any method called get_glocal_parameteres is likely out-of-date.
