### ISSUE TITLE
Can no longer record spikes from Spike Source Array

### ISSUE THREAD

**Issue by SimonDavidson** [SpiNNakerManchester/sPyNNaker#82]
Mainstream PyNN allows the network designer to record spikes from a spike source array in the same one can record any population.We could do this on SpiNNaker until th latest release when attempting this now gives an error, stating that it is not possible (so it's not a bug, it's as designed).

This seems like a backwards step for several reasons. First, PyNN supports it. Second, scripts that worked before have suddenly stopped working. Third, if the intention was to save effort because we should already know what the spikes are without asking the hardware, this still creates lots of extra work for the user to process these spikes separately to produce a graph or whatever.

If we can reserve space to capture spikes from neurons, we should be able to do it for the spike sorce arrays too, as we wee able to do before.

**Comment by rowleya** [comment]
It is easy enough to do this in the short term by having the script convert the input spikes in to a pynn-compatible spike array.

We could do a recording in the sdram, but this would either 1) not fit if the number of spikes exceeded the sdram buffer (which is 8mb at maximum; another 8mb would be too much) or 2) if the number of spikes is less than the buffer, it would simply be a copy of the buffer!  Buffered-out would solve the former case, but not the latter.  We should investigate this recording for live input however, but as this is new functionality (you couldn't input live at all previously), it is not as important.

I would therefore suggest that as a first implementation, record sets up to make a copy of input spikes, and getSpikes then returns the copy.

Sent from my android device.

-----Original Message-----

**Comment by alan-stokes** [comment]
clone of #122 (even though im sure this came first, the other one has had more activity, so closing this one.
