### ISSUE TITLE
pop based master pop vs bit-field expander

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#820]
this will currently cause a issue. as the per core key will no longer map to a unique master pop entry. 

it will require the expander to pre process the master pop table and incoming core keys to figure out the max bitfield length and create the corrasponding bitfield. 

left as a issue so that i dont forget when these two meet

**Comment by rowleya** [comment]
Note that for entries to be combined, there must be a single key that combines the incoming keys.  Additionally, there is a routing table generator that will actually put this key in the routing table.  The combination of these two things mean that you can probably just do what you do now, with the exception that you might need to cope with the vertex slices being a single big slice.

The other issue could be that the bit field might be rather big, and if it doesn't fit for the whole vertex you might have to reject it completely.  Alternatives to this include allowing sub-ranges which have bit fields e.g. if I have neurons 0-1000, allow (somehow) that neurons 0-255 have a bitfield but the rest don't.

**Comment by alan-stokes** [comment]
> Additionally, there is a routing table generator that will actually put this key in the routing table. The combination of these two things

I knew there was something that scared the brown stuff out of me. THAT def will break the sorter of the bit_field_compressor as when it builds the neuron level stuff, it assumes there is a 1 to 1 nature on bit-field key to routing table entry. there's a many to 1 in bitfields with same key over different processors. but 1 to 1 of key to entry. 

you MIGHT be right that when they all working in harmony, they might just work......but unknown. 

> Alternatives to this include allowing sub-ranges which have bit fields e.g. if I have neurons 0-1000, allow (somehow) that neurons 0-255 have a bitfield but the rest don't.

unless thats also at the master pop level, its going to cause untold issues for how the master pop bitfield tie in works. as it uses the same index in 2 arrays to match. 

thus why i put a issue here. coz im not sure if there is a issue, or what the issue impacts. but we might ned to face these at some points. so putting brain cycles on paper incase i forget something later on

**Comment by andrewgait** [comment]
As both these changes are now in master (and have been for a while), I think this issue can be closed (and reopened if needed).
