### ISSUE TITLE
Calculation of synaptic row lengths incorrect

### ISSUE THREAD

**Issue by neworderofjamie** [SpiNNakerManchester/sPyNNaker#83]
After much painful debugging I found that in the case of short synaptic rows, population_table_get_address mis-calculates the length of short synaptic rows e.g. when there's just 1 plastic synapse, the following row layout is typical:

word 0 - num plastic words
words 1 - 2 - plastic header
word 3 - plastic synapse (padded to a whole word)
word 4 - num fixed synapses
word 5 - num plastic synapses
word 6 - fixed plastic control (padded to whole word)

And with N_SYNAPSE_ROW_HEADER_WORDS == 3, only 4 words get DMAd in, leaving the whole fixed region to the mercy of whatever was in the DMA buffer before..

The hacky solution would just be to increase N_SYNAPSE_ROW_HEADER_WORDS to something >= 6 (and whatever the python equivalent is) to something larger, but IMO, the proper solution is to store synaptic row lengths in bytes so the population table doesn't need to know anything about their internal implementation.

**Comment by neworderofjamie** [comment]
Thinking a little more about this, I suspect the row size table masked this problem previously when we were using the linear master population table

**Comment by rowleya** [comment]
The way the system currently works is that it asks the synapse row io for the number of words required.  I have had a look at the plastic synapse row io objects, and found some issues.  I have now replaced these in the “fix_plastic_row_size” branch of sPyNNaker:
https://github.com/SpiNNakerManchester/sPyNNaker/commit/a923b9908c5e16c5cad22a031d8526629a439f64

Have a look and see if these work any better.  I think that the one for the plastic_weight_synapse_row_io.py is fine (this seems to just be 16-bit fixed part and 16-bit plastic weights, so the number of words is the number of connections).  I am less sure about the plastic_weight_control_synapse_row_io.py change (this seems to be 16-bit fixed part, with 32-bit plastic weights and some header words).

As you say, these have not changed between versions, so are likely only to have worked in the old version by chance!

**Comment by neworderofjamie** [comment]
Umm, I can entirely believe that the vertexslice crud has been superseded by synapse_row.get_n_connections, but I'm not convinced by the rest of that change. How come the plastic region header size is now being ignored? Also, I'm pretty sure the bit handling odd numbers of synapses is necessary as the plastic region and fixed-plastic region are both word-aligned within the row so if you have an odd number of 16-bit weights and their associated control words e.g. 3, both sections will need to be padded to 2 words meaning the total is 4 words rather than 3.

To be honest, I don't believe this is related to the problem I was seeing - The data was all there (I was just manually adding a couple of words to the DMA length). The problem was that the row lengths in the table were in terms of synapses which means the C-code needs to be either very conservative and potentially fetch more data than in required or psychic about the contents of the row it's DMAing to get it's size. I think the master population table just needs to operate in words/bytes rather than number of synapses.

**Comment by neworderofjamie** [comment]
I merged your change into my branch and, I think fixed the original issue and another horror I spotted in the process - see https://github.com/SpiNNakerManchester/sPyNNaker/commit/d9d02b0842b0fff5e513a64e58b276e96080b30a
