### ISSUE TITLE
SynapseDynamicsStructuralStatic vs SynapseDynamicsStructuralCommon initial delay / initial weight docs cant agree

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#833]
The issue arises from @dkfellows trying to add docs to these classes. Unfortunately there is a mismatch that @pabogdan will likely be able to solve in no time. 

https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_static.py#L47
says the initial delay is a float, or a (float, float)

whereas 
https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py#L107
says the initial delay is a int or a (int, int)

and the default is a int from here:
https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py#L90

and the weight disagrees from here, where its a int
https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py#L89

given that weights and delays are usually a float. id personally say its a float. But im not 100% here. As peter owns the structural stuff (as shown by line 33) i bow to him to fix.

the doc changes are going to be going in very shortly. so may be worth waiting till they go in to avoid conflcits.

**Comment by pabogdan** [comment]
Everything is definitely meant to be float. Good spot!
