### ISSUE TITLE
AbstractSynapseDynamicsStructural inheritance and docs dont match up. 

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#835]
The issue arises from @dkfellows trying to add docs to these classes. Unfortunately there is a mismatch that @pabogdan will likely be able to solve in no time.

This the docs of is_same_as causes the flagging of some very strange inheritance here. 
the docs for this within the common class states that the param should be of some type from SynapseDynamicsStructuralCommon, as shown here:

https://github.com/SpiNNakerManchester/sPyNNaker/blob/graph-mapping-sanity/spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py#L503

But we can see that inherited from only object and is not inherited directly from here: 
https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py#L29
and here:
https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_static.py#L68

This means the structural calls to is_same_as should always fail when handed SynapseDynamicsStructuralStatic or SynapseDynamicsStructuralSTDP as they are not family members. The reason it doesn't is due to not testing the family, but assuming duck typing levels of equivalence. 

I honestly dont see how youd get out of this without adding SynapseDynamicsStructuralCommon to the inheritance tree of the SynapseDynamicsStructuralStatic and SynapseDynamicsStructuralSTDP, but i persume @pabogdan will be able to fix it so that the docs do not disagree with each other in some way.

**Comment by Christian-B** [comment]
fixed when cleaning up common.
