### ISSUE TITLE
SynapseDynamics can not handled unrequired edges.

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#848]
The way SynapseDynamics currently works it can not handle the situation where unnecssary MachineEdges are removed.

To replicate:
1. in ProjectionApplicationEdge comment out the block "if _are_dynamics_structural("
2.run p8_integration_tests/quick_test/test_struct_pl/test_structural_without_stdp.py

**Comment by andrewgait** [comment]
Why would you comment out that block and then expect a structural plasticity test to work?  If the dynamics are structural then machine edges should not be removed, ever.

**Comment by rowleya** [comment]
The issue is that quite a few structural tests start with no connectivity, so then the edges get removed and structural plasticity won't be able to restore them.  Because it *can* add new connections, it makes no sense to remove a structural edge because of no existing connections at the start.

**Comment by Christian-B** [comment]
An open question is:
Should structural plasticity added edges that are not part of the original connector not even with weight zero.

For example
Give a OnetoOne conncector should it be allowed to learn a link between neuron 5 on the source and neuron 8 on the destination.
Given a from List could it learn ones not in the list. 
In other words is the assumption that all none specifically mentioned connections are there but just start with a weight of zero?

**Comment by rowleya** [comment]
Yes, it should be able to (and does) learn new connections that are not in the original connector.  The projection *is* required, and the connector specifies the initial connectivity, even if empty.

**Comment by Christian-B** [comment]
If what @rowleya says is correct and that the role of the connector is only to specify the None zero connector then clearly No edge may be filtered.
