### ISSUE TITLE
orphan DelayExtensionVertex

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#850]
it is possible that all the edges into a DelayExtensionVertex are filtered out.

to repliacte:
import spynnaker8 as sim
sim.setup(timestep=1.0)
sim.set_number_of_neurons_per_core(sim.IF_curr_exp, 2)
sim.set_number_of_neurons_per_core(sim.SpikeSourceArray, 2)
pop_1 = sim.Population(4, sim.IF_curr_exp(), label="pop_1")
input = sim.Population(10, sim.SpikeSourceArray(spike_times=[0]), label="input")
input_proj = sim.Projection(input, pop_1, sim.OneToOneConnector(),
synapse_type=sim.StaticSynapse(weight=5, delay=21))
sim.run(40)

In https://github.com/SpiNNakerManchester/sPyNNaker/pull/847 there is a workaround which avoids errors by writing zeros for the unkown values.
See: https://github.com/SpiNNakerManchester/sPyNNaker/blob/0cd1c37d69ea54e77ba9e54367249b96bfd18a48/spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py#L254

**Comment by Christian-B** [comment]
I dont suggest trying to fix this until well into the self paritioning work

**Comment by alan-stokes** [comment]
isnt the easy fix to this to do what EVERY other vertex does and has has key and key. adn then delay just checks the bool before firing?

**Comment by alan-stokes** [comment]
pr that i think fixes it in a better way. coz saying key 0 is odd.....plus i would still fire with key 0. and i have no idea what that would do. likely lots of dropped packets.

**Comment by Christian-B** [comment]
This needs to be fixed by avoiding that the DelayExtensionVertex is ever created in the first place.

Something that  can be done once delay extension are added on the fly rather than when projections are created,
