### ISSUE TITLE
Support for booting multi-board systems

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#87]
Currently, it is not possible to boot a multi-board system from SpiNNMan.  We currently use the machine name and the board version for booting.  

This would be extended with the number of boards.  For simplicity, this would assume a certain layout of the boards, with this being stored somewhere (along with an assumed BMP configuration).  

For flexibility, some additional optional parameters would override this assumption, namely the x_size and y_size of the configuration, and a list of BMP ids in use.

**Comment by rowleya** [comment]
Of course, a BMP IP address would also be needed!

**Comment by alan-stokes** [comment]
done and merged and closed
