### ISSUE TITLE
odd smell here

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#878]
on synaptic_manager line 359 https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/neuron/synaptic_manager.py#L343-L359, a overscale is used (aka a fudge for safety).

 this is fine when being done for partitioning sdram estaimtes. but this came method is called at dsg time via line 1214 
in generate dsg. 
https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/neuron/synaptic_manager.py#L1214-L1215

this means we're adding the fudge in at dsg time. which seems wrong. but not sure. needs looking at.

**Comment by rowleya** [comment]
My personal view is that whatever you say you need from the SDRAM size should be what you then allocate in the DSG.  This simplifies the debugging somewhat.

**Comment by alan-stokes** [comment]
whereas i agree in some level. there are many many places where we have both a estimate AND an exact sdram calc. where the estimate is used for partitioning and the exact is used during dsg. and as long as exact < estimate life is good. 

given we fixed the structural to not use the estimate when doing dsg allcoation, when it can indeed find the data for exact, it would be fair to ensure we follow suit, and this smells as a use of a estimate logic. 

If we CANT figure the exact in a sensible manner (aka to do so would require connectivity expanded on host) then fine and dandy, id like a comment in the dsg code when we call it to state such, if we can figure the exact. it would be better of us to do so.

**Comment by rowleya** [comment]
If the estimate is wrong and too small (it can happen), then allocating a larger space at DSG will cause the code to blow up whilst attempting to allocate recording regions.  We shouldn't do that.  If you estimate wrong, you reserve wrong and you find out at that point which at least tells you which region of which vertex you got wrong, rather than finding out that one vertex on a chip was wrong and you don't know which...

**Comment by alan-stokes** [comment]
so what ya proposing. removing all the exacts from the calculations? and just using estimates throughout. that seems wonky. 

I agree that if a estimate is too small, ya shat yaself, but that's why im saying estimates should ALWAYS be larger, and then exact can allocate exact if possible so that we use the sdram as well as we can. Diagnosing when ya estimate is too small is a problem, but current master has a mix and is predominated towards estimates for partitioning and exact for dsg. so either we need to gut the whole system to use estimates, or this point smells funny.

**Comment by rowleya** [comment]
If you can get an exact at partitioning time, use exact.  If not use an estimate.  Once you have a size for SDRAM usage, you should then use that in the DSG; or else if you want to use an exact value in the DSG the code should at that point validate that the value is not more than the estimate and error if it is (this is not done automatically, though that would also be a solution).  Using different values in SDRAM resources and DSG without checking is likely to be a source of error, and worse one that is hard to find!

**Comment by rowleya** [comment]
Note you said that the estimate should ALWAYS be larger.  With random numbers, the only way to guarantee that is to use an infinite sized region.

**Comment by alan-stokes** [comment]
well there is a question about @Christian-B 's multi sdram (im not sure if that got into master yet) which would allow you to chekc dsg exacts vs estimate on a region by region basis. allowing you your 
>  (this is not done automatically, though that would also be a solution).

if we ignore the multisdram for this. what are you proposing then? we remove all exacts and just use the estimated calcs in all of dsg?

**Comment by rowleya** [comment]
Well the solution is either:
1. to wait for multisdram and then do this automatically if that is then possible. The issue in that case is to ensure that everyone uses multisdram, and that it supports something that ties together regions between the estimates and the allocations.
1. go through and change all the places where we use an estimate in SDRAM followed by an exact in DSG and either:
    1. Change the code so that it uses the estimate in DSG as well.
    1. Change the code so that it checks whether the exact is > the estimate and error if it is.

**Comment by alan-stokes** [comment]
yep. and id argue that 2.ii is the easiest route, coz that's kinda how everything been operating. and @Christian-B did some work to stop the structural stuff from using an estimate in dsg. so would be a shame to throw that away and thus go to 2.i.

multi-sdram has conflicts but once the other 2 sets of prs are processed, i can try to de conflict it and see if it can be ready to go into master any time soon

**Comment by rowleya** [comment]
So long as it *is* checked against the estimate, I don't mind using exact numbers in the end if that can be achieved.

**Comment by alan-stokes** [comment]
so this still makes what this issue pointed at, a valid issue. and the conclusion is that we need to add more checks etc.

**Comment by Christian-B** [comment]
This is being fixed in https://github.com/SpiNNakerManchester/sPyNNaker/pull/876

**Comment by alan-stokes** [comment]
closed as #876 is in
