### ISSUE TITLE
Ports that can be allocated dynamically should be

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#88]
Some UDP ports are allocated using fixed numbers unnecessarily, making it difficult to use some features on shared machines.  These ports should instead be allocated dynamically (through requesting a socket without a local port), and then using the allocated port number.  Clearly this is more difficult if external communication is required; the database could also be used here however, with the option of specifying the port at the worst.

**Comment by alan-stokes** [comment]
fixed
