### ISSUE TITLE
verify FixedNumberPreConnector setting seed correctly

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#886]
FixedNumberPreConnector.gen_connector_params method

            self.__pre_connector_seed[key] = [
                int(i * 0xFFFFFFFF) for i in self._rng.next(n=4)]

@alan-stokes worries this could create a key outside of the acceptable range.

Same in FixedNumberPostConnector

**Comment by alan-stokes** [comment]
ya also got it here:

https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/neural_projections/connectors/abstract_generate_connector_on_machine.py#L97-L108

**Comment by alan-stokes** [comment]
and
https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/neural_projections/connectors/abstract_generate_connector_on_machine.py#L110-L128

**Comment by andrewgait** [comment]
Do you mean a key outside the acceptable range, or a seed outside the acceptable range?  I'm not sure how the code that's there could do either of those...

**Comment by alan-stokes** [comment]
this comes from the not using:
https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/utilities/utility_calls.py#L285-L313

where the logic for when seed 1 = 0, or when seed[3] is > 698769069

**Comment by alan-stokes** [comment]
also: https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py#L351-L353

creates 1 int with the same * mask, but this is being used by a numpyRNG. what does the * 0x7FFFFFFF do in that scope? is this something that really needs to be mapped to a mar64 seed later on?

**Comment by andrewgait** [comment]
> this comes from the not using:
> https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/utilities/utility_calls.py#L285-L313
> 
> where the logic for when seed 1 = 0, or when seed[3] is > 698769069

I have to confess that I thought this was done in the C code for the expander (there's an equivalent function for this in spinn_common/random.c) but it would appear not.  So this probably does need fixing to validate the seeds, though I'm surprised that this hasn't caused problems before now...

**Comment by alan-stokes** [comment]
guessing that if youve got the bad numbers the seed just inst very random. how many end users check our randomness?
