### ISSUE TITLE
master pop table sdram requirements are wrong. 

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#892]
the fudge factor is applied to the exact cost model in the following lines:

https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/neuron/master_pop_table.py#L173-L177

But as this is meant to be the EXACT sdram, a fudge factor here makes no sense. 

But when it is removed the DSE errors on the master pop region for not having enough space. So there is obviously some other SDRAM cost that's not being taken into account that this fudge factor is hiding. 

It was found when augmenting the master pop table for self partition splitter objects. But is showable in master as well.

**Comment by andrewgait** [comment]
It looks to me as though both _OVERSCALE in master_pop_table and _SYNAPSE_SDRAM_OVERSCALE in synaptic_matrices.py are now no longer used after recent merges.  So I would suggest that this issue should be closed.

**Comment by rowleya** [comment]
Yes, I think these were there for delays, but now it actually checks for delays
