### ISSUE TITLE
get rid of the multiple test utility objects

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#893]
pacman, fec, spy  all over unit tests, build their own app verts etc. 

bloody well have 1 version and have the rest link to it. 

*throws pie at @Christian-B *

**Comment by Christian-B** [comment]
ApplicationVertex
PACMAN/uinit_test_objects/placer_test_support.py
PACMAN/uinit_test_objects/simple_test_vertex.py
PACMAN/unittests/model_tests/splitter_tests/test_one_app_one_machine.py 
PACMAN/unittests/model_tests/splitter_tests/test_splitter_slice_legacy.py
PACMAN/unittests/operations_tests/routing_info_algorithms_tests/test_zoned_routing_allocator.py
SpiNNFrontEndCommon/fec_integration_tests/test_buffer_manager_listener_creation.py
SpiNNFrontEndCommon/fec_integration_tests/interface/interface_functions/simple_test_vertex.py
SpiNNFrontEndCommon/unittests/interface/interface_functions/test_front_end_common_dsg_region_reloader.py
