### ISSUE TITLE
synaptic manager dsg regions being set in hardcoded manner

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#897]
for future support of slef parittioning, we should ensure these are parameters of the manager, not hardocded. as a synapse core ant going to want dsg regions .....6 onwards

**Comment by alan-stokes** [comment]
fixed by https://github.com/SpiNNakerManchester/sPyNNaker/pull/937

**Comment by dkfellows** [comment]
Is there any evidence that we will ever actually have varying region IDs? Or is this just prepping for a future that never comes?

**Comment by alan-stokes** [comment]
well theres 2 avenues. a conways app graph using a genral synaptic manager for edge data. should not be limtied to the pynn region ids. But further more, the synapse cores of the luca modle will highly likely not have the neuron params and thus would want different region ids. if we follow convention of going from 0 upwards, they would be lower numbers for them

**Comment by alan-stokes** [comment]
the ear vertex's which recievied from other neuron modles, had to contort themselves to supprot those fixed region ids. this way they no longer would need to contort

**Comment by Christian-B** [comment]
Will not fix as in discussion of https://github.com/SpiNNakerManchester/sPyNNaker/pull/937
