### ISSUE TITLE
Support distance-dependent delays

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#901]
PyNN supports synapses specified with distance dependent delays as described at the bottom of the Fixed Synaptic Weight section:
http://neuralensemble.org/docs/PyNN/connections.html#fixed-synaptic-weight

We should add support to this to the code.

**Comment by andrewgait** [comment]
Do you know how complicated the function of the distance is allowed to be in this instance?  Is it similar to what gets used for distance-dependent connections (i.e. there's a "safe list" of functions)?  Or is it more basic and simply just a linear representation as shown in the documentation?  (It's not clear from the PyNN documentation which of these it is...)

**Comment by rowleya** [comment]
I think it is based on the same safe-list of functions (likely anyway).

**Comment by rowleya** [comment]
I should add that on re-reading it, the weights can probably be a function of distance too.
