### ISSUE TITLE
bitfield misleading warning

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#916]
since the pop based master pop table came in. this warning has started appearing when there were no master pop entries.

[INFO] (population_table_binary_search_impl.c: 257): Population table has 0 entries
[INFO] (profiler.c: 36): Reading profile setup from 0x60243d14
[INFO] (profiler.c: 42): Initialising profiler with storage for 0 samples starting at 0x60243d18
[WARNING] (population_table_binary_search_impl.c: 306): Couldn't initialise basic bit field holder. Will end up doing possibly more DMA's during the execution than required. We required 0 bytes where 54972 are available

obviously there should be a if to stop trying when " Population table has 0 entries"

this is here to remind me once chasing down current error

**Comment by alan-stokes** [comment]
fixed by : https://github.com/SpiNNakerManchester/sPyNNaker/pull/917
tested by : https://github.com/SpiNNakerManchester/sPyNNaker8/pull/488

**Comment by andrewgait** [comment]
This was fixed by #917.
