### ISSUE TITLE
Update sEMD model

### ISSUE THREAD

**Issue by andrewgait** [SpiNNakerManchester/sPyNNaker#946]
Received a request from a user via email to make a minor modification to the sEMD model - repeating their email here so it's better tracked than just a PR.

"I am a PhD candidate at the Bioinspired Circuits and Systems
lab at the UNiversity of Groningen led by Prof. Dr. Elisabetta Chicca.
Approximately one year ago you helped Simon to set up our
sEMD model on the collab server. See here:

https://groups.google.com/g/spinnakerusers/c/ZPEXFtesi-A/m/g5pT2qU6DgAJ

The implementation is very helpful for us and many students are using it now. However, we would like to request a small change in sEMD SpiNNaker model. In the file synapse_types_semd_impl.h the parameter SCALING_FACTOR is set to 100.0k. Could you please set this factor to 1? How can I check out these changes
using the JupyterHub until they are embedded in the master branch?

Thank you very much and best regards,
Thorben Schoepe"

**Comment by rowleya** [comment]
It sounds like making that a parameter of the model would be useful

**Comment by andrewgait** [comment]
> It sounds like making that a parameter of the model would be useful

Yes, I have sent them an email suggesting this might be the best way forward.
