### ISSUE TITLE
Issues with numpy > 1.18

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#953]
It seems this version causes some issues in our software

**Comment by rowleya** [comment]
Attempting tests with Python3.8 here:
http://apollo.cs.man.ac.uk:8080/blue/organizations/jenkins/Integration%20Tests/detail/python3.8/1/pipeline

**Comment by dkfellows** [comment]
Either fixed or obsoleted. We're using the newer numpy anyway...
