### ISSUE TITLE
SpikeSourceArray PopulationView set_parameters doesn't work correctly

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#965]
The following doesn't seem to work, but I think it should:

```
import spynnaker8 as p
p.setup(1.0)
pop = p.Population(10, p.SpikeSourceArray([]))
pop[1].set_parameters(spike_times=[5])
```

Issue seems to be that you are setting an array value; it seems to think it needs to be the same size as the population (which it doesn't).

**Comment by rowleya** [comment]
Note that the "obvious" workaround also fails:
```
import spynnaker8 as p
p.setup(1.0)
pop = p.Population(10, p.SpikeSourceArray([]))
pop.set(spike_times=[[i] for i in range(10)])
```

This time, the setter isn't checking for list vs. item.  In this case, a numpy array solves the problem, but is only a workaround:
```
import spynnaker8 as p
import numpy

p.setup(1.0)
pop = p.Population(10, p.SpikeSourceArray([]))
pop.set(spike_times=[numpy.array([i]) for i in range(10)])
```

**Comment by alan-stokes** [comment]
going to ask a bunch of silly question i fear. 
pop[1] will give you a pop view. 
pop views dont have a set_parameters method. So it will never work that way. 
pop views do have a set method, which eventuallky goes to the pop commons's set_by_selector method, which i think will get to the SSA spike times setter. But its a full set. not a atrom speific set. 

so wouldnt
import spynnaker8 as p
p.setup(1.0)
pop = p.Population(10, p.SpikeSourceArray([]))
pop[1].set("spike_times", [5])

work?

**Comment by rowleya** [comment]
I think pop[1] is a cell rather than a PopulationView, so it should then have set_parameter.

**Comment by alan-stokes** [comment]
having reread the get titme method. as its a int, it would get a 
IDMixin
which does indeed have a set params. so it goes to the same place in the end, set value by selector. so what does id do in SSA set in the end?

**Comment by alan-stokes** [comment]
we think this is fixed now. please check and close accordingly.

**Comment by andrewgait** [comment]
This was fixed but for some reason the issue wasn't closed.
