### ISSUE TITLE
collapsing index variables

### ISSUE THREAD

**Issue by chanokin** [SpiNNakerManchester/sPyNNaker#967]
I'm not super fresh on my C but wouldn't the outer `i` (line 270) variable be overwritten by the input loops' `i` (lines 290 and 293)? Or is this something the awesome compiler catches and fixes automatically?

https://github.com/SpiNNakerManchester/sPyNNaker/blob/43ac5a7bc8b172a97ecb3804fd328c3d693136ad/neural_modelling/src/neuron/implementations/neuron_impl_standard.h#L270-L295

**Comment by rowleya** [comment]
If the compiler doesn't complain, I guess it must just shadow the variable.  It would still be better if it didn't though!
