### ISSUE TITLE
check unused integration tests

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#975]
these tests where moved from https://github.com/SpiNNakerManchester/sPyNNaker8 but not run.

They need to be checked and either moved to where they do run or deleted.

https://github.com/SpiNNakerManchester/sPyNNaker8/tree/master/p8_integration_tests/test_from_file_connector
https://github.com/SpiNNakerManchester/sPyNNaker8/tree/master/p8_integration_tests/test_new_model_templates
https://github.com/SpiNNakerManchester/sPyNNaker8/tree/master/p8_integration_tests/x_test

This was detected when looking at: https://github.com/SpiNNakerManchester/sPyNNaker/pull/958 but is out of scope for that PR!

**Comment by andrewgait** [comment]
https://github.com/SpiNNakerManchester/sPyNNaker8/tree/master/p8_integration_tests/test_new_model_templates is/was run by Jenkins, under "stage('Run new Model Example')" in the spynnaker8 Jenkinsfile.

https://github.com/SpiNNakerManchester/sPyNNaker8/tree/master/p8_integration_tests/test_from_file_connector isn't currently run but it's the only test for FromFileConnector, so it should probably be moved into quick_test/test_connectors (or somewhere like that).

I think the tests in x_test were considered unnecessary at some point in the past, but it might be worth someone going through them to check for certain.
