### ISSUE TITLE
Verify if Connectors need to inherit from pyNN.connectors

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#981]
https://github.com/SpiNNakerManchester/sPyNNaker/pull/958 merged the spy8 connectors and the spy connectors which is good.

Part of these merges flag up that some but not all of the connectors inherit from  pyNN.connectors

So the question is what is the benefit of this inheritance?
if good why not all connectors?

If no longer needed time to remove.

**Comment by andrewgait** [comment]
I don't think it's necessary as far as I can tell.  I paused for a minute with references to PyNN space objects (which are more relevant when https://github.com/SpiNNakerManchester/sPyNNaker/pull/974 is taken into consideration), but these come in via AbstractConnector.set_space(...) from a Projection, so I don't think the inheritance is needed.
