### ISSUE TITLE
Sdram costs off

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#991]
import spynnaker8 as sim
sim.setup(timestep=1.0)
pop_1 = sim.Population(1, sim.IF_curr_exp(), label="pop_1")
pop_1.record(["spikes", "v"])
sim.run(10)

causes:
[ERROR] (recording.c: 685): Could not allocate recording region

**Comment by Christian-B** [comment]
Putting an emergency fudge into https://github.com/SpiNNakerManchester/sPyNNaker/pull/990

**Comment by alan-stokes** [comment]
test is fixed by https://github.com/SpiNNakerManchester/sPyNNaker/pull/992 

adding this script to the intergration tests of that branch for coveraging

**Comment by Christian-B** [comment]
confirmed fixed by above prs
