### ISSUE TITLE
Unify New Models tests

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#998]
The crone job fails on 
https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/p8_integration_tests/test_new_model_templates/test_new_model_templates.py

yet this appears to be a subset of

https://github.com/SpiNNakerManchester/sPyNNaker8NewModelTemplate/tree/master/nmt_integration_tests

**Comment by rowleya** [comment]
The integration tests cron job passed... Do we want to continue to maintain the sPyNNaker8 ones?

**Comment by rowleya** [comment]
http://apollo.cs.man.ac.uk:8080/blue/organizations/jenkins/Integration_Tests_Cron_Job/activity

**Comment by Christian-B** [comment]
No lets nuke that too.

**Comment by rowleya** [comment]
OK, I have so far made it that it won't run any more but not deleted it completely.  I will leave this around for now but can delete it when we are sure we have everything from it.

**Comment by Christian-B** [comment]
https://github.com/SpiNNakerManchester/sPyNNaker8/pull/540 deletes the Jenkins files

**Comment by Christian-B** [comment]
fixed
